# Generated by Django 2.0.13 on 2019-08-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inclusao_alimentacao', '0001_initial'),
        ('escola', '0002_auto_20190826_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusoes_alimentacao_continua', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inclusao_alimentacao.MotivoInclusaoContinua'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grupos_inclusoes_normais', to='escola.Escola'),
        ),
    ]
