# Generated by Django 2.2.6 on 2019-12-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceirizada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0002_auto_20191205_1815'),
        ('inclusao_alimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusoes_alimentacao_continua', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inclusao_alimentacao.MotivoInclusaoContinua'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grupos_inclusoes_normais', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
    ]
