# Generated by Django 2.0.13 on 2019-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0002_auto_20190826_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinclusaoalimentacaonormal',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaocontinua',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaocontinua',
            name='outro_motivo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Outro motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaonormal',
            name='outro_motivo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Outro motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivoinclusaocontinua',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivoinclusaonormal',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
