# Generated by Django 2.2.8 on 2019-12-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0003_auto_20191206_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='foi_solicitado_fora_do_prazo',
            field=models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?'),
        ),
    ]
