# Generated by Django 2.2.6 on 2019-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0004_inclusaoalimentacaocontinua_foi_solicitado_fora_do_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='foi_solicitado_fora_do_prazo',
            field=models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?'),
        ),
    ]
