# Generated by Django 2.0.13 on 2019-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0006_grupoinclusaoalimentacaonormal_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivoinclusaocontinua',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='motivoinclusaonormal',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
