# Generated by Django 2.2.8 on 2020-02-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0007_inclusaoalimentacaodacei_quantidadedealunosporfaixaetariadainclusaodealimentacaodacei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadedealunosporfaixaetariadainclusaodealimentacaodacei',
            name='inclusao_alimentacao_da_cei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantidade_alunos_da_inclusao', to='inclusao_alimentacao.InclusaoAlimentacaoDaCEI'),
        ),
    ]
