# Generated by Django 2.2.6 on 2019-10-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0006_auto_20191008_1819'),
        ('escola', '0007_auto_20191008_1829'),
        ('inclusao_alimentacao', '0007_auto_20191008_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_grupoinclusaoalimentacaonormal_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaoalimentacaocontinua_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
    ]
