# Generated by Django 2.2.10 on 2020-04-24 20:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0009_auto_20200221_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusaoalimentacaocontinua',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], default=[], null=True), size=None),
        ),
    ]
