# Generated by Django 2.2.13 on 2020-10-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0011_inclusaoalimentacaodacei_outro_motivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantidadeporperiodo',
            options={'verbose_name': 'Quantidade por periodo', 'verbose_name_plural': 'Quantidades por periodo'},
        ),
    ]
