# Generated by Django 2.2.13 on 2022-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0016_inclusaoalimentacaocontinua_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadeporperiodo',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
    ]
