# Generated by Django 2.2.13 on 2022-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0017_auto_20220411_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusaoalimentacaodacei',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
    ]
