# Generated by Django 2.2.13 on 2022-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0018_auto_20220426_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Esta cancelado?'),
        ),
    ]
