# Generated by Django 2.2.13 on 2022-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0019_inclusaoalimentacaonormal_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='cancelado_justificativa',
            field=models.CharField(blank=True, max_length=500, verbose_name='Porque foi cancelado individualmente'),
        ),
    ]
