# Generated by Django 2.2.13 on 2022-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0022_auto_20220707_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadeporperiodo',
            name='numero_alunos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
