# Generated by Django 2.2.13 on 2022-09-05 16:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0053_periodoescolar_tipo_turno'),
        ('terceirizada', '0007_auto_20211008_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inclusao_alimentacao', '0024_auto_20220720_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusaoDeAlimentacaoCEMEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('foi_solicitado_fora_do_prazo', models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?')),
                ('terceirizada_conferiu_gestao', models.BooleanField(default=False, verbose_name='Terceirizada conferiu?')),
                ('status', django_xworkflows.models.StateField(max_length=37, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_VALIDADO', 'DRE_PEDIU_ESCOLA_REVISAR', 'DRE_NAO_VALIDOU_PEDIDO_ESCOLA', 'CODAE_AUTORIZADO', 'CODAE_QUESTIONADO', 'CODAE_NEGOU_PEDIDO', 'TERCEIRIZADA_RESPONDEU_QUESTIONAMENTO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'CANCELADO_AUTOMATICAMENTE']))),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusoes_de_alimentacao_cemei', to='escola.Escola')),
                ('rastro_dre', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaodealimentacaocemei_rastro_dre', to='escola.DiretoriaRegional')),
                ('rastro_escola', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaodealimentacaocemei_rastro_escola', to='escola.Escola')),
                ('rastro_lote', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaodealimentacaocemei_rastro_lote', to='escola.Lote')),
                ('rastro_terceirizada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusao_alimentacao_inclusaodealimentacaocemei_rastro_terceirizada', to='terceirizada.Terceirizada')),
            ],
            options={
                'verbose_name': 'Inclusão de alimentação CEMEI',
                'verbose_name_plural': 'Inclusões de alimentação CEMEI',
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, sme_terceirizadas.dados_comuns.behaviors.Logs, sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade, models.Model),
        ),
        migrations.CreateModel(
            name='QuantidadeDeAlunosPorFaixaEtariaDaInclusaoDeAlimentacaoCEMEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_alunos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('matriculados_quando_criado', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.FaixaEtaria')),
                ('inclusao_alimentacao_cemei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade_alunos_cei_da_inclusao_cemei', to='inclusao_alimentacao.InclusaoDeAlimentacaoCEMEI')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar')),
            ],
            options={
                'verbose_name': 'Quantidade de alunos por faixa etária da inclusao de alimentação CEMEI',
                'verbose_name_plural': 'Quantidade de alunos por faixa etária da inclusao de alimentação CEMEI',
            },
        ),
        migrations.CreateModel(
            name='QuantidadeDeAlunosEMEIInclusaoDeAlimentacaoCEMEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_alunos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('matriculados_quando_criado', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('inclusao_alimentacao_cemei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade_alunos_emei_da_inclusao_cemei', to='inclusao_alimentacao.InclusaoDeAlimentacaoCEMEI')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar')),
            ],
            options={
                'verbose_name': 'Quantidade de alunos EMEI por inclusao de alimentação CEMEI',
                'verbose_name_plural': 'Quantidade de alunos EMEI por inclusao de alimentação CEMEI',
            },
        ),
        migrations.CreateModel(
            name='DiasMotivosInclusaoDeAlimentacaoCEMEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outro_motivo', models.CharField(blank=True, max_length=500, verbose_name='Outro motivo')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Esta cancelado?')),
                ('cancelado_justificativa', models.CharField(blank=True, max_length=500, verbose_name='Porque foi cancelado individualmente')),
                ('inclusao_alimentacao_cemei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_motivos_da_inclusao_cemei', to='inclusao_alimentacao.InclusaoDeAlimentacaoCEMEI')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inclusao_alimentacao.MotivoInclusaoNormal')),
            ],
            options={
                'verbose_name': 'Diaa e motivo inclusão de alimentação CEMEI',
                'verbose_name_plural': 'Dias e motivos inclusçao de alimentação CEMEI',
                'ordering': ('data',),
            },
        ),
    ]
