# Generated by Django 2.2.13 on 2022-11-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0026_quantidadedealunosporfaixaetariadainclusaodealimentacaodacei_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusaoalimentacaodacei',
            name='periodo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar'),
        ),
    ]
