# Generated by Django 2.2.13 on 2023-01-04 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migracao_dados(apps, _):
    InclusaoAlimentacaoDaCEI = apps.get_model('inclusao_alimentacao', 'InclusaoAlimentacaoDaCEI')
    DiasMotivosInclusaoDeAlimentacaoCEI = apps.get_model('inclusao_alimentacao', 'DiasMotivosInclusaoDeAlimentacaoCEI')
    for inclusao_cei in InclusaoAlimentacaoDaCEI.objects.all():
        dia_motivo = DiasMotivosInclusaoDeAlimentacaoCEI(
            inclusao_cei=inclusao_cei,
            motivo=inclusao_cei.motivo,
            data=inclusao_cei.data,
            outro_motivo=inclusao_cei.outro_motivo
        )
        dia_motivo.save()


def backwards(apps, _):
    DiasMotivosInclusaoDeAlimentacaoCEI = apps.get_model('inclusao_alimentacao', 'DiasMotivosInclusaoDeAlimentacaoCEI')
    DiasMotivosInclusaoDeAlimentacaoCEI.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0029_auto_20221221_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasMotivosInclusaoDeAlimentacaoCEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cancelado', models.BooleanField(default=False, verbose_name='Esta cancelado?')),
                ('cancelado_justificativa', models.CharField(blank=True, max_length=500, verbose_name='Porque foi cancelado individualmente')),
                ('outro_motivo', models.CharField(blank=True, max_length=500, verbose_name='Outro motivo')),
                ('inclusao_cei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_motivos_da_inclusao_cei', to='inclusao_alimentacao.InclusaoAlimentacaoDaCEI')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inclusao_alimentacao.MotivoInclusaoNormal')),
            ],
            options={
                'verbose_name': 'Dia e motivo inclusão de alimentação CEI',
                'verbose_name_plural': 'Dias e motivos inclusão de alimentação CEI',
                'ordering': ('data',),
            },
        ),
        migrations.RunPython(migracao_dados, backwards),
        migrations.RemoveField(
            model_name='inclusaoalimentacaodacei',
            name='data',
        ),
        migrations.RemoveField(
            model_name='inclusaoalimentacaodacei',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='inclusaoalimentacaodacei',
            name='outro_motivo',
        ),
    ]
