# Generated by Django 2.2.13 on 2023-01-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0030_diasmotivosinclusaodealimentacaocei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusaoalimentacaodacei',
            name='data',
        ),
        migrations.RemoveField(
            model_name='inclusaoalimentacaodacei',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='inclusaoalimentacaodacei',
            name='outro_motivo',
        ),
    ]
