# Generated by Django 2.2.13 on 2023-01-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inclusao_alimentacao', '0031_auto_20230105_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasmotivosinclusaodealimentacaocei',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='diasmotivosinclusaodealimentacaocei',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diasmotivosinclusaodealimentacaocemei',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='diasmotivosinclusaodealimentacaocemei',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodo',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodo',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
