M = "Manhã"
T = "Tarde"
I = "Integral"

DESPERDICIO_PERIODO = ["M", "T", "I"]

CR = "CLASSIFICAÇÃO DE RESTO"
CS = "CLASSIFICAÇÃO DE SOBRA"
AR = "ACEITABILIDADE DAS REFEIÇÕES"

CLASSIFICACAO_TIPO = ["CR", "CS", "AR"]