# Generated by Django 2.2.6 on 2019-12-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('escola', '0002_auto_20191205_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='periodo_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='tipo_unidade_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.TipoUnidadeEscolar'),
        ),
        migrations.AddField(
            model_name='tipoalimentacao',
            name='substituicoes',
            field=models.ManyToManyField(blank=True, to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes_periodo_escolar', to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='suspensao_alimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_periodo_escolar', to='cardapio.SuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='tipos_alimentacao',
            field=models.ManyToManyField(related_name='suspensoes_periodo_escolar', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='grupo_suspensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_alimentacao', to='cardapio.GrupoSuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.MotivoSuspensao'),
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='alteracao_cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_periodo_escolar', to='cardapio.AlteracaoCardapio'),
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_periodo_escolar', to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_tipo_alimentacao_de', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_tipo_alimentacao_para', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='grupo_suspensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantidades_por_periodo', to='cardapio.GrupoSuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='cardapio_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_de', to='cardapio.Cardapio'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='cardapio_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_para', to='cardapio.Cardapio'),
        ),
    ]
