# Generated by Django 2.2.6 on 2019-12-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceirizada', '0001_initial'),
        ('cardapio', '0002_auto_20191205_1815'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0002_auto_20191205_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversaocardapio',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='combodovinculotipoalimentacaoperiodotipoue',
            name='tipos_alimentacao',
            field=models.ManyToManyField(blank=True, help_text='Tipos de alimentacao do combo.', related_name='cardapio_combodovinculotipoalimentacaoperiodotipoue_possibilidades', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='combodovinculotipoalimentacaoperiodotipoue',
            name='vinculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='cardapio.VinculoTipoAlimentacaoComPeriodoEscolarETipoUnidadeEscolar'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='editais', to='terceirizada.Edital'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.MotivoAlteracaoCardapio'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AlterUniqueTogether(
            name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            unique_together={('periodo_escolar', 'tipo_unidade_escolar')},
        ),
    ]
