# Generated by Django 2.2.6 on 2019-12-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_auto_20191206_1113'),
        ('cardapio', '0004_substituicaodocombodovinculotipoalimentacaoperiodotipoue'),
    ]

    operations = [
    ]
