# Generated by Django 2.2.6 on 2019-12-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_merge_20191206_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracaocardapio',
            name='foi_solicitado_fora_do_prazo',
            field=models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?'),
        ),
    ]
