# Generated by Django 2.0.13 on 2019-10-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_auto_20190913_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='tipos_alimentacao',
        ),
        migrations.AddField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='tipo_alimentacao_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_tipo_alimentacao_de', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='tipo_alimentacao_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_tipo_alimentacao_para', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='tipoalimentacao',
            name='substituicoes',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
    ]
