# Generated by Django 2.0.13 on 2019-10-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_auto_20190913_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='qtd_alunos',
        ),
    ]
