# Generated by Django 2.0.13 on 2019-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_auto_20190913_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivoalteracaocardapio',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='motivosuspensao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipoalimentacao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
