# Generated by Django 2.0.13 on 2019-10-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_remove_substituicoesalimentacaonoperiodoescolar_qtd_alunos'),
        ('cardapio', '0008_auto_20191007_1603'),
    ]

    operations = [
    ]
