# Generated by Django 2.0.13 on 2019-10-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_merge_20191008_1242'),
        ('cardapio', '0008_auto_20191008_1819'),
    ]

    operations = [
    ]
