# Generated by Django 2.2.8 on 2020-02-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_horariodocombodotipodealimentacaoporunidadeescolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_tipo_alimentacao_de', to='cardapio.ComboDoVinculoTipoAlimentacaoPeriodoTipoUE'),
        ),
        migrations.AlterField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_tipo_alimentacao_para', to='cardapio.ComboDoVinculoTipoAlimentacaoPeriodoTipoUE'),
        ),
    ]
