# Generated by Django 2.2.6 on 2019-10-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_auto_20191008_1829'),
        ('terceirizada', '0006_auto_20191008_1819'),
        ('cardapio', '0010_merge_20191008_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapio_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_gruposuspensaoalimentacao_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_inversaocardapio_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
    ]
