# Generated by Django 2.2.6 on 2019-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cardapio", "0010_merge_20191008_1825")]

    operations = [
        migrations.AlterField(
            model_name="tipoalimentacao",
            name="substituicoes",
            field=models.ManyToManyField(blank=True, to="cardapio.TipoAlimentacao"),
        )
    ]
