# Generated by Django 2.2.6 on 2019-10-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0011_auto_20191023_1058'),
        ('cardapio', '0011_auto_20191021_1743'),
    ]

    operations = [
    ]
