# Generated by Django 2.2.8 on 2020-02-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_auto_20200210_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoalimentacao',
            name='substituicoes',
        ),
    ]
