# Generated by Django 2.2.6 on 2019-10-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_merge_20191023_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inversaocardapio',
            options={'verbose_name': 'Inversão de cardápio', 'verbose_name_plural': 'Inversão$ProjectFileDir$ de cardápios'},
        ),
    ]
