# Generated by Django 2.2.6 on 2019-11-08 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_remove_escola_endereco'),
        ('cardapio', '0013_auto_20191030_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoTipoAlimentacaoComPeriodoEscolarETipoUnidadeEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar')),
                ('tipo_unidade_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.TipoUnidadeEscolar')),
                ('tipos_alimentacao', models.ManyToManyField(blank=True, to='cardapio.TipoAlimentacao')),
            ],
            options={
                'verbose_name': 'Vínculo tipo alimentação',
                'verbose_name_plural': 'Vínculos tipo alimentação',
            },
        ),
    ]
