# Generated by Django 2.2.6 on 2019-11-29 18:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_remove_escola_endereco'),
        ('cardapio', '0014_vinculotipoalimentacaocomperiodoescolaretipounidadeescolar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            unique_together={('periodo_escolar', 'tipo_unidade_escolar')},
        ),
        migrations.CreateModel(
            name='SubstituicoesDoVinculoTipoAlimentacaoPeriodoTipoUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('possibilidades', models.ManyToManyField(blank=True, help_text='Possibilidades de substituicões para este tipo de alimentação.', related_name='cardapio_substituicoesdovinculotipoalimentacaoperiodotipoue_possibilidades', to='cardapio.TipoAlimentacao')),
                ('substituicoes', models.ManyToManyField(blank=True, help_text='Substituições para este tipo de alimentação.', related_name='cardapio_substituicoesdovinculotipoalimentacaoperiodotipoue_substituicoes', to='cardapio.TipoAlimentacao')),
                ('tipo_alimentacao', models.ForeignKey(help_text='Tipo de alimentação.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_substituicoesdovinculotipoalimentacaoperiodotipoue_tipo_alimentacao', to='cardapio.TipoAlimentacao')),
            ],
            options={
                'verbose_name': 'Substituição do vínculo tipo alimentação',
                'verbose_name_plural': 'Substituições do vínculo tipo alimentação',
            },
        ),
        migrations.RemoveField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='tipos_alimentacao',
        ),
        migrations.AddField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='substituicoes',
            field=models.ManyToManyField(blank=True, to='cardapio.SubstituicoesDoVinculoTipoAlimentacaoPeriodoTipoUE'),
        ),
    ]
