# Generated by Django 2.2.8 on 2020-03-26 15:56

import uuid

import django.db.models.deletion
import django_prometheus.models
import django_xworkflows.models
from django.conf import settings
from django.db import migrations, models

import sme_terceirizadas.dados_comuns.behaviors


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_auto_20200313_1521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terceirizada', '0003_auto_20191213_1339'),
        ('cardapio', '0014_alteracaocardapiocei_faixaetariasubstituicaoalimentacaocei_substituicaoalimentacaonoperiodoescolarce'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensaoAlimentacaoDaCEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=26, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='InformativoPartindoDaEscolaWorkflow', states=['RASCUNHO', 'INFORMADO', 'TERCEIRIZADA_TOMOU_CIENCIA']))),
                ('outro_motivo', models.CharField(blank=True, max_length=50, verbose_name='Outro motivo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.MotivoSuspensao')),
                ('periodos_escolares', models.ManyToManyField(blank=True, help_text='Periodos escolares da suspensão', related_name='cardapio_suspensaoalimentacaodacei_periodos', to='escola.PeriodoEscolar')),
                ('rastro_dre', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_dre', to='escola.DiretoriaRegional')),
                ('rastro_escola', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_escola', to='escola.Escola')),
                ('rastro_lote', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_lote', to='escola.Lote')),
                ('rastro_terceirizada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_terceirizada', to='terceirizada.Terceirizada')),
            ],
            options={
                'verbose_name': 'Suspensão de Alimentação de CEI',
                'verbose_name_plural': 'Suspensões de Alimentação de CEI',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('suspensao_alimentacao_de_cei'), sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, django_xworkflows.models.BaseWorkflowEnabled, models.Model, sme_terceirizadas.dados_comuns.behaviors.Logs, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade),
        ),
    ]
