# Generated by Django 2.2.8 on 2020-03-25 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0003_auto_20191213_1339'),
        ('escola', '0015_auto_20200313_1521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0014_alteracaocardapiocei_faixaetariasubstituicaoalimentacaocei_substituicaoalimentacaonoperiodoescolarce'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensaoAlimentacaoDaCEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=37, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_VALIDADO', 'DRE_PEDIU_ESCOLA_REVISAR', 'DRE_NAO_VALIDOU_PEDIDO_ESCOLA', 'CODAE_AUTORIZADO', 'CODAE_QUESTIONADO', 'CODAE_NEGOU_PEDIDO', 'TERCEIRIZADA_RESPONDEU_QUESTIONAMENTO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'CANCELADO_AUTOMATICAMENTE']))),
                ('outro_motivo', models.CharField(blank=True, max_length=50, verbose_name='Outro motivo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.MotivoSuspensao')),
                ('rastro_dre', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_dre', to='escola.DiretoriaRegional')),
                ('rastro_escola', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_escola', to='escola.Escola')),
                ('rastro_lote', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_lote', to='escola.Lote')),
                ('rastro_terceirizada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_suspensaoalimentacaodacei_rastro_terceirizada', to='terceirizada.Terceirizada')),
            ],
            options={
                'verbose_name': 'Suspensão de Alimentação de CEI',
                'verbose_name_plural': 'Suspensões de Alimentação de CEI',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('suspensao_alimentacao_de_cei'), sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, django_xworkflows.models.BaseWorkflowEnabled, models.Model, sme_terceirizadas.dados_comuns.behaviors.Logs, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade),
        ),
        migrations.CreateModel(
            name='SuspensaoAlimentacaoNoPeriodoEscolarDeCEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes_da_cei_periodo_escolar', to='escola.PeriodoEscolar')),
                ('suspensao_alimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_da_cei_periodo_escolar', to='cardapio.SuspensaoAlimentacaoDaCEI')),
            ],
            options={
                'verbose_name': 'Suspensão de alimentação no período da CEI',
                'verbose_name_plural': 'Suspensões de alimentação no período da CEI',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('suspensao_alimentacao_cei_periodo_escolar'), models.Model),
        ),
    ]
