# Generated by Django 2.2.6 on 2019-12-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0015_auto_20191129_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='periodo_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar'),
        ),
        migrations.AlterField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='tipo_unidade_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.TipoUnidadeEscolar'),
        ),
    ]
