# Generated by Django 2.2.13 on 2021-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0018_auto_20210407_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='qtd_alunos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
