# Generated by Django 2.2.13 on 2021-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0020_remove_substituicaoalimentacaonoperiodoescolar_qtd_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='qtd_alunos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
