# Generated by Django 2.2.13 on 2022-03-24 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0022_auto_20211110_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combodovinculotipoalimentacaoperiodotipoue',
            name='tipos_alimentacao',
        ),
        migrations.RemoveField(
            model_name='substituicaodocombodovinculotipoalimentacaoperiodotipoue',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='substituicaodocombodovinculotipoalimentacaoperiodotipoue',
            name='tipos_alimentacao',
        ),
        migrations.AddField(
            model_name='combodovinculotipoalimentacaoperiodotipoue',
            name='substituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='cardapio.SubstituicaoDoComboDoVinculoTipoAlimentacaoPeriodoTipoUE'),
        ),
        migrations.AddField(
            model_name='combodovinculotipoalimentacaoperiodotipoue',
            name='tipo_alimentacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='substituicaodocombodovinculotipoalimentacaoperiodotipoue',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
