# Generated by Django 2.2.13 on 2022-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0022_auto_20211110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculotipoalimentacaocomperiodoescolaretipounidadeescolar',
            name='tipos_alimentacao',
            field=models.ManyToManyField(blank=True, related_name='vinculos', to='cardapio.TipoAlimentacao'),
        ),
    ]
