# Generated by Django 2.2.13 on 2022-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0023_vinculotipoalimentacaocomperiodoescolaretipounidadeescolar_tipos_alimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
    ]
