# Generated by Django 2.2.13 on 2022-03-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0023_auto_20220324_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='periodo_escolar',
        ),
        migrations.RemoveField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_de',
        ),
        migrations.RemoveField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_para',
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='combos',
            field=models.ManyToManyField(to='cardapio.ComboDoVinculoTipoAlimentacaoPeriodoTipoUE'),
        ),
    ]
