# Generated by Django 2.2.13 on 2022-04-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0024_auto_20220408_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_de',
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipos_alimentacao_de',
            field=models.ManyToManyField(blank=True, help_text='Tipos de alimentação substituídos na solicitação', related_name='tipos_alimentacao_de', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AlterField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_para',
            field=models.ForeignKey(blank=True, help_text='Substituição selecionada na solicitação', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_alimentacao_para', to='cardapio.TipoAlimentacao'),
        ),
    ]
