# Generated by Django 2.2.13 on 2022-04-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0025_auto_20220414_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipo_alimentacao_para',
            field=models.ForeignKey(blank=True, help_text='Substituição selecionada na solicitação', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicao_alimento_para', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AlterField(
            model_name='substituicaoalimentacaonoperiodoescolar',
            name='tipos_alimentacao_de',
            field=models.ManyToManyField(blank=True, help_text='Tipos de alimentação substituídos na solicitação', related_name='substituicoes_alimentos_de', to='cardapio.TipoAlimentacao'),
        ),
    ]
