# Generated by Django 2.2.13 on 2022-05-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0026_auto_20220414_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituicaoalimentacaonoperiodoescolarcei',
            name='tipo_alimentacao_de',
        ),
        migrations.AddField(
            model_name='substituicaoalimentacaonoperiodoescolarcei',
            name='tipos_alimentacao_de',
            field=models.ManyToManyField(blank=True, related_name='substituicoes_cei_tipo_alimentacao_de', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AlterField(
            model_name='substituicaoalimentacaonoperiodoescolarcei',
            name='tipo_alimentacao_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_cei_tipo_alimentacao_para', to='cardapio.TipoAlimentacao'),
        ),
    ]
