# Generated by Django 2.2.13 on 2022-05-09 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0027_auto_20220504_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDRENaoValida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de não validação da DRE',
                'verbose_name_plural': 'Motivos de não validação da DRE',
            },
        ),
    ]
