# Generated by Django 2.2.13 on 2022-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0029_auto_20220512_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversaocardapio',
            name='data_de_inversao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inversão'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='data_para_inversao',
            field=models.DateField(blank=True, null=True, verbose_name='Data para inversão'),
        ),
    ]
