# Generated by Django 2.2.13 on 2022-09-20 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terceirizada', '0007_auto_20211008_1027'),
        ('escola', '0053_periodoescolar_tipo_turno'),
        ('cardapio', '0036_quantidadeporperiodosuspensaoalimentacao_alunos_cei_ou_emei'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoCardapioCEMEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('foi_solicitado_fora_do_prazo', models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?')),
                ('terceirizada_conferiu_gestao', models.BooleanField(default=False, verbose_name='Terceirizada conferiu?')),
                ('status', django_xworkflows.models.StateField(max_length=37, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_VALIDADO', 'DRE_PEDIU_ESCOLA_REVISAR', 'DRE_NAO_VALIDOU_PEDIDO_ESCOLA', 'CODAE_AUTORIZADO', 'CODAE_QUESTIONADO', 'CODAE_NEGOU_PEDIDO', 'TERCEIRIZADA_RESPONDEU_QUESTIONAMENTO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'CANCELADO_AUTOMATICAMENTE']))),
                ('alunos_cei_e_ou_emei', models.CharField(choices=[('TODOS', 'Todos'), ('CEI', 'CEI'), ('EMEI', 'EMEI')], default='TODOS', max_length=10)),
                ('alterar_dia', models.DateField(blank=True, null=True, verbose_name='Alterar dia')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.MotivoAlteracaoCardapio')),
                ('rastro_dre', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapiocemei_rastro_dre', to='escola.DiretoriaRegional')),
                ('rastro_escola', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapiocemei_rastro_escola', to='escola.Escola')),
                ('rastro_lote', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapiocemei_rastro_lote', to='escola.Lote')),
                ('rastro_terceirizada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_alteracaocardapiocemei_rastro_terceirizada', to='terceirizada.Terceirizada')),
            ],
            options={
                'verbose_name': 'Alteração de cardápio CEMEI',
                'verbose_name_plural': 'Alterações de cardápio CEMEI',
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, sme_terceirizadas.dados_comuns.behaviors.Logs, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade, models.Model),
        ),
        migrations.CreateModel(
            name='SubstituicaoAlimentacaoNoPeriodoEscolarCEMEIEMEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qtd_alunos', models.PositiveSmallIntegerField(default=0)),
                ('alteracao_cardapio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_cemei_emei_periodo_escolar', to='cardapio.AlteracaoCardapioCEMEI')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_cemei_emei_periodo_escolar', to='escola.PeriodoEscolar')),
                ('tipos_alimentacao_de', models.ManyToManyField(blank=True, related_name='substituicoes_cemei_emei_tipo_alimentacao_de', to='cardapio.TipoAlimentacao')),
                ('tipos_alimentacao_para', models.ManyToManyField(blank=True, help_text='Substituições selecionada na solicitação', related_name='substituicoes_cemei_emei_alimento_para', to='cardapio.TipoAlimentacao')),
            ],
            options={
                'verbose_name': 'Substituições de alimentação CEMEI EMEI no período',
                'verbose_name_plural': 'Substituições de alimentação CEMEI EMEI no período',
            },
        ),
        migrations.CreateModel(
            name='SubstituicaoAlimentacaoNoPeriodoEscolarCEMEICEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alteracao_cardapio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_cemei_cei_periodo_escolar', to='cardapio.AlteracaoCardapioCEMEI')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_cemei_cei_periodo_escolar', to='escola.PeriodoEscolar')),
                ('tipos_alimentacao_de', models.ManyToManyField(blank=True, related_name='substituicoes_cemei_cei_tipo_alimentacao_de', to='cardapio.TipoAlimentacao')),
                ('tipos_alimentacao_para', models.ManyToManyField(blank=True, help_text='Substituições selecionada na solicitação', related_name='substituicoes_cemei_cei_alimento_para', to='cardapio.TipoAlimentacao')),
            ],
            options={
                'verbose_name': 'Substituições de alimentação CEMEI CEI no período',
                'verbose_name_plural': 'Substituições de alimentação CEMEI CEI no período',
            },
        ),
        migrations.CreateModel(
            name='FaixaEtariaSubstituicaoAlimentacaoCEMEICEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.FaixaEtaria')),
                ('substituicao_alimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_etarias', to='cardapio.SubstituicaoAlimentacaoNoPeriodoEscolarCEMEICEI')),
            ],
            options={
                'verbose_name': 'Faixa Etária de substituição de alimentação CEMEI CEI',
                'verbose_name_plural': 'Faixas Etárias de substituição de alimentação CEMEI CEI',
            },
        ),
    ]
