# Generated by Django 2.2.13 on 2022-10-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0037_alteracaocardapiocemei_faixaetariasubstituicaoalimentacaocemeicei_substituicaoalimentacaonoperiodoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoalteracaocardapio',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
    ]
