# Generated by Django 2.2.13 on 2022-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0038_motivoalteracaocardapio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensaoalimentacaodacei',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
