# Generated by Django 3.2.18 on 2023-06-22 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0043_auto_20230116_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIntervaloAlteracaoCardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cancelado', models.BooleanField(default=False, verbose_name='Esta cancelado?')),
                ('cancelado_justificativa', models.CharField(blank=True, max_length=500, verbose_name='Porque foi cancelado individualmente')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('alteracao_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_intervalo', to='cardapio.alteracaocardapio')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data do intervalo de Alteração de cardápio',
                'verbose_name_plural': 'Datas do intervalo de Alteração de cardápio',
                'ordering': ('data',),
            },
            bases=(models.Model, sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel),
        ),
    ]
