# Generated by Django 4.1.12 on 2023-10-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0015_auto_20230925_1221'),
        ('escola', '0062_diasuspensaoatividades'),
        ('cardapio', '0044_dataintervaloalteracaocardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaocardapio',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapio',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapio',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapio',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocei',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocei',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocei',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocei',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocemei',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocemei',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocemei',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='alteracaocardapiocemei',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='combodovinculotipoalimentacaoperiodotipoue',
            name='tipos_alimentacao',
            field=models.ManyToManyField(blank=True, help_text='Tipos de alimentacao do combo.', related_name='%(app_label)s_%(class)s_possibilidades', to='cardapio.tipoalimentacao'),
        ),
        migrations.AlterField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='gruposuspensaoalimentacao',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='inversaocardapio',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='inversaocardapio',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='inversaocardapio',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='inversaocardapio',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='substituicaodocombodovinculotipoalimentacaoperiodotipoue',
            name='tipos_alimentacao',
            field=models.ManyToManyField(blank=True, help_text='Tipos de alimentacao das substituições dos combos.', related_name='%(app_label)s_%(class)s_possibilidades', to='cardapio.tipoalimentacao'),
        ),
        migrations.AlterField(
            model_name='suspensaoalimentacaodacei',
            name='periodos_escolares',
            field=models.ManyToManyField(blank=True, help_text='Periodos escolares da suspensão', related_name='%(app_label)s_%(class)s_periodos', to='escola.periodoescolar'),
        ),
        migrations.AlterField(
            model_name='suspensaoalimentacaodacei',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='suspensaoalimentacaodacei',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='suspensaoalimentacaodacei',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='suspensaoalimentacaodacei',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
    ]
