# Generated by Django 3.2.18 on 2023-06-16 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0044_dataalteracaocardapio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAlteracaoCardapio',
            new_name='DataIntervaloAlteracaoCardapio',
        ),
    ]
