# Generated by Django 3.2.18 on 2023-09-12 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0045_controlesobras'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlesobras',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlesobras',
            name='peso_alimento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='controlesobras',
            name='peso_recipiente',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='controlesobras',
            name='peso_sobra',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
