# Generated by Django 3.2.18 on 2023-09-13 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0046_auto_20230912_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlesobras',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
