# Generated by Django 3.2.18 on 2023-09-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0060_auto_20230815_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0047_controlesobras_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleRestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('peso_resto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cardapio', models.CharField(blank=True, max_length=250, verbose_name='cardapio')),
                ('resto_predominante', models.CharField(blank=True, max_length=250, verbose_name='resto_predominante')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.escola')),
                ('tipo_alimentacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.tipoalimentacao')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle de Restos',
            },
        ),
        migrations.CreateModel(
            name='ImagemControleResto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(upload_to='')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('controle_resto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cardapio.controlerestos')),
            ],
            options={
                'verbose_name': 'Imagem do Controle de Resto',
                'verbose_name_plural': 'Imagens do Controle de Resto',
            },
        ),
    ]
