# Generated by Django 3.2.18 on 2023-09-19 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0049_remove_imagemcontroleresto_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemcontroleresto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
