# Generated by Django 3.2.18 on 2023-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0050_imagemcontroleresto_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlerestos',
            name='data_medicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Medição'),
        ),
        migrations.AddField(
            model_name='controlesobras',
            name='data_medicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Medição'),
        ),
    ]
