# Generated by Django 3.2.18 on 2023-10-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0051_auto_20231010_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlerestos',
            name='data_medicao',
        ),
        migrations.RemoveField(
            model_name='controlesobras',
            name='data_medicao',
        ),
        migrations.AddField(
            model_name='controlerestos',
            name='data_hora_medicao',
            field=models.DateTimeField(default=None, null=True, verbose_name='Data e hora da medição'),
        ),
        migrations.AddField(
            model_name='controlesobras',
            name='data_hora_medicao',
            field=models.DateTimeField(default=None, null=True, verbose_name='Data e hora da medição'),
        ),
    ]
