# Generated by Django 3.2.18 on 2023-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0052_auto_20231010_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlerestos',
            name='quantidade_distribuida',
            field=models.DecimalField(decimal_places=2, max_digits=5),
            preserve_default=False,
        ),
    ]
