# Generated by Django 4.2.7 on 2024-04-10 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0046_dataintervaloalteracaocardapiocemei"),
        ("cardapio", "0053_controlerestos_quantidade_distribuida"),
    ]

    operations = []
