# Generated by Django 4.2.7 on 2024-06-17 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0055_remove_controlesobras_data_hora_medicao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlesobras",
            name="escola",
        ),
        migrations.RemoveField(
            model_name="controlesobras",
            name="tipo_alimentacao",
        ),
        migrations.RemoveField(
            model_name="controlesobras",
            name="tipo_alimento",
        ),
        migrations.RemoveField(
            model_name="controlesobras",
            name="tipo_recipiente",
        ),
        migrations.RemoveField(
            model_name="controlesobras",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="imagemcontroleresto",
            name="controle_resto",
        ),
        migrations.DeleteModel(
            name="ControleRestos",
        ),
        migrations.DeleteModel(
            name="ControleSobras",
        ),
        migrations.DeleteModel(
            name="ImagemControleResto",
        ),
    ]
