# Generated by Django 4.2.7 on 2023-12-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0081_alter_homologacaoproduto_rastro_terceirizada"),
    ]

    operations = [
        migrations.AddField(
            model_name="informacaonutricional",
            name="eh_fixo",
            field=models.BooleanField(
                default=False, verbose_name="Informação Nutricional Fixa"
            ),
        ),
    ]
