# Generated by Django 4.2.7 on 2024-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0082_informacaonutricional_eh_fixo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoedital",
            name="suspenso_justificativa",
            field=models.CharField(
                blank=True,
                max_length=1500,
                verbose_name="Porque foi suspenso individualmente",
            ),
        ),
    ]
