# Generated by Django 2.0.13 on 2019-08-05 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados_comuns', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('data_inicial', models.DateField(verbose_name='Data inicial')),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Terceirizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=160, null=True, verbose_name='Razao social')),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('representante_legal', models.CharField(blank=True, max_length=160, null=True, verbose_name='Representante legal')),
                ('representante_contato', models.CharField(blank=True, max_length=160, null=True, verbose_name='Representante contato (email/tel)')),
                ('nutricionista_responsavel', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nutricionista responsavel')),
                ('nutricionista_crn', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nutricionista crn')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_comuns.Contato')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_comuns.Endereco')),
                ('lotes', models.ManyToManyField(related_name='lotes', to='escola.Lote')),
            ],
            options={
                'verbose_name': 'Terceirizada',
                'verbose_name_plural': 'Terceirizadas',
            },
        ),
    ]
