# Generated by Django 2.0.13 on 2019-08-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceirizada',
            name='lotes',
        ),
    ]
