# Generated by Django 2.0.13 on 2019-07-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_contato_endereco'),
        ('terceirizada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceirizada',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_comuns.Contato'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_comuns.Endereco'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='nutricionista_crn',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Nutricionista crn'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='nutricionista_responsavel',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Nutricionista responsavel'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='razao_social',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Razao social'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='representante_contato',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Representante contato (email/tel)'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Representante legal'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='lotes',
            field=models.ManyToManyField(related_name='lotes', to='terceirizada.Lote'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Nome fantasia'),
        ),
    ]
