# Generated by Django 2.0.13 on 2019-08-05 20:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0001_initial'),
        ('terceirizada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('crn_numero', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nutricionista crn')),
            ],
            options={
                'verbose_name': 'Nutricionista',
                'verbose_name_plural': 'Nutricionistas',
            },
        ),
        migrations.RemoveField(
            model_name='terceirizada',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='terceirizada',
            name='nutricionista_crn',
        ),
        migrations.RemoveField(
            model_name='terceirizada',
            name='nutricionista_responsavel',
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='contatos',
            field=models.ManyToManyField(blank=True, to='dados_comuns.Contato'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='terceirizada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricionistas', to='terceirizada.Terceirizada'),
        ),
    ]
