# Generated by Django 2.0.13 on 2019-07-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_auto_20190723_1614'),
        ('terceirizada', '0002_auto_20190712_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='diretoria_regional',
        ),
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='lotes',
            field=models.ManyToManyField(related_name='lotes', to='escola.Lote'),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
