# Generated by Django 2.0.13 on 2019-08-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0002_remove_terceirizada_lotes'),
        ('terceirizada', '0003_auto_20190807_1125'),
    ]

    operations = [
    ]
