# Generated by Django 2.0.13 on 2019-08-09 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_auto_20190808_1313'),
        ('terceirizada', '0005_auto_20190809_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=100, verbose_name='No do contrato')),
                ('processo', models.CharField(help_text='Processo administrativo do contrato', max_length=100, verbose_name='Processo Administrativo')),
                ('data_proposta', models.DateField(verbose_name='Data da proposta')),
                ('lotes', models.ManyToManyField(related_name='contratos_do_lote', to='escola.Lote')),
                ('terceirizadas', models.ManyToManyField(related_name='contratos_da_terceirizada', to='terceirizada.Terceirizada')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='VigenciaContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(verbose_name='Data inicial')),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencias', to='terceirizada.Contrato')),
            ],
            options={
                'verbose_name': 'Vigência de contrato',
                'verbose_name_plural': 'Vigências de contrato',
            },
        ),
    ]
