# Generated by Django 2.0.13 on 2019-08-09 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0006_contrato_vigenciacontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='edital',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='terceirizada.Edital'),
            preserve_default=False,
        ),
    ]
