# Generated by Django 2.0.13 on 2019-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0007_contrato_edital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='processo',
            field=models.CharField(help_text='Processo administrativo do edital', max_length=100, verbose_name='Processo Administrativo'),
        ),
    ]
