# Generated by Django 2.0.13 on 2019-08-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0008_auto_20190809_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='terceirizada.Edital'),
        ),
    ]
