# Generated by Django 2.0.13 on 2019-08-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0009_auto_20190809_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigenciacontrato',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vigencias', to='terceirizada.Contrato'),
        ),
    ]
