# Generated by Django 2.0.13 on 2019-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0010_auto_20190812_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='numero',
            field=models.CharField(help_text='Número do Edital', max_length=100, unique=True, verbose_name='Edital No'),
        ),
    ]
