# Generated by Django 2.0.13 on 2019-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0012_auto_20190812_0908'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together=set(),
        ),
    ]
