# Generated by Django 2.0.13 on 2019-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_auto_20190812_1200'),
        ('terceirizada', '0013_auto_20190812_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dres',
            field=models.ManyToManyField(related_name='contratos_da_dre', to='escola.DiretoriaRegional'),
        ),
    ]
