# Generated by Django 2.0.13 on 2019-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_auto_20190812_1200'),
        ('terceirizada', '0014_contrato_dres'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='contrato',
        #     name='dres',
        # ),
        # migrations.AddField(
        #     model_name='contrato',
        #     name='diretorias_regionais',
        #     field=models.ManyToManyField(related_name='contratos_da_diretoria_regional', to='escola.DiretoriaRegional'),
        # ),
    ]
