# Generated by Django 2.0.13 on 2019-08-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0015_auto_20190815_1225'),
        ('terceirizada', '0015_auto_20190815_0757'),
    ]

    operations = [
    ]
