# Generated by Django 2.0.13 on 2019-08-20 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terceirizada', '0016_merge_20190816_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceirizada',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='terceirizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
