# Generated by Django 2.2.6 on 2019-11-26 14:34

from django.db import migrations, models

import sme_terceirizadas.dados_comuns.behaviors


class Migration(migrations.Migration):

    dependencies = [
        ('paineis_consolidados', '0002_view_com_rastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrosConsolidados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('data_evento', models.DateField()),
                ('lote_nome', models.CharField(max_length=50)),
                ('dre_nome', models.CharField(max_length=200)),
                ('escola_nome', models.CharField(max_length=200)),
                ('terceirizada_nome', models.CharField(max_length=200)),
                ('lote_uuid', models.UUIDField(editable=False)),
                ('escola_uuid', models.UUIDField(editable=False)),
                ('dre_uuid', models.UUIDField(editable=False)),
                ('terceirizada_uuid', models.UUIDField(editable=False)),
                ('tipo_doc', models.CharField(max_length=30)),
                ('desc_doc', models.CharField(max_length=50)),
                ('data_log', models.DateTimeField()),
                ('status_evento', models.PositiveSmallIntegerField()),
                ('status_atual', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'solicitacoes_consolidadas',
                'abstract': False,
                'managed': False,
            },
            bases=(models.Model, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade),
        ),
    ]
