# Generated by Django 2.2.8 on 2020-01-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis_consolidados', '0004_quantidade_alunos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiltrosConsolidados',
        ),
    ]
