# Generated by Django 2.0.13 on 2019-09-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis_consolidados', '0003_ajuste_de_view'),
        ('paineis_consolidados', '0004_ajuste_de_view_2'),
    ]

    operations = [
    ]
