# Generated by Django 2.0.13 on 2019-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis_consolidados', '0006_solicitacoes_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('escola_uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
                ('desc_doc', models.CharField(max_length=50)),
                ('status_evento', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'solicitacoes_consolidadas',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('escola_uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
                ('desc_doc', models.CharField(max_length=50)),
                ('status_evento', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'solicitacoes_consolidadas',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='solicitacoescodae',
            table='solicitacoes_consolidadas',
        ),
    ]
