# Generated by Django 2.2.13 on 2022-03-09 16:32

from django.db import migrations, models
import sme_terceirizadas.dados_comuns.behaviors


class Migration(migrations.Migration):

    dependencies = [
        ('paineis_consolidados', '0016_solicitacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesNutrimanifestacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('data_evento', models.DateField()),
                ('criado_em', models.DateTimeField()),
                ('lote_nome', models.CharField(max_length=50)),
                ('dre_nome', models.CharField(max_length=200)),
                ('escola_nome', models.CharField(max_length=200)),
                ('tipo_solicitacao_dieta', models.CharField(max_length=30)),
                ('terceirizada_nome', models.CharField(max_length=200)),
                ('nome_aluno', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=10)),
                ('codigo_eol_aluno', models.CharField(max_length=7)),
                ('aluno_nao_matriculado', models.BooleanField(default=False, null=True)),
                ('dieta_alterada_id', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('em_vigencia', models.BooleanField()),
                ('lote_uuid', models.UUIDField(editable=False)),
                ('escola_uuid', models.UUIDField(editable=False)),
                ('escola_destino_id', models.IntegerField()),
                ('dre_uuid', models.UUIDField(editable=False)),
                ('terceirizada_uuid', models.UUIDField(editable=False)),
                ('tipo_doc', models.CharField(max_length=30)),
                ('desc_doc', models.CharField(max_length=50)),
                ('data_log', models.DateTimeField()),
                ('status_evento', models.PositiveSmallIntegerField()),
                ('numero_alunos', models.PositiveSmallIntegerField()),
                ('status_atual', models.CharField(max_length=32)),
                ('conferido', models.BooleanField()),
                ('terceirizada_conferiu_gestao', models.BooleanField()),
            ],
            options={
                'db_table': 'solicitacoes_consolidadas',
                'abstract': False,
                'managed': False,
            },
            bases=(models.Model, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade, sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel),
        ),
        migrations.CreateModel(
            name='SolicitacoesNutrisupervisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('data_evento', models.DateField()),
                ('criado_em', models.DateTimeField()),
                ('lote_nome', models.CharField(max_length=50)),
                ('dre_nome', models.CharField(max_length=200)),
                ('escola_nome', models.CharField(max_length=200)),
                ('tipo_solicitacao_dieta', models.CharField(max_length=30)),
                ('terceirizada_nome', models.CharField(max_length=200)),
                ('nome_aluno', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=10)),
                ('codigo_eol_aluno', models.CharField(max_length=7)),
                ('aluno_nao_matriculado', models.BooleanField(default=False, null=True)),
                ('dieta_alterada_id', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('em_vigencia', models.BooleanField()),
                ('lote_uuid', models.UUIDField(editable=False)),
                ('escola_uuid', models.UUIDField(editable=False)),
                ('escola_destino_id', models.IntegerField()),
                ('dre_uuid', models.UUIDField(editable=False)),
                ('terceirizada_uuid', models.UUIDField(editable=False)),
                ('tipo_doc', models.CharField(max_length=30)),
                ('desc_doc', models.CharField(max_length=50)),
                ('data_log', models.DateTimeField()),
                ('status_evento', models.PositiveSmallIntegerField()),
                ('numero_alunos', models.PositiveSmallIntegerField()),
                ('status_atual', models.CharField(max_length=32)),
                ('conferido', models.BooleanField()),
                ('terceirizada_conferiu_gestao', models.BooleanField()),
            ],
            options={
                'db_table': 'solicitacoes_consolidadas',
                'abstract': False,
                'managed': False,
            },
            bases=(models.Model, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade, sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel),
        ),
    ]
