# Generated by Django 2.2.8 on 2020-04-16 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformacaoNutricional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeInformacaoNutricional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocoloDeDietaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('eh_para_alunos_com_dieta', models.BooleanField(default=False)),
                ('detalhes_da_dieta', models.TextField()),
                ('componentes', models.CharField(blank=True, max_length=100, verbose_name='Componentes do Produto')),
                ('tem_aditivos_alergenicos', models.BooleanField(default=False)),
                ('aditivos', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo do Produto')),
                ('embalagem', models.CharField(blank=True, max_length=100, verbose_name='Embalagem Primária')),
                ('prazo_validade', models.CharField(blank=True, max_length=100, verbose_name='Prazo de validade')),
                ('info_armazenamento', models.CharField(blank=True, max_length=100, verbose_name='Informações de Armazenamento')),
                ('outras_informacoes', models.TextField()),
                ('numero_registro', models.CharField(blank=True, max_length=100, verbose_name='Registro do órgão competente')),
                ('porcao', models.CharField(blank=True, max_length=50, verbose_name='Porção nutricional')),
                ('unidade_caseira', models.CharField(blank=True, max_length=50, verbose_name='Unidade nutricional')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.Fabricante')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.Marca')),
                ('protocolos', models.ManyToManyField(blank=True, help_text='Protocolos do produto.', related_name='protocolos', to='produto.ProtocoloDeDietaEspecial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformacoesNutricionaisDoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_porcao', models.CharField(blank=True, max_length=10, verbose_name='Quantidade por Porção')),
                ('valor_diario', models.CharField(blank=True, max_length=3, verbose_name='%VD(*)')),
                ('informacoes_nutricionais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.InformacaoNutricional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.Produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='informacaonutricional',
            name='tipo_nutricional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.TipoDeInformacaoNutricional'),
        ),
        migrations.CreateModel(
            name='ImagemDoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.Produto')),
            ],
        ),
    ]
