# Generated by Django 2.2.8 on 2020-04-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacoesnutricionaisdoproduto',
            old_name='informacoes_nutricionais',
            new_name='informacao_nutricional',
        ),
    ]
