# Generated by Django 2.2.8 on 2020-04-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_imagemdoproduto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemdoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produto.Produto'),
        ),
    ]
