# Generated by Django 2.2.8 on 2020-04-20 17:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20200420_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemdoproduto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
