# Generated by Django 2.2.8 on 2020-04-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_imagemdoproduto_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemdoproduto',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
