# Generated by Django 2.2.10 on 2020-04-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20200422_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemdoproduto',
            options={'verbose_name': 'Imagem do Produto', 'verbose_name_plural': 'Imagens do Produto'},
        ),
        migrations.AlterModelOptions(
            name='informacaonutricional',
            options={'verbose_name': 'Informação Nutricional', 'verbose_name_plural': 'Informações Nutricionais'},
        ),
        migrations.AlterModelOptions(
            name='informacoesnutricionaisdoproduto',
            options={'verbose_name': 'Informação Nutricional do Produto', 'verbose_name_plural': 'Informações Nutricionais do Produto'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='protocolodedietaespecial',
            options={'verbose_name': 'Protocolo de Dieta Especial', 'verbose_name_plural': 'Protocolos de Dieta Especial'},
        ),
    ]
