# Generated by Django 2.2.10 on 2020-04-24 19:27

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_homologacaodoproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homologacaodoproduto',
            name='rastro_lote',
        ),
        migrations.AlterField(
            model_name='homologacaodoproduto',
            name='status',
            field=django_xworkflows.models.StateField(max_length=29, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='HomologacaoProdutoWorkflow', states=['RASCUNHO', 'CODAE_PENDENTE_HOMOLOGACAO', 'CODAE_HOMOLOGADO', 'CODAE_NAO_HOMOLOGADO', 'CODAE_QUESTIONADO', 'CODAE_PEDIU_ANALISE_SENSORIAL', 'TERCEIRIZADA_CANCELOU'])),
        ),
    ]
