# Generated by Django 2.2.10 on 2020-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0021_auto_20200427_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='aditivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='outras_informacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
