# Generated by Django 2.2.10 on 2020-04-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_auto_20200427_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='detalhes_da_dieta',
        ),
    ]
