# Generated by Django 2.2.10 on 2020-05-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0026_auto_20200429_1713'),
        ('produto', '0020_auto_20200429_1007'),
    ]

    operations = [
    ]
