# Generated by Django 2.2.10 on 2020-06-02 16:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0008_auto_20191217_1146'),
        ('produto', '0027_merge_20200504_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamacaoDeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reclamante_registro_funcional', models.CharField(max_length=50, verbose_name='RF/CRN/CRF')),
                ('reclamante_cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('reclamante_nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('reclamacao', models.TextField(verbose_name='Reclamação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('homologacao_de_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.HomologacaoDoProduto')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.Vinculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnexoReclamacaoDeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('arquivo', models.FileField(upload_to='')),
                ('reclamacao_de_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anexos', to='produto.ReclamacaoDeProduto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
