# Generated by Django 2.2.10 on 2020-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0027_merge_20200504_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='porcao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Porção nutricional'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_caseira',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade nutricional'),
        ),
    ]
