# Generated by Django 2.2.10 on 2020-06-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0028_anexoreclamacaodeproduto_reclamacaodeproduto'),
        ('produto', '0029_auto_20200526_1641'),
    ]

    operations = [
    ]
