# Generated by Django 2.2.10 on 2020-06-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0030_merge_20200610_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologacaodoproduto',
            name='protocolo_analise_sensorial',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
