# Generated by Django 2.2.10 on 2020-06-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0030_merge_20200610_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacaodeproduto',
            name='homologacao_de_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reclamacoes', to='produto.HomologacaoDoProduto'),
        ),
    ]
