# Generated by Django 2.2.10 on 2020-06-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0031_homologacaodoproduto_protocolo_analise_sensorial'),
        ('produto', '0031_anexorespostaanalisesensorial_respostaanalisesensorial'),
    ]

    operations = [
    ]
