# Generated by Django 2.2.10 on 2020-06-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0031_auto_20200618_1447'),
        ('produto', '0032_merge_20200618_1349'),
    ]

    operations = [
    ]
