# Generated by Django 2.2.10 on 2020-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0032_merge_20200618_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologacaodoproduto',
            name='pdf_gerado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homologacaodoproduto',
            name='protocolo_analise_sensorial',
            field=models.CharField(blank=True, default='', max_length=8),
            preserve_default=False,
        ),
    ]
