# Generated by Django 2.2.10 on 2020-06-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0034_auto_20200619_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacaodeproduto',
            name='homologacao_de_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to='produto.HomologacaoDoProduto'),
        ),
    ]
