# Generated by Django 2.2.10 on 2020-06-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0035_auto_20200624_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoreclamacaodeproduto',
            name='reclamacao_de_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='produto.ReclamacaoDeProduto'),
        ),
    ]
