# Generated by Django 2.2.13 on 2020-08-24 12:34

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0041_reclamacaodeproduto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolodedietaespecial',
            name='nome',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='reclamacaodeproduto',
            name='status',
            field=django_xworkflows.models.StateField(max_length=32, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='AGUARDANDO_AVALIACAO', name='ReclamacaoProdutoWorkflow', states=['AGUARDANDO_AVALIACAO', 'AGUARDANDO_RESPOSTA_TERCEIRIZADA', 'RESPONDIDO_TERCEIRIZADA', 'CODAE_ACEITOU', 'CODAE_RECUSOU', 'CODAE_RESPONDEU'])),
        ),
    ]
