# Generated by Django 2.2.13 on 2020-08-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0013_auto_20200825_1335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0020_auto_20200825_1335'),
        ('produto', '0042_auto_20200824_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastroProdutoDieta',
            fields=[
                ('fluxosolicitacaocadastroproduto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dados_comuns.FluxoSolicitacaoCadastroProduto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_produto', models.CharField(max_length=150)),
                ('marca_produto', models.CharField(max_length=150)),
                ('fabricante_produto', models.CharField(max_length=150)),
                ('info_produto', models.TextField()),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('solicitacao_dieta_especial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_dieta_especial', to='dieta_especial.SolicitacaoDietaEspecial')),
            ],
            options={
                'abstract': False,
            },
            bases=('dados_comuns.fluxosolicitacaocadastroproduto', sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, models.Model),
        ),
    ]
