# Generated by Django 2.2.13 on 2020-09-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0043_auto_20200827_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('nome', 'marca', 'fabricante')},
        ),
    ]
