# Generated by Django 2.2.13 on 2020-08-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_auto_20200313_1521'),
        ('terceirizada', '0003_auto_20191213_1339'),
        ('produto', '0044_auto_20200825_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastroprodutodieta',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cadastro_produto', to='escola.Aluno'),
        ),
        migrations.AddField(
            model_name='solicitacaocadastroprodutodieta',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cadastro_produto', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='solicitacaocadastroprodutodieta',
            name='terceirizada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cadastro_produto', to='terceirizada.Terceirizada'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastroprodutodieta',
            name='solicitacao_dieta_especial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cadastro_produto', to='dieta_especial.SolicitacaoDietaEspecial'),
        ),
    ]
