# Generated by Django 2.2.13 on 2021-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0046_lognomedeprodutoedital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(blank=True, max_length=500, verbose_name='Embalagem Primária'),
        ),
    ]
