# Generated by Django 2.2.13 on 2021-07-20 21:54

from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0005_auto_20201127_1541'),
        ('produto', '0051_auto_20210608_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacaodeproduto',
            name='status',
            field=django_xworkflows.models.StateField(max_length=32, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='AGUARDANDO_AVALIACAO', name='ReclamacaoProdutoWorkflow', states=['AGUARDANDO_AVALIACAO', 'AGUARDANDO_RESPOSTA_TERCEIRIZADA', 'AGUARDANDO_ANALISE_SENSORIAL', 'ANALISE_SENSORIAL_RESPONDIDA', 'RESPONDIDO_TERCEIRIZADA', 'CODAE_ACEITOU', 'CODAE_RECUSOU', 'CODAE_RESPONDEU'])),
        ),
        migrations.CreateModel(
            name='AnaliseSensorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_RESPOSTA', 'Aguardando resposta'), ('RESPONDIDA', 'Respondida')], default='AGUARDANDO_RESPOSTA', max_length=25, verbose_name='Status da análise')),
                ('homologacao_de_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_sensoriais', to='produto.HomologacaoDoProduto')),
                ('terceirizada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_sensoriais', to='terceirizada.Terceirizada')),
            ],
            options={
                'abstract': False,
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, models.Model),
        ),
    ]
