# Generated by Django 2.2.13 on 2021-08-02 12:16

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0052_auto_20210720_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacaodeproduto',
            name='status',
            field=django_xworkflows.models.StateField(max_length=32, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='AGUARDANDO_AVALIACAO', name='ReclamacaoProdutoWorkflow', states=['AGUARDANDO_AVALIACAO', 'AGUARDANDO_RESPOSTA_TERCEIRIZADA', 'AGUARDANDO_RESPOSTA_UE', 'AGUARDANDO_ANALISE_SENSORIAL', 'ANALISE_SENSORIAL_RESPONDIDA', 'RESPONDIDO_TERCEIRIZADA', 'RESPONDIDO_UE', 'CODAE_ACEITOU', 'CODAE_RECUSOU', 'CODAE_RESPONDEU'])),
        ),
    ]
