# Generated by Django 2.2.13 on 2021-08-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0053_auto_20210802_1216'),
        ('produto', '0053_auto_20210729_1700'),
    ]

    operations = [
    ]
