# Generated by Django 2.2.13 on 2021-09-27 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0060_produto_tem_gluten'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('volume', models.FloatField(null=True, verbose_name='Volume')),
                ('embalagem_produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.EmbalagemProduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificacoes', to='produto.Produto')),
                ('unidade_de_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.UnidadeMedida')),
            ],
            options={
                'verbose_name': 'Especificicação do Produto',
                'verbose_name_plural': 'Especificações do Produto',
            },
        ),
    ]
