# Generated by Django 2.2.13 on 2022-07-29 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0007_auto_20211008_1027'),
        ('produto', '0065_produto_editais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='editais',
        ),
        migrations.CreateModel(
            name='ProdutoEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_produto', models.CharField(blank=True, choices=[('COMUM', 'Comum'), ('DIETA_ESPECIAL', 'Dieta especial')], max_length=1, null=True, verbose_name='tipo de produto')),
                ('outras_informacoes', models.TextField(blank=True, verbose_name='Outras Informações')),
                ('edital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terceirizada.Edital')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.Produto')),
            ],
            options={
                'verbose_name': 'Vinculo entre produto e edital',
                'verbose_name_plural': 'Vinculos entre produtos e editais',
            },
        ),
    ]
