# Generated by Django 2.2.13 on 2022-07-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0066_auto_20220729_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoedital',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
