# Generated by Django 2.2.13 on 2022-08-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0069_auto_20220801_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoedital',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vinculos', to='terceirizada.Edital'),
        ),
        migrations.AlterField(
            model_name='produtoedital',
            name='outras_informacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Informações'),
        ),
        migrations.AlterField(
            model_name='produtoedital',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vinculos', to='produto.Produto'),
        ),
        migrations.AlterField(
            model_name='produtoedital',
            name='tipo_produto',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('DIETA_ESPECIAL', 'Dieta especial')], max_length=25, verbose_name='tipo de produto'),
        ),
    ]
