# Generated by Django 2.2.13 on 2022-08-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0071_auto_20220804_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoedital',
            name='outras_informacoes',
            field=models.TextField(blank=True, verbose_name='Outras Informações'),
        ),
    ]
