# Generated by Django 2.2.13 on 2023-02-01 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0074_auto_20221207_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoedital',
            name='suspenso',
            field=models.BooleanField(default=False, verbose_name='Esta suspenso?'),
        ),
        migrations.AddField(
            model_name='produtoedital',
            name='suspenso_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspenso em'),
        ),
        migrations.AddField(
            model_name='produtoedital',
            name='suspenso_justificativa',
            field=models.CharField(blank=True, max_length=500, verbose_name='Porque foi suspenso individualmente'),
        ),
        migrations.AddField(
            model_name='produtoedital',
            name='suspenso_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
