# Generated by Django 3.2.18 on 2023-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0075_auto_20230201_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomedeprodutoedital',
            name='tipo_produto',
            field=models.CharField(choices=[('TERCEIRIZADA', 'Terceirizada'), ('LOGISTICA', 'Logistica')], default='TERCEIRIZADA', max_length=25, verbose_name='tipo de produto'),
        ),
    ]
