# Generated by Django 3.2.18 on 2023-07-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0076_nomedeprodutoedital_tipo_produto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomedeprodutoedital',
            unique_together={('nome', 'tipo_produto')},
        ),
    ]
