# Generated by Django 3.2.18 on 2023-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0077_alter_nomedeprodutoedital_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologacaoproduto',
            name='eh_copia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='eh_copia',
            field=models.BooleanField(default=False),
        ),
    ]
