# Generated by Django 3.2.18 on 2023-08-07 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0078_auto_20230718_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHoraVinculoProdutoEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('suspenso', models.BooleanField(default=False, verbose_name='Esta suspenso?')),
                ('produto_edital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datas_horas_vinculo', to='produto.produtoedital')),
            ],
            options={
                'verbose_name': 'Data e hora do vínculo',
                'verbose_name_plural': 'Datas e horas do vínculo',
                'ordering': ('criado_em',),
            },
        ),
    ]
