# Generated by Django 3.2.18 on 2023-08-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0079_datahoravinculoprodutoedital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datahoravinculoprodutoedital',
            options={'ordering': ('criado_em',), 'verbose_name': 'Data e hora do vínculo', 'verbose_name_plural': 'Datas e horas do vínculo'},
        ),
    ]
