# Generated by Django 3.2.18 on 2023-08-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0079_datahoravinculoprodutoedital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahoravinculoprodutoedital',
            name='produto_edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_horas_vinculo', to='produto.produtoedital'),
        ),
    ]
