# Generated by Django 3.2.18 on 2023-08-31 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0080_alter_datahoravinculoprodutoedital_produto_edital'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecipiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
