# Generated by Django 4.2.7 on 2024-04-10 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0082_informacaonutricional_eh_fixo"),
        ("produto", "0082_tipoalimento"),
    ]

    operations = []
