# Generated by Django 2.2.13 on 2020-11-06 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoRemessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('numero_solicitacao', models.CharField(blank=True, max_length=100, verbose_name='Número da solicitação')),
                ('status', models.CharField(choices=[('INTEGRADA', 'Integrada')], default='INTEGRADA', max_length=25, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Solicitação Remessa',
                'verbose_name_plural': 'Solicitações Remessas',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_guia', models.CharField(blank=True, max_length=100, verbose_name='Número da guia')),
                ('data_entrega', models.DateField(verbose_name='Data da entrega')),
                ('codigo_unidade', models.CharField(blank=True, max_length=10, verbose_name='Código da unidade')),
                ('nome_unidade', models.CharField(blank=True, max_length=150, verbose_name='Nome da unidade')),
                ('endereco_unidade', models.CharField(blank=True, max_length=300, verbose_name='Endereço da unidade')),
                ('numero_unidade', models.CharField(blank=True, max_length=10, verbose_name='Número da unidade')),
                ('bairro_unidade', models.CharField(blank=True, max_length=100, verbose_name='Bairro da unidade')),
                ('cep_unidade', models.CharField(blank=True, max_length=20, verbose_name='CEP da unidade')),
                ('cidade_unidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade da unidade')),
                ('estado_unidade', models.CharField(blank=True, max_length=2, verbose_name='Estado da unidade')),
                ('contato_unidade', models.CharField(blank=True, max_length=150, verbose_name='Contato na unidade')),
                ('telefone_unidade', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone da unidade')),
                ('status', models.CharField(choices=[('INTEGRADA', 'Integrada')], default='INTEGRADA', max_length=25, verbose_name='status')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='logistica.SolicitacaoRemessa')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
            },
        ),
    ]
