# Generated by Django 2.2.13 on 2020-11-09 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='telefone_unidade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone da unidade'),
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_suprimento', models.CharField(blank=True, max_length=100, verbose_name='Código suprimento')),
                ('codigo_papa', models.CharField(blank=True, max_length=10, verbose_name='Código papa')),
                ('nome_alimento', models.CharField(blank=True, max_length=100, verbose_name='Nome do alimento/produto')),
                ('embalagem', models.CharField(blank=True, max_length=100, verbose_name='Embalagem')),
                ('qtd_volume', models.PositiveSmallIntegerField(blank=True, verbose_name='Quantidade/Volume')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='logistica.Guia')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
