# Generated by Django 2.2.13 on 2020-11-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0003_auto_20191213_1339'),
        ('logistica', '0004_auto_20201113_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoremessa',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='terceirizada.Terceirizada'),
        ),
    ]
