# Generated by Django 2.2.13 on 2020-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_tipoembalagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoembalagem',
            name='sigla',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
