# Generated by Django 2.2.13 on 2021-01-14 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_auto_20201207_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoembalagem',
            options={'verbose_name': 'Tipo de Embalagem Fechada', 'verbose_name_plural': 'Tipos de Embalagens Fechadas'},
        ),
        migrations.AlterField(
            model_name='guia',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Número da guia'),
        ),
        migrations.AlterField(
            model_name='solicitacaoremessa',
            name='numero_solicitacao',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Número da solicitação'),
        ),
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao_embalagem', models.CharField(max_length=300, verbose_name='Descrição da Embalagem')),
                ('capacidade_embalagem', models.FloatField(verbose_name='Capacidade da Embalagem')),
                ('unidade_medida', models.CharField(max_length=10, verbose_name='Unidade de Medida')),
                ('tipo_embalagem', models.CharField(choices=[('FECHADA', 'Fechada'), ('FRACIONADA', 'Fracionada')], default='FECHADA', max_length=15)),
                ('qtd_volume', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade/Volume')),
                ('alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embalagens', to='logistica.Alimento')),
            ],
            options={
                'verbose_name': 'Embalagem',
                'verbose_name_plural': 'Embalagens',
            },
        ),
    ]
