# Generated by Django 2.2.13 on 2021-01-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_solicitacaodealteracaorequisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodealteracaorequisicao',
            name='justificativa',
            field=models.TextField(verbose_name='Justificativa'),
        ),
    ]
