# Generated by Django 2.2.13 on 2021-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_auto_20210120_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaodealteracaorequisicao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='solicitacaodealteracaorequisicao',
            name='hora',
        ),
    ]
