# Generated by Django 2.2.13 on 2021-01-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_auto_20210122_0927'),
        ('logistica', '0014_auto_20210121_1947'),
    ]

    operations = [
    ]
