# Generated by Django 2.2.13 on 2021-02-22 16:47

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_solicitacaodealteracaorequisicao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodealteracaorequisicao',
            name='status',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='EM_ANALISE', name='SolicitacaoDeAlteracaoWorkFlow', states=['EM_ANALISE', 'ACEITA', 'NEGADA'])),
        ),
    ]
