# Generated by Django 2.2.13 on 2021-03-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_auto_20210226_1748'),
        ('logistica', '0018_auto_20210222_1647'),
    ]

    operations = [
    ]
