# Generated by Django 2.2.13 on 2021-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_merge_20210302_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodealteracaorequisicao',
            name='justificativa_aceite',
            field=models.TextField(blank=True, verbose_name='Justificativa de aceite pela dilog'),
        ),
        migrations.AlterField(
            model_name='solicitacaodealteracaorequisicao',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Justificativa de solicitação pelo distribuidor'),
        ),
    ]
