# Generated by Django 2.2.13 on 2021-03-16 14:05

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0021_auto_20210315_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodealteracaorequisicao',
            name='justificativa_negacao',
            field=models.TextField(blank=True, verbose_name='Justificativa de negacao pela dilog'),
        ),
        migrations.AlterField(
            model_name='solicitacaoremessa',
            name='status',
            field=django_xworkflows.models.StateField(max_length=31, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='AGUARDANDO_ENVIO', name='SolicitacaoRemessaWorkFlow', states=['AGUARDANDO_ENVIO', 'DILOG_ENVIA', 'CANCELADA', 'DISTRIBUIDOR_CONFIRMA', 'DISTRIBUIDOR_SOLICITA_ALTERACAO', 'DILOG_ACEITA_ALTERACAO', 'DILOG_NEGA_ALTERACAO'])),
        ),
    ]
