# Generated by Django 2.2.13 on 2021-04-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0025_auto_20210415_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='status',
        ),
    ]
