# Generated by Django 2.2.13 on 2021-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0031_auto_20210521_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insucessoentregaguia',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
