# Generated by Django 2.2.13 on 2021-05-26 17:50

import uuid

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0033_auto_20210523_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaIndividualPorAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_embalagem', models.CharField(choices=[('FECHADA', 'Fechada'), ('FRACIONADA', 'Fracionada')], default='FECHADA', max_length=15)),
                ('nome_alimento', models.CharField(max_length=100, verbose_name='Nome do alimento/produto')),
                ('qtd_recebido', models.PositiveSmallIntegerField(verbose_name='Quantidade recebido')),
                ('observacao', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('status_alimento', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PARCIAL', 'Parcial'), ('NAO_RECEBIDO', 'Não recebido')], default='RECEBIDO', max_length=40)),
                ('ocorrencia', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('QTD_MENOR', 'Quantidade menor que a prevista'), ('PROBLEMA_QUALIDADE', 'Problema de qualidade do produto'), ('ALIMENTO_DIFERENTE', 'Alimento diferente do previsto'), ('EMBALAGEM_DANIFICADA', 'Embalagem danificada'), ('EMBALAGEM_VIOLADA', 'Embalagem violada'), ('VALIDADE_EXPIRADA', 'Prazo de validade expirado'), ('ATRASO_ENTREGA', 'Atraso na entrega'), ('AUSENCIA_PRODUTO', 'Ausência do produto')], max_length=136)),
                ('tem_ocorrencia', models.BooleanField(default=False)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='logistica.ConferenciaGuia')),
            ],
            options={
                'verbose_name': 'Conferência Individual por Alimento',
                'verbose_name_plural': 'Conferências Individuais por Alimentos',
            },
        ),
    ]
