# Generated by Django 2.2.13 on 2021-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0034_conferenciaindividualporalimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciaindividualporalimento',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
