# Generated by Django 2.2.13 on 2021-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0037_embalagem_qtd_a_receber'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciaguia',
            name='eh_reposicao',
            field=models.BooleanField(default=False),
        ),
    ]
