# Generated by Django 2.2.13 on 2021-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0038_conferenciaguia_eh_reposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='situacao',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('ARQUIVADA', 'Arquivada')], default='ATIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitacaoremessa',
            name='situacao',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('ARQUIVADA', 'Arquivada')], default='ATIVA', max_length=10),
        ),
    ]
