# Generated by Django 2.2.13 on 2021-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0039_auto_20210714_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='telefone_unidade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefone da unidade'),
        ),
    ]
