# Generated by Django 2.2.13 on 2021-10-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0040_auto_20210914_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoremessa',
            name='sequencia_envio',
            field=models.IntegerField(null=True, verbose_name='Sequência de envio atribuído pelo papa'),
        ),
    ]
