# Generated by Django 2.2.13 on 2022-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0045_auto_20220703_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insucessoentregaguia',
            name='motivo',
            field=models.CharField(choices=[('UNIDADE_FECHADA', 'Unidade educacional fechada'), ('UNIDADE_SEM_ENERGIA', 'Unidade educacional sem energia elétrica'), ('UNIDADE_SEM_ACESSO', 'Interdição de via de acesso ao local de entrega'), ('OUTROS', 'Outros')], default='UNIDADE_FECHADA', max_length=25, verbose_name='Motivo do insucesso'),
        ),
    ]
