# Generated by Django 3.2.16 on 2023-05-18 01:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0047_insucessoentregaguia_outro_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenciaindividualporalimento',
            name='ocorrencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('QTD_MENOR', 'Quantidade menor que a prevista'), ('PROBLEMA_QUALIDADE', 'Problema de qualidade do produto'), ('ALIMENTO_DIFERENTE', 'Alimento diferente do previsto'), ('EMBALAGEM_DANIFICADA', 'Embalagem danificada'), ('EMBALAGEM_VIOLADA', 'Embalagem violada'), ('VALIDADE_EXPIRADA', 'Prazo de validade expirado'), ('ATRASO_ENTREGA', 'Atraso na entrega'), ('AUSENCIA_PRODUTO', 'Ausência do produto'), ('FALTA_URBANIDADE', 'Falta de urbanidade na entrega'), ('FALTA_ESPACO_ARMAZENAMENTO', 'Falta de espaço no freezer para armazenamento')], max_length=180),
        ),
    ]
