# Generated by Django 3.2.18 on 2023-06-27 17:08

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0051_auto_20230608_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoocorrenciasguia',
            name='status',
            field=django_xworkflows.models.StateField(max_length=26, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='NotificacaoOcorrenciaWorkflow', states=['RASCUNHO', 'NOTIFICACAO_CRIADA', 'NOTIFICACAO_ENVIADA_FISCAL'])),
        ),
    ]
