# Generated by Django 3.2.18 on 2023-06-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0052_alter_notificacaoocorrenciasguia_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaoocorrenciasguia',
            name='link_processo_sei',
        ),
    ]
