# Generated by Django 3.2.18 on 2023-06-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0054_alter_notificacaoocorrenciasguia_processo_sei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoocorrenciasguia',
            name='processo_sei',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Nº do Processo SEI'),
        ),
    ]
