# Generated by Django 4.2.7 on 2024-04-24 13:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recebimento", "0003_fichaderecebimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaderecebimento",
            name="data_fabricacao_de_acordo",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Data(s) de Fabricação Observada(s) estão de acordo?",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="data_fabricacao_divergencia",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Descrição da divergência nas Data(s) de Fabricação",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="data_validade_de_acordo",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Data(s) de Validades Observada(s) estão de acordo?",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="data_validade_divergencia",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Descrição da divergência nas Data(s) de Validades",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="lote_fabricante_de_acordo",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Lote(s) do Fabricante Observado(s) estão de acordo?",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="lote_fabricante_divergencia",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Descrição da divergência nos Lote(s) do Fabricante",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="numero_lote_armazenagem",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Nº do Lote Armazenagem",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="numero_paletes",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nº de Paletes"
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="peso_embalagem_primaria_1",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Peso da Embalagem Primária (1)",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="peso_embalagem_primaria_2",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Peso da Embalagem Primária (2)",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="peso_embalagem_primaria_3",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Peso da Embalagem Primária (3)",
            ),
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="peso_embalagem_primaria_4",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Peso da Embalagem Primária (4)",
            ),
        ),
        migrations.CreateModel(
            name="VeiculoFichaDeRecebimento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "numero",
                    models.CharField(max_length=25, verbose_name="Nº do Veículo"),
                ),
                (
                    "temperatura_recebimento",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Temperatura da Área de Recebimento (°C)",
                    ),
                ),
                (
                    "temperatura_produto",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Temperatura do Produto (°C)",
                    ),
                ),
                ("placa", models.CharField(blank=True, max_length=15, null=True)),
                ("lacre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_sif_sisbi_sisp",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nº SIF, SISBI ou SISP",
                    ),
                ),
                (
                    "numero_nota_fiscal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantidade_nota_fiscal",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "embalagens_nota_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Quantidade de Embalagens da Nota Fiscal",
                    ),
                ),
                (
                    "quantidade_recebida",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "embalagens_recebidas",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Quantidade de Embalagens da Recebidas",
                    ),
                ),
                (
                    "estado_higienico_adequado",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Estado Higiênico-Sanitário adequado?",
                    ),
                ),
                ("termografo", models.BooleanField(blank=True, null=True)),
                (
                    "ficha_recebimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veiculos",
                        to="recebimento.fichaderecebimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo Ficha de Recebimento",
                "verbose_name_plural": "Veículos Fichas de Recebimentos",
            },
        ),
    ]
