# Generated by Django 4.2.7 on 2024-04-19 10:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0057_cronograma_tipo_embalagem_secundaria"),
        ("recebimento", "0002_questoesporproduto"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaDeRecebimento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Entrega"
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ficha_recebimento",
                        to="pre_recebimento.etapasdocronograma",
                        verbose_name="Etapa do Cronograma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de Recebimento",
                "verbose_name_plural": "Fichas de Recebimentos",
            },
        ),
    ]
