# Generated by Django 2.0.13 on 2019-07-17 14:44

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('inclusao_alimentacao', '0001_initial'), ('inclusao_alimentacao', '0002_auto_20190711_1118'),
                ('inclusao_alimentacao', '0003_auto_20190717_1011'),
                ('inclusao_alimentacao', '0004_auto_20190717_1118')]

    initial = True

    dependencies = [
        ('dados_comuns', '0001_initial'),
        ('escola', '0001_initial'),
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoInclusaoAlimentacaoNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
            ],
            options={
                'verbose_name': 'Grupo de inclusão de alimentação normal',
                'verbose_name_plural': 'Grupos de inclusão de alimentação normal',
            },
        ),
        migrations.CreateModel(
            name='InclusaoAlimentacaoContinua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('data_inicial', models.DateField(verbose_name='Data inicial')),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outro_motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outro motivo')),
                # ('dias_semana', models.ManyToManyField(to='dados_comuns.DiaSemana')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
            ],
            options={
                'verbose_name': 'Inclusão de alimentação contínua',
                'verbose_name_plural': 'Inclusões de alimentação contínua',
            },
        ),
        migrations.CreateModel(
            name='InclusaoAlimentacaoNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prioritario', models.BooleanField(default=False)),
                ('outro_motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outro motivo')),
            ],
            options={
                'verbose_name': 'Inclusão de alimentação normal',
                'verbose_name_plural': 'Inclusões de alimentação normal',
            },
        ),
        migrations.CreateModel(
            name='MotivoInclusaoContinua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de inclusao contínua',
                'verbose_name_plural': 'Motivos de inclusao contínua',
            },
        ),
        migrations.CreateModel(
            name='MotivoInclusaoNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de inclusao normal',
                'verbose_name_plural': 'Motivos de inclusao normais',
            },
        ),
        migrations.CreateModel(
            name='QuantidadePorPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_alunos',
                 models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('periodo_escolar',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar')),
                ('tipos_alimentacao', models.ManyToManyField(to='cardapio.TipoAlimentacao')),
            ],
            options={
                'verbose_name': 'Quantidade por periodo',
                'verbose_name_plural': 'Quantidades por periodo',
            },
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='inclusao_alimentacao.MotivoInclusaoNormal'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='quantidade_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='inclusao_alimentacao.QuantidadePorPeriodo'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='inclusao_alimentacao.MotivoInclusaoContinua'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='quantidades_periodo',
            field=models.ManyToManyField(to='inclusao_alimentacao.QuantidadePorPeriodo'),
        ),
        migrations.AddField(
            model_name='grupoinclusaoalimentacaonormal',
            name='inclusoes',
            field=models.ManyToManyField(to='inclusao_alimentacao.InclusaoAlimentacaoNormal'),
        ),
        # migrations.RemoveField(
        #     model_name='inclusaoalimentacaocontinua',
        #     name='dias_semana',
        # ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(blank=True,
                                                            choices=[(0,
                                                                      'Segunda'),
                                                                     (1,
                                                                      'Terça'),
                                                                     (3,
                                                                      'Quarta'),
                                                                     (2,
                                                                      'Quinta'),
                                                                     (4,
                                                                      'Sexta'),
                                                                     (5,
                                                                      'Sábado'),
                                                                     (6,
                                                                      'Domingo')],
                                                            default=[],
                                                            null=True),
                size=None),
        ),
    ]
