# Generated by Django 2.0.13 on 2019-07-11 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inclusaoalimentacaonormal',
            old_name='quantidades_periodo',
            new_name='quantidade_periodo',
        ),
        migrations.AlterField(
            model_name='quantidadeporperiodo',
            name='numero_alunos',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
