# Generated by Django 2.0.13 on 2019-07-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0001_squashed_0004_auto_20190717_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinclusaoalimentacaonormal',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grupos_inclusoes_normais', to='escola.Escola'),
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaocontinua',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusoes_alimentacao_continua', to='escola.Escola'),
        ),
    ]
