# Generated by Django 2.0.13 on 2019-07-17 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0002_auto_20190711_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusaoalimentacaocontinua',
            name='dias_semana',
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], default=[], null=True), default=[1], size=None),
            preserve_default=False,
        ),
    ]
