# Generated by Django 2.0.13 on 2019-08-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0002_auto_20190805_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusaoalimentacaonormal',
            name='prioritario',
        ),
    ]
