# Generated by Django 2.0.13 on 2019-08-15 10:57

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0002_auto_20190805_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinclusaoalimentacaonormal',
            name='status',
            field=django_xworkflows.models.StateField(max_length=25, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_APROVADO', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO', 'CODAE_RECUSOU', 'TERCEIRIZADA_TOMA_CIENCIA'])),
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaocontinua',
            name='status',
            field=django_xworkflows.models.StateField(max_length=25, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_APROVADO', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO', 'CODAE_RECUSOU', 'TERCEIRIZADA_TOMA_CIENCIA'])),
        ),
    ]
