# Generated by Django 2.0.13 on 2019-07-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0002_auto_20190719_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoinclusaoalimentacaonormal',
            name='inclusoes',
        ),
        migrations.RemoveField(
            model_name='inclusaoalimentacaocontinua',
            name='quantidades_periodo',
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='grupo_inclusao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusoes_normais', to='inclusao_alimentacao.GrupoInclusaoAlimentacaoNormal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantidadeporperiodo',
            name='grupo_inclusao_normal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantidades_por_periodo', to='inclusao_alimentacao.GrupoInclusaoAlimentacaoNormal'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodo',
            name='inclusao_alimentacao_continua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantidades_por_periodo', to='inclusao_alimentacao.InclusaoAlimentacaoContinua'),
        ),
    ]
