# Generated by Django 2.0.13 on 2019-07-17 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0003_auto_20190717_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusaoalimentacaocontinua',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (3, 'Quarta'), (2, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], default=[], null=True), size=None),
        ),
    ]
