# Generated by Django 2.0.13 on 2019-07-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inclusao_alimentacao', '0003_auto_20190722_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusaoalimentacaonormal',
            name='grupo_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='inclusoes_normais',
                                    to='inclusao_alimentacao.GrupoInclusaoAlimentacaoNormal'),
        ),
    ]
