# Generated by Django 2.0.13 on 2019-09-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0003_auto_20190902_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantidadeporperiodo',
            options={},
        ),
    ]
