# Generated by Django 2.0.13 on 2019-08-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0003_auto_20190815_0757'),
        ('inclusao_alimentacao', '0003_remove_inclusaoalimentacaonormal_prioritario'),
    ]

    operations = [
    ]
