# Generated by Django 2.0.13 on 2019-07-25 15:12

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0004_auto_20190722_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaocontinua',
            name='status',
            field=django_xworkflows.models.StateField(max_length=23, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_APROVADO', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO'])),
        ),
    ]
