# Generated by Django 2.0.13 on 2019-08-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0004_auto_20190816_0821'),
        ('inclusao_alimentacao', '0004_merge_20190815_1525'),
    ]

    operations = [
    ]
