# Generated by Django 2.0.13 on 2019-08-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0003_auto_20190815_1225'),
        ('inclusao_alimentacao', '0005_merge_20190816_1152'),
    ]

    operations = [
    ]
