# Generated by Django 2.0.13 on 2019-08-16 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inclusao_alimentacao', '0005_merge_20190816_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inclusaoalimentacaocontinua',
            options={'ordering': ['data_inicial'], 'verbose_name': 'Inclusão de alimentação contínua',
                     'verbose_name_plural': 'Inclusões de alimentação contínua'},
        ),
        migrations.AlterModelOptions(
            name='inclusaoalimentacaonormal',
            options={'ordering': ('data',), 'verbose_name': 'Inclusão de alimentação normal',
                     'verbose_name_plural': 'Inclusões de alimentação normal'},
        ),
    ]
