# Generated by Django 2.0.13 on 2019-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0004_auto_20190816_1653'),
        ('inclusao_alimentacao', '0006_auto_20190816_1541'),
    ]

    operations = [
    ]
