# Generated by Django 2.0.13 on 2019-08-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0006_auto_20190816_1541'),
        ('inclusao_alimentacao', '0006_merge_20190816_1408'),
    ]

    operations = [
    ]
