# Generated by Django 2.0.13 on 2019-08-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inclusao_alimentacao', '0007_inclusaoalimentacaocontinua_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descricao'),
        ),
        migrations.AddField(
            model_name='inclusaoalimentacaonormal',
            name='status',
            field=django_xworkflows.models.StateField(max_length=23, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_APROVADO', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO'])),
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaonormal',
            name='grupo_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusoes_normais', to='inclusao_alimentacao.GrupoInclusaoAlimentacaoNormal'),
        ),
        migrations.AlterField(
            model_name='inclusaoalimentacaonormal',
            name='quantidade_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inclusao_alimentacao.QuantidadePorPeriodo'),
        ),
    ]
