# Generated by Django 2.0.13 on 2019-08-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0007_merge_20190816_1615'),
        ('inclusao_alimentacao', '0007_merge_20190819_0852'),
    ]

    operations = [
    ]
