# Generated by Django 2.0.13 on 2019-08-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0008_merge_20190819_1131'),
        ('inclusao_alimentacao', '0008_merge_20190819_1559'),
    ]

    operations = [
    ]
