# Generated by Django 2.0.13 on 2019-08-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0009_auto_20190801_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusaoalimentacaonormal',
            name='quantidade_periodo',
        ),
    ]
