# Generated by Django 2.0.13 on 2019-08-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusao_alimentacao', '0011_merge_20190820_1424'),
        ('inclusao_alimentacao', '0010_auto_20190820_1113'),
    ]

    operations = [
    ]
