# Generated by Django 4.2.7 on 2024-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dieta_especial", "0058_logquantidadedietasautorizadas_cei_ou_emei"),
    ]

    operations = [
        migrations.AddField(
            model_name="logquantidadedietasautorizadas",
            name="infantil_ou_fundamental",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("INFANTIL", "INFANTIL"),
                    ("FUNDAMENTAL", "FUNDAMENTAL"),
                ],
                default="N/A",
                max_length=11,
            ),
        ),
    ]
