PERIODOS_ESPECIAIS_CEI_CEU_CCI = ['INTEGRAL', 'PARCIAL']
PERIODOS_ESPECIAIS_CEU_GESTAO = ['MANHA', 'TARDE', 'INTEGRAL', 'NOITE']
PERIODOS_ESPECIAIS_CEMEI = ['MANHA', 'TARDE', 'INTEGRAL']
PERIODOS_ESPECIAIS_CEI_DIRET = ['MANHA', 'TARDE', 'INTEGRAL']
