PERIODOS_ESPECIAIS_CEI_CEU_CCI = ['INTEGRAL', 'PARCIAL']
PERIODOS_ESPECIAIS_CEU_GESTAO = ['MANHA', 'TARDE', 'INTEGRAL', 'NOITE']
PERIODOS_ESPECIAIS_CEMEI = ['MANHA', 'TARDE', 'INTEGRAL']
PERIODOS_CEMEI_EVENTO_ESPECIFICO = ['MANHA', 'TARDE', 'INTEGRAL', 'NOITE']
PERIODOS_ESPECIAIS_CEI_DIRET = ['MANHA', 'TARDE', 'INTEGRAL']
CEI_OU_EMEI = (
    ('N/A', 'N/A'),
    ('CEI', 'CEI'),
    ('EMEI', 'EMEI')
)
