# Generated by Django 2.0.13 on 2019-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20190902_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registro_funcional',
            field=models.CharField(default='', max_length=10, verbose_name='RF'),
        ),
    ]
