# Generated by Django 2.0.13 on 2019-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_usuario_registro_funcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoperfil',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
