# Generated by Django 2.2.6 on 2019-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20191008_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vinculo_funcional',
            field=models.CharField(default='', max_length=2, verbose_name='Vinculo'),
        ),
    ]
