# Generated by Django 2.2.6 on 2019-10-23 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('data_inicial', models.DateField(verbose_name='Data inicial')),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
            },
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='permissao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfis',
        ),
        migrations.AddField(
            model_name='perfil',
            name='super_usuario',
            field=models.BooleanField(default=False, verbose_name='Super usuario na instiuição?'),
        ),
        migrations.DeleteModel(
            name='GrupoPerfil',
        ),
        migrations.DeleteModel(
            name='PerfilPermissao',
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
        migrations.AddField(
            model_name='vinculo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
