# Generated by Django 2.2.6 on 2019-10-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='vinculo_funcional',
        ),
    ]
