# Generated by Django 2.2.6 on 2019-10-23 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20191023_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
