# Generated by Django 2.2.6 on 2019-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_auto_20191023_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='data_final',
            field=models.DateField(null=True, verbose_name='Data final'),
        ),
    ]
