# Generated by Django 2.2.13 on 2020-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaDiretorCogestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
