# Generated by Django 2.2.6 on 2019-10-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('perfil', '0010_auto_20191023_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
