# Generated by Django 2.2.6 on 2019-10-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_auto_20191024_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinculo',
            old_name='object_id',
            new_name='instituicao_id',
        ),
        migrations.RenameField(
            model_name='vinculo',
            old_name='content_type',
            new_name='tipo_instituicao',
        ),
    ]
