# Generated by Django 2.2.13 on 2022-01-25 21:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_auto_20201009_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoPlanilhaUsuarioPerfilEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conteudo', models.FileField(blank=True, default='', upload_to='')),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO')], default='PENDENTE', max_length=35, verbose_name='status')),
                ('log', models.TextField(blank=True, default='')),
                ('resultado', models.FileField(blank=True, default='', upload_to='')),
            ],
            options={
                'verbose_name': 'Arquivo para importação de usuário perfil Escola',
                'verbose_name_plural': 'Arquivos para importação de usuários perfil Escola',
            },
        ),
    ]
