# Generated by Django 2.2.6 on 2019-10-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_auto_20191024_1133'),
        ('perfil', '0007_remove_usuario_vinculo_funcional'),
    ]

    operations = [
    ]
