# Generated by Django 2.2.6 on 2019-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_auto_20191030_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='data_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Data inicial'),
        ),
    ]
