# Generated by Django 2.2.13 on 2022-07-26 11:35

from django.db import migrations, models
from django.db.models import F


def migrate_default_values(apps, schmema_editor):
    Usuario = apps.get_model('perfil', 'Usuario')
    Usuario.objects.all().update(
        username=F('email'))


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_importacaoplanilhausuarioperfildre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.RunPython(migrate_default_values),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),

    ]
