# Generated by Django 2.2.6 on 2019-11-26 14:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_auto_20191031_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de e-mail',
                'verbose_name_plural': 'Tipos de e-mail',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.TipoEmail'),
        ),
    ]
