# Generated by Django 2.2.6 on 2019-11-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0018_auto_20191126_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_email',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '@sme.prefeitura.sp.gov.br'), (1, '@prefeitura.sp.gov.br')], null=True),
        ),
        migrations.DeleteModel(
            name='TipoEmail',
        ),
    ]
