# Generated by Django 2.2.13 on 2022-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_perfil_tipo_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaoplanilhausuarioexternocoresso',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO'), ('REMOVIDO', 'REMOVIDO')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='importacaoplanilhausuarioperfilcodae',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO'), ('REMOVIDO', 'REMOVIDO')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='importacaoplanilhausuarioperfildre',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO'), ('REMOVIDO', 'REMOVIDO')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='importacaoplanilhausuarioperfilescola',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO'), ('REMOVIDO', 'REMOVIDO')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='importacaoplanilhausuarioservidorcoresso',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO'), ('REMOVIDO', 'REMOVIDO')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='visao',
            field=models.CharField(blank=True, choices=[('ESCOLA', 'Escola'), ('DRE', 'Diretoria Regional'), ('CODAE', 'CODAE'), ('EMPRESA', 'Empresa')], default=None, max_length=25, null=True, verbose_name='Visão'),
        ),
    ]
