# Generated by Django 4.2.7 on 2024-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0022_importacaoplanilhausuarioueparceiracoresso"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="aceitou_termos",
            field=models.BooleanField(default=False),
        ),
    ]
