# Generated by Django 4.2.7 on 2024-04-11 15:53

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0002_categoriaocorrencia_tipoocorrencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPerguntaParametrizacaoOcorrencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Pergunta para Parametrização de Tipo de Ocorrência",
                "verbose_name_plural": "Tipos de Pergunta para Parametrização de Tipo de Ocorrência",
            },
        ),
        migrations.AlterField(
            model_name="categoriaocorrencia",
            name="perfis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DIRETOR", "DIRETOR"), ("SUPERVISAO", "SUPERVISAO")],
                    default=[],
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="perfis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DIRETOR", "DIRETOR"), ("SUPERVISAO", "SUPERVISAO")],
                    default=[],
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="ParametrizacaoOcorrencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "posicao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "tipo_ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametrizacoes",
                        to="imr.tipoocorrencia",
                    ),
                ),
                (
                    "tipo_pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametrizacoes",
                        to="imr.tipoperguntaparametrizacaoocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização de Tipo de Ocorrência",
                "verbose_name_plural": "Parametrizações de Tipo de Ocorrência",
            },
        ),
    ]
