# Generated by Django 4.2.7 on 2024-04-11 11:51

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0002_categoriaocorrencia_tipoocorrencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametrizacaoOcorrencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "posicao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "tipo_resposta",
                    models.CharField(
                        choices=[
                            ("Opções Sim/Não", "Opções Sim/Não"),
                            ("Campo Numérico", "Campo Numérico"),
                            ("Campo de Texto Simples", "Campo de Texto Simples"),
                            ("Campo de Texto Longo", "Campo de Texto Longo"),
                            ("Seletor de Datas", "Seletor de Datas"),
                            ("Seletor de Períodos", "Seletor de Períodos"),
                            ("Seletor de Faixas Etárias", "Seletor de Faixas Etárias"),
                            (
                                "Seletor de Sim/Não/Não se aplica",
                                "Seletor de Sim/Não/Não se aplica",
                            ),
                        ],
                        verbose_name="Tipo de resposta",
                    ),
                ),
                (
                    "tipo_ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametrizacoes",
                        to="imr.tipoocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização de Tipo de Ocorrência",
                "verbose_name_plural": "Parametrizações de Tipo de Ocorrência",
            },
        ),
    ]
