# Generated by Django 4.2.7 on 2024-04-12 12:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0002_categoriaocorrencia_tipoocorrencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaocorrencia",
            name="perfis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DIRETOR", "DIRETOR"), ("SUPERVISAO", "SUPERVISAO")],
                    default=[],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="obrigacaopenalidade",
            name="tipo_penalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obrigacoes",
                to="imr.tipopenalidade",
                verbose_name="Tipo de Penalidade",
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipos_ocorrencia",
                to="imr.categoriaocorrencia",
                verbose_name="Categoria da Ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="penalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipos_ocorrencia",
                to="imr.tipopenalidade",
                verbose_name="Penalidade do Item",
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="perfis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DIRETOR", "DIRETOR"), ("SUPERVISAO", "SUPERVISAO")],
                    default=[],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="pontuacao",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Pontuação (IMR)"
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="tolerancia",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Tolerância"
            ),
        ),
    ]
