# Generated by Django 4.2.7 on 2024-04-11 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0003_parametrizacaoocorrencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaocorrencia",
            name="perfis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DIRETOR", "DIRETOR"), ("SUPERVISAO", "SUPERVISAO")],
                    default=[],
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="tipoocorrencia",
            name="perfis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DIRETOR", "DIRETOR"), ("SUPERVISAO", "SUPERVISAO")],
                    default=[],
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
