# Generated by Django 4.2.7 on 2024-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0004_alter_categoriaocorrencia_perfis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrizacaoocorrencia",
            name="tipo_resposta",
            field=models.CharField(
                choices=[
                    ("Opções Sim/Não", "Opções Sim/Não"),
                    ("Campo Numérico", "Campo Numérico"),
                    ("Campo de Texto Simples", "Campo de Texto Simples"),
                    ("Campo de Texto Longo", "Campo de Texto Longo"),
                    ("Seletor de Datas", "Seletor de Datas"),
                    ("Seletor de Períodos", "Seletor de Períodos"),
                    ("Seletor de Faixas Etárias", "Seletor de Faixas Etárias"),
                    (
                        "Seletor de Tipo de Alimentação",
                        "Seletor de Tipo de Alimentação",
                    ),
                    (
                        "Seletor de Sim/Não/Não se aplica",
                        "Seletor de Sim/Não/Não se aplica",
                    ),
                ],
                verbose_name="Tipo de resposta",
            ),
        ),
    ]
