# Generated by Django 4.2.7 on 2024-04-15 16:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0069_logalunopordia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicao_inicial", "0041_alter_parametrizacaofinanceira_options"),
        ("imr", "0004_parametrizacaoocorrencia_tiporespostamodelo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioOcorrenciasBase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data", models.DateField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formularios_ocorrencias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulário Base - Ocorrências",
                "verbose_name_plural": "Formulários Base - Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="PeriodoVisita",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Período de Visita",
                "verbose_name_plural": "Períodos de Visita",
            },
        ),
        migrations.CreateModel(
            name="FormularioSupervisao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nome_nutricionista_empresa",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nome da Nutricionista RT da Empresa",
                    ),
                ),
                (
                    "acompanhou_visita",
                    models.BooleanField(
                        default=False, verbose_name="Acompanhou a visita?"
                    ),
                ),
                (
                    "apresentou_ocorrencias",
                    models.BooleanField(
                        default=False,
                        verbose_name="No momento da visita, a prestação de serviços apresentou ocorrências?",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formularios_supervisao",
                        to="escola.escola",
                    ),
                ),
                (
                    "formulario_base",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imr.formularioocorrenciasbase",
                    ),
                ),
                (
                    "periodo_visita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formularios_supervisao",
                        to="imr.periodovisita",
                        verbose_name="Período da Visita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulário da Supervisão - Ocorrências",
                "verbose_name_plural": "Formulários da Supervisão - Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="FormularioDiretor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "formulario_base",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imr.formularioocorrenciasbase",
                    ),
                ),
                (
                    "solicitacao_medicao_inicial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formularios_ocorrencias",
                        to="medicao_inicial.solicitacaomedicaoinicial",
                        verbose_name="Solicitação Medição Inicial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulário do Diretor - Ocorrências",
                "verbose_name_plural": "Formulários do Diretor - Ocorrências",
            },
        ),
        migrations.AddField(
            model_name="respostacamponumerico",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_campo_numerico",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostacampotextolongo",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_campo_texto_longo",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostacampotextosimples",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_campo_texto_simples",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostadatas",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_datas",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostafaixaetaria",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_faixa_etaria",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostaperiodo",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_periodo",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostasimnao",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_sim_nao",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostasimnaonaoseaplica",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_sim_nao_nao_se_aplica",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
        migrations.AddField(
            model_name="respostatipoalimentacao",
            name="formulario_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_tipos_alimentacao",
                to="imr.formularioocorrenciasbase",
                verbose_name="Formulário de Ocorrências",
            ),
        ),
    ]
