# Generated by Django 4.2.7 on 2024-04-19 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0005_formularioocorrenciasbase_periodovisita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoocorrencia",
            name="eh_imr",
            field=models.BooleanField(default=False, verbose_name="É IMR?"),
        ),
        migrations.AddField(
            model_name="tipoocorrencia",
            name="porcentagem_desconto",
            field=models.FloatField(
                help_text="Caso a opção de É IMR? esteja marcada a % de desconto incidirá sobre a reincidência dos apontamentos. Se não for marcada a opção de É IMR?, a % de desconto será referente a multa da penalidade.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="% de desconto",
            ),
        ),
    ]
