# Generated by Django 4.2.7 on 2024-04-29 14:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0010_importacaoplanilhatipoocorrencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaNaoSeAplica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("resposta", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "formulario_base",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_nao_se_aplica",
                        to="imr.formularioocorrenciasbase",
                        verbose_name="Formulário de Ocorrências",
                    ),
                ),
                (
                    "tipo_ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_nao_se_aplica",
                        to="imr.parametrizacaoocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta Não se aplica",
                "verbose_name_plural": "Respostas Não se aplica",
            },
        ),
    ]
