# Generated by Django 4.2.7 on 2024-05-03 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0010_importacaoplanilhatipoocorrencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtensilioMesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativo"), (False, "Inativo")],
                        default=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Utensílio de Mesa",
                "verbose_name_plural": "Utensílios de Mesa",
                "ordering": ("nome",),
            },
        ),
    ]
