# Generated by Django 4.2.7 on 2024-04-25 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0011_alter_categoriaocorrencia_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipopenalidade",
            options={
                "ordering": ("edital__numero", "numero_clausula"),
                "verbose_name": "Tipo de Penalidade",
                "verbose_name_plural": "Tipos de Penalidades",
            },
        ),
    ]
