# Generated by Django 4.2.7 on 2024-05-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0013_remove_tipoocorrencia_modelo_anexo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anexosformulariobase",
            options={
                "verbose_name": "Anexo Formulário Base",
                "verbose_name_plural": "Anexos Formulário Base",
            },
        ),
        migrations.AlterModelOptions(
            name="notificacoesassinadasformulariobase",
            options={
                "verbose_name": "Notificação Assinada Formulário Base",
                "verbose_name_plural": "Notificações Assinadas Formulário Base",
            },
        ),
        migrations.AddField(
            model_name="respostacamponumerico",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostacampotextolongo",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostacampotextosimples",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostadatas",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostafaixaetaria",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostanaoseaplica",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostaperiodo",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostasimnao",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostasimnaonaoseaplica",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AddField(
            model_name="respostatipoalimentacao",
            name="grupo",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Grupo de respostas"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="respostacamponumerico",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostacampotextolongo",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostacampotextosimples",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostadatas",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostafaixaetaria",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostanaoseaplica",
            unique_together={("formulario_base", "tipo_ocorrencia", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostaperiodo",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostasimnao",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostasimnaonaoseaplica",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
        migrations.AlterUniqueTogether(
            name="respostatipoalimentacao",
            unique_together={("formulario_base", "parametrizacao", "grupo")},
        ),
    ]
