# Generated by Django 4.2.7 on 2024-05-06 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0013_remove_tipoocorrencia_modelo_anexo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anexosformulariobase",
            options={
                "verbose_name": "Anexo Formulário Base",
                "verbose_name_plural": "Anexos Formulário Base",
            },
        ),
        migrations.AlterModelOptions(
            name="notificacoesassinadasformulariobase",
            options={
                "verbose_name": "Notificação Assinada Formulário Base",
                "verbose_name_plural": "Notificações Assinadas Formulário Base",
            },
        ),
    ]
