# Generated by Django 4.2.7 on 2024-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0014_alter_anexosformulariobase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoocorrencia",
            name="aceita_multiplas_respostas",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Aceita múltiplas respostas?",
            ),
        ),
    ]
