# Generated by Django 4.2.7 on 2024-05-10 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0018_mobiliario_editalmobiliario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariosupervisao",
            name="apresentou_ocorrencias",
        ),
    ]
