# Generated by Django 4.2.7 on 2024-05-10 17:31

import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0022_ocorrencianaoseaplica_delete_respostanaoseaplica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariosupervisao",
            name="apresentou_ocorrencias",
        ),
        migrations.AddField(
            model_name="formulariosupervisao",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="EM_PREENCHIMENTO",
                    name="FormularioSupervisaoWorkflow",
                    states=["EM_PREENCHIMENTO"],
                ),
            ),
        ),
        migrations.AlterField(
            model_name="formulariosupervisao",
            name="nome_nutricionista_empresa",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nome da Nutricionista RT da Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="formulariosupervisao",
            name="periodo_visita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formularios_supervisao",
                to="imr.periodovisita",
                verbose_name="Período da Visita",
            ),
        ),
    ]
