# Generated by Django 4.2.7 on 2024-05-20 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0026_formulariosupervisao_maior_frequencia_no_periodo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametrizacaoocorrencia",
            options={
                "ordering": (
                    "tipo_ocorrencia__categoria__posicao",
                    "tipo_ocorrencia__posicao",
                    "posicao",
                ),
                "verbose_name": "Parametrização de Tipo de Ocorrência",
                "verbose_name_plural": "Parametrizações de Tipo de Ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoocorrencia",
            options={
                "ordering": ("categoria__posicao", "posicao"),
                "verbose_name": "Tipo de Ocorrência",
                "verbose_name_plural": "Tipos de Ocorrência",
            },
        ),
    ]
