# Generated by Django 4.2.7 on 2024-05-27 15:45

import django.core.validators
from django.db import migrations, models

import sme_terceirizadas.dados_comuns.validators


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0027_alter_parametrizacaoocorrencia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexosformulariobase",
            name="nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="anexosformulariobase",
            name="anexo",
            field=models.FileField(
                upload_to="IMR",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "PDF",
                            "XLS",
                            "XLSX",
                            "XLSM",
                            "DOC",
                            "DOCX",
                            "PNG",
                            "JPG",
                            "JPEG",
                        ]
                    ),
                    sme_terceirizadas.dados_comuns.validators.validate_file_size_10mb,
                ],
                verbose_name="Anexo",
            ),
        ),
    ]
