# Generated by Django 4.2.7 on 2024-02-02 14:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0067_grupounidadeescolar"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoMatriculaAluno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(null=True)),
                ("codigo_situacao", models.IntegerField()),
                ("situacao", models.CharField(blank=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="escola.aluno",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="escola.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Matrícula do Aluno",
                "verbose_name_plural": "Históricos de Matrículas dos Alunos",
                "unique_together": {("aluno", "escola")},
            },
        ),
    ]
