# Generated by Django 4.2.7 on 2024-05-23 15:32

import datetime

from django.db import migrations, models


def preenchar_campo_para_escolas_com_acesso_modulo_medicao(apps, _):
    Escola = apps.get_model("escola", "Escola")
    escolas_com_acesso_modulo_medicao = Escola.objects.filter(
        acesso_modulo_medicao_inicial=True
    )
    tipo_unidades_emef_emei = ["EMEF", "EMEI", "CEU EMEI"]
    escolas_com_acesso_modulo_medicao.filter(
        tipo_unidade__iniciais__in=tipo_unidades_emef_emei
    ).update(acesso_desde=datetime.date(2023, 8, 1))
    escolas_com_acesso_modulo_medicao.exclude(
        tipo_unidade__iniciais__in=tipo_unidades_emef_emei
    ).update(acesso_desde=datetime.date(2023, 12, 1))


def backwards(apps, _):
    Escola = apps.get_model("escola", "Escola")
    escolas_com_acesso_modulo_medicao = Escola.objects.filter(
        acesso_modulo_medicao_inicial=True
    )
    escolas_com_acesso_modulo_medicao.update(acesso_desde=None)


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0069_logalunopordia"),
    ]

    operations = [
        migrations.AddField(
            model_name="escola",
            name="acesso_desde",
            field=models.DateField(
                blank=True, null=True, verbose_name="Acesso módulo medição desde"
            ),
        ),
        migrations.RunPython(
            preenchar_campo_para_escolas_com_acesso_modulo_medicao, backwards
        ),
    ]
