# Generated by Django 4.2.7 on 2024-06-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0070_escola_acesso_desde"),
    ]

    operations = [
        migrations.AddField(
            model_name="alunoperiodoparcial",
            name="data",
            field=models.DateField(
                null=True, verbose_name="Aluno no período parcial a partir de"
            ),
        ),
    ]
