# Generated by Django 4.2.7 on 2023-11-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dados_comuns", "0109_alter_logsolicitacoesusuario_status_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("REQUISICAO_DE_ENTREGA", "Requisição de entrega"),
                    (
                        "ALTERACAO_REQUISICAO_ENTREGA",
                        "Alteração de requisição de entrega",
                    ),
                    ("GUIA_DE_REMESSA", "Guia de Remessa"),
                    ("CRONOGRAMA", "Assinatura do Cronograma"),
                    (
                        "SOLICITACAO_ALTERACAO_CRONOGRAMA",
                        "Solicitação de Alteração do Cronograma",
                    ),
                    ("ALTERACAO_CRONOGRAMA", "Alteração do Cronograma"),
                    ("LAYOUT_DE_EMBALAGENS", "Layout de Embalagens"),
                    ("DOCUMENTOS_DE_RECEBIMENTO", "Documentos de Recebimento"),
                ],
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
    ]
