# Generated by Django 4.2.7 on 2024-06-14 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(blank=True, max_length=2, verbose_name="tipo"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="descricao"
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Classificação",
            },
        ),
    ]
