# Generated by Django 4.2.7 on 2024-06-17 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cardapio", "0056_remove_controlesobras_escola_and_more"),
        ("escola", "0070_escola_acesso_desde"),
        ("produto", "0083_merge_20240410_1439"),
        ("desperdicio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleRestos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("peso_resto", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cardapio",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="cardapio"
                    ),
                ),
                (
                    "resto_predominante",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="resto_predominante"
                    ),
                ),
                (
                    "data_hora_medicao",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Data e hora da medição"
                    ),
                ),
                (
                    "quantidade_distribuida",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="escola.escola",
                    ),
                ),
                (
                    "tipo_alimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cardapio.tipoalimentacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle de Restos",
            },
        ),
        migrations.CreateModel(
            name="ImagemControleResto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("arquivo", models.FileField(upload_to="")),
                ("nome", models.CharField(blank=True, max_length=255)),
                (
                    "controle_resto",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desperdicio.controlerestos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Controle de Resto",
                "verbose_name_plural": "Imagens do Controle de Resto",
            },
        ),
        migrations.CreateModel(
            name="ControleSobras",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("peso_alimento", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "peso_recipiente",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("peso_sobra", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "data_medicao",
                    models.DateField(
                        default=None, null=True, verbose_name="Data da medição"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(blank=True, max_length=1, verbose_name="Período"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="escola.escola",
                    ),
                ),
                (
                    "tipo_alimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cardapio.tipoalimentacao",
                    ),
                ),
                (
                    "tipo_alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="produto.tipoalimento",
                    ),
                ),
                (
                    "tipo_recipiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="produto.tiporecipiente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle de Sobras",
            },
        ),
    ]
