# Generated by Django 4.2.7 on 2024-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desperdicio", "0002_controlerestos_imagemcontroleresto_controlesobras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlerestos",
            name="data_hora_medicao",
        ),
        migrations.AddField(
            model_name="controlerestos",
            name="data_medicao",
            field=models.DateField(
                default=None, null=True, verbose_name="Data da medição"
            ),
        ),
        migrations.AddField(
            model_name="controlerestos",
            name="periodo",
            field=models.CharField(blank=True, max_length=1, verbose_name="Período"),
        ),
    ]
