# Generated by Django 4.2.7 on 2024-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desperdicio", "0003_remove_controlerestos_data_hora_medicao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlerestos",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="controlesobras",
            name="especificar",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="especificar"
            ),
        ),
    ]
