# Generated by Django 4.2.7 on 2024-07-22 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("desperdicio", "0004_controlerestos_observacoes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlerestos",
            name="quantidade_distribuida",
        ),
    ]
