# Generated by Django 2.0.13 on 2019-07-10 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretoriaRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciais', models.CharField(blank=True, max_length=10, null=True, verbose_name='Iniciais')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Diretoria regional',
                'verbose_name_plural': 'Diretorias regionais',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nome')),
                ('codigo_eol', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL')),
                ('codigo_codae', models.CharField(max_length=10, unique=True, verbose_name='Código CODAE')),
                ('quantidade_alunos', models.PositiveSmallIntegerField(verbose_name='Quantidade de alunos')),
                ('cardapios', models.ManyToManyField(blank=True, to='cardapio.Cardapio')),
                ('diretoria_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas', to='escola.DiretoriaRegional')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='FaixaIdadeEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Idade escolar',
                'verbose_name_plural': 'Idades escolares',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Período escolar',
                'verbose_name_plural': 'Períodos escolares',
            },
        ),
        migrations.CreateModel(
            name='TipoGestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de gestão',
                'verbose_name_plural': 'Tipos de gestão',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidadeEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciais', models.CharField(blank=True, max_length=10, null=True, verbose_name='Iniciais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de unidade escolar',
                'verbose_name_plural': 'Tipos de unidade escolar',
            },
        ),
        migrations.AddField(
            model_name='escola',
            name='idades',
            field=models.ManyToManyField(blank=True, to='escola.FaixaIdadeEscolar'),
        ),
    ]
