# Generated by Django 2.0.13 on 2019-08-05 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='usuarios',
            field=models.ManyToManyField(related_name='escolas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diretoriaregional',
            name='usuarios',
            field=models.ManyToManyField(related_name='diretorias_regionais', to=settings.AUTH_USER_MODEL),
        ),
    ]
