# Generated by Django 2.0.13 on 2019-08-07 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20190805_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subprefeitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Subprefeitura',
                'verbose_name_plural': 'Subprefeituras',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_gestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipos_gestao', to='escola.TipoGestao'),
        ),
        migrations.AddField(
            model_name='lote',
            name='subprefeitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subprefeituras', to='escola.Subprefeitura'),
        ),
    ]
