# Generated by Django 2.0.13 on 2019-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20190710_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='codigo_codae',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código CODAE'),
        ),
    ]
