# Generated by Django 2.0.13 on 2019-08-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20190807_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='subprefeitura',
        ),
        migrations.AddField(
            model_name='subprefeitura',
            name='diretoria_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subprefeituras', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='subprefeitura',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subprefeituras', to='escola.Lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_gestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lotes', to='escola.TipoGestao'),
        ),
    ]
