# Generated by Django 2.0.13 on 2019-08-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0002_remove_terceirizada_lotes'),
        ('escola', '0004_auto_20190807_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='terceirizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lotes', to='terceirizada.Terceirizada'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to='escola.Lote'),
        ),
    ]
