# Generated by Django 2.0.13 on 2019-07-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_contato_endereco'),
        ('escola', '0004_escola_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='contato',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dados_comuns.Contato'),
            preserve_default=False,
        ),
    ]
