# Generated by Django 2.0.13 on 2019-07-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20190712_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretoriaregional',
            name='iniciais',
        ),
    ]
