# Generated by Django 2.0.13 on 2019-08-08 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20190807_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoriaregional',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='diretorias_regionais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subprefeitura',
            name='diretoria_regional',
        ),
        migrations.AddField(
            model_name='subprefeitura',
            name='diretoria_regional',
            field=models.ManyToManyField(blank=True, related_name='subprefeituras', to='escola.DiretoriaRegional'),
        ),
    ]
