# Generated by Django 2.0.13 on 2019-07-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_remove_diretoriaregional_iniciais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escola',
            old_name='periodos',
            new_name='periodos_escolares',
        ),
    ]
