# Generated by Django 2.0.13 on 2019-08-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_auto_20190808_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas', to='escola.Lote'),
        ),
    ]
