# Generated by Django 2.0.13 on 2019-08-16 11:21

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0008_auto_20190812_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='CODAE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CODAE',
                'verbose_name_plural': 'CODAE',
            },
        ),
    ]
