# Generated by Django 2.0.13 on 2019-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_auto_20190716_1657'),
        ('escola', '0009_auto_20190717_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='cardapios',
        ),
        migrations.AddField(
            model_name='tipounidadeescolar',
            name='cardapios',
            field=models.ManyToManyField(blank=True, to='cardapio.Cardapio'),
        ),
    ]
