# Generated by Django 2.0.13 on 2019-08-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_codae'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diretoriaregional',
            options={'ordering': ('nome',), 'verbose_name': 'Diretoria regional', 'verbose_name_plural': 'Diretorias regionais'},
        ),
        migrations.AlterModelOptions(
            name='escola',
            options={'ordering': ('codigo_eol',), 'verbose_name': 'Escola', 'verbose_name_plural': 'Escolas'},
        ),
        migrations.AlterModelOptions(
            name='faixaidadeescolar',
            options={'ordering': ('nome',), 'verbose_name': 'Idade escolar', 'verbose_name_plural': 'Idades escolares'},
        ),
        migrations.AlterModelOptions(
            name='subprefeitura',
            options={'ordering': ('nome',), 'verbose_name': 'Subprefeitura', 'verbose_name_plural': 'Subprefeituras'},
        ),
        migrations.AlterField(
            model_name='escola',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='escola.Lote'),
        ),
    ]
