# Generated by Django 2.0.13 on 2019-08-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_auto_20190822_1320'),
        ('escola', '0010_auto_20190822_1508'),
    ]

    operations = [
    ]
