# Generated by Django 2.0.13 on 2019-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_auto_20190723_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipounidadeescolar',
            name='cardapios',
            field=models.ManyToManyField(blank=True, related_name='tipos_unidade_escolar', to='cardapio.Cardapio'),
        ),
    ]
