# Generated by Django 2.0.13 on 2019-07-31 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_periodoescolar_tipos_alimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='usuarios',
            field=models.ManyToManyField(related_name='escolas', to=settings.AUTH_USER_MODEL),
        ),
    ]
