# Generated by Django 2.0.13 on 2019-07-31 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0014_auto_20190731_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoriaregional',
            name='usuarios',
            field=models.ManyToManyField(related_name='diretorias_regionais', to=settings.AUTH_USER_MODEL),
        ),
    ]
