# Generated by Django 2.2.6 on 2019-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='É Administrador por parte das Terceirizadas?'),
        ),
    ]
