# Generated by Django 2.0.13 on 2019-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricionista',
            name='crn_numero',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nutricionista crn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nome fantasia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='razao_social',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Razao social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='representante_contato',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Representante contato (email/tel)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='representante_legal',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Representante legal'),
            preserve_default=False,
        ),
    ]
