# Generated by Django 2.0.13 on 2019-09-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0002_auto_20190902_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='terceirizadas',
        ),
        migrations.AddField(
            model_name='contrato',
            name='terceirizada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='terceirizada.Terceirizada'),
            preserve_default=False,
        ),
    ]
