# Generated by Django 2.0.13 on 2019-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0003_auto_20190903_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceirizada',
            name='representante_contato',
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='representante_email',
            field=models.CharField(blank=True, max_length=160, verbose_name='Representante contato (email)'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='representante_telefone',
            field=models.CharField(blank=True, max_length=160, verbose_name='Representante contato (telefone)'),
        ),
    ]
