# Generated by Django 2.0.13 on 2019-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_auto_20190902_1147'),
        ('terceirizada', '0004_auto_20190903_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='contatos',
            field=models.ManyToManyField(blank=True, to='dados_comuns.Contato'),
        ),
    ]
