# Generated by Django 2.2.13 on 2020-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0004_auto_20201119_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceirizada',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='estado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='responsavel_cargo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Responsável cargo'),
        ),
        migrations.AlterField(
            model_name='terceirizada',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=160, verbose_name='Responsável contato (telefone)'),
        ),
    ]
