# Generated by Django 2.0.13 on 2019-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('terceirizada', '0005_nutricionista_contatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricionista',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
