# Generated by Django 2.2.6 on 2019-10-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0008_remove_terceirizada_vinculos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceirizada',
            name='endereco',
        ),
    ]
