# Generated by Django 2.2.13 on 2022-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0008_emailterceirizadapormodulo_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailterceirizadapormodulo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterUniqueTogether(
            name='emailterceirizadapormodulo',
            unique_together={('email', 'terceirizada', 'modulo')},
        ),
    ]
