# Generated by Django 2.2.6 on 2019-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0009_remove_terceirizada_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceirizada',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='terceirizada',
            name='endereco',
            field=models.CharField(blank=True, max_length=160, verbose_name='Endereco'),
        ),
    ]
