# Generated by Django 2.2.6 on 2019-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0010_auto_20191113_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceirizada',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
    ]
