# Generated by Django 2.2.13 on 2023-01-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0010_auto_20230106_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceirizada',
            name='tipo_empresa',
            field=models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('AGRICULTURA_FAMILIAR', 'Agricultura Familiar'), ('TERCEIRIZADA', 'Terceirizada')], default='TERCEIRIZADA', max_length=25),
        ),
    ]
