# Generated by Django 2.2.13 on 2023-01-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0011_terceirizada_tipo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='diretorias_regionais',
            field=models.ManyToManyField(blank=True, related_name='contratos_da_diretoria_regional', to='escola.DiretoriaRegional'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='lotes',
            field=models.ManyToManyField(blank=True, related_name='contratos_do_lote', to='escola.Lote'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='terceirizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='terceirizada.Terceirizada'),
        ),
    ]
