# Generated by Django 3.2.18 on 2023-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0013_auto_20230112_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ata_chamada_publica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No da Ata/Chamada Pública'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pregao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No do Pregão Eletrônico'),
        ),
    ]
