# Generated by Django 3.2.20 on 2023-09-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0014_auto_20230821_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='ata_chamada_publica',
            new_name='ata',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='pregao',
            new_name='pregao_chamada_publica',
        ),
    ]
