# Generated by Django 4.2.7 on 2024-04-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0019_alter_contrato_ata"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="eh_imr",
            field=models.BooleanField(default=False, verbose_name="É IMR?"),
        ),
    ]
