# Generated by Django 2.0.13 on 2019-05-27 16:24

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoCardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', model_utils.fields.StatusField(choices=[('DRE_A_VALIDAR', 'A validar pela DRE'), ('DRE_APROVADO', 'Aprovado pela DRE'), ('DRE_REPROVADO', 'Reprovado pela DRE'), ('CODAE_A_VALIDAR', 'A validar pela CODAE'), ('CODAE_APROVADO', 'Aprovado pela CODAE'), ('CODAE_REPROVADO', 'Reprovado pela CODAE'), ('TERCEIRIZADA_A_VISUALIZAR', 'Terceirizada a visualizar'), ('TERCEIRIZADA_A_VISUALIZADO', 'Terceirizada visualizado')], default='DRE_A_VALIDAR', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
