# Generated by Django 2.0.13 on 2019-05-22 22:36

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoCardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('motivo', models.TextField(blank=True, max_length=256, null=True, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', model_utils.fields.StatusField(choices=[('SALVO', 'Salvo'), ('A_VALIDAR', 'A validar'), ('CONFIRMADO', 'Confirmado'), ('A_VISUALIZAR', 'A visualizar'), ('A_APROVAR', 'A aprovar'), ('A_EDITAR', 'A editar'), ('NEGADO_PELA_CODAE', 'Negado pela CODAE'), ('NEGADO_PELA_COMPANHIA', 'Negado pela companhia'), ('VISUALIZADO', 'Visualizado')], default='SALVO', max_length=100, no_check_for_status=True)),
                ('nome_escola', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nome da escola...')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
