# Generated by Django 2.0.13 on 2019-07-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='periodos',
            field=models.ManyToManyField(blank=True, to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='tipos_alimentacao',
            field=models.ManyToManyField(blank=True, to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='cardapio_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_de', to='cardapio.Cardapio'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='cardapio_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_para', to='cardapio.Cardapio'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='tipo_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_de', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='tipo_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_para', to='cardapio.TipoAlimentacao'),
        ),
    ]
