# Generated by Django 2.0.13 on 2019-08-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes_periodo_escolar', to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='suspensao_alimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_periodo_escolar', to='cardapio.SuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='tipos_alimentacao',
            field=models.ManyToManyField(related_name='suspensoes_periodo_escolar', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='grupo_suspensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardapio.SuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.MotivoSuspensao'),
        ),
        migrations.AddField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='alteracao_cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_periodo_escolar', to='cardapio.AlteracaoCardapio'),
        ),
        migrations.AddField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_periodo_escolar', to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='tipos_alimentacao',
            field=models.ManyToManyField(related_name='substituicoes_periodo_escolar', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='grupo_suspensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantidades_por_periodo', to='cardapio.GrupoSuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='quantidadeporperiodosuspensaoalimentacao',
            name='tipos_alimentacao',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='cardapio_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_de', to='cardapio.Cardapio'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='cardapio_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardapio_para', to='cardapio.Cardapio'),
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
    ]
