# Generated by Django 2.0.13 on 2019-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_auto_20190710_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversaocardapio',
            name='status',
            field=models.IntegerField(choices=[(0, 'A validar pela DRE'), (1, 'Aprovado pela DRE'), (2, 'Reprovado pela DRE'), (3, 'A validar pela CODAE'), (4, 'Aprovado pela CODAE'), (5, 'Reprovado pela CODAE'), (6, 'Terceirizada a visualizar'), (7, 'Terceirizada visualizado')], default=0),
        ),
    ]
