# Generated by Django 2.0.13 on 2019-07-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0002_auto_20190712_1013'),
        ('cardapio', '0003_inversaocardapio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='edital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='terceirizada.Edital'),
            preserve_default=False,
        ),
    ]
