# Generated by Django 2.0.13 on 2019-08-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_auto_20190805_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensaoalimentacao',
            name='grupo_suspensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardapio.GrupoSuspensaoAlimentacao'),
        ),
    ]
