# Generated by Django 2.0.13 on 2019-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alteracaocardapio_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaocardapio',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gruposuspensaoalimentacao',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inversaocardapio',
            name='motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inversaocardapio',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivoalteracaocardapio',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivosuspensao',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suspensaoalimentacao',
            name='outro_motivo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Outro motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoalimentacao',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
