# Generated by Django 2.0.13 on 2019-07-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_cardapio_edital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensaoalimentacao',
            name='cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.Cardapio'),
        ),
    ]
