# Generated by Django 2.0.13 on 2019-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_auto_20190716_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensaoalimentacao',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cardápio inteiro'), (1, 'Período escolar'), (2, 'Tipo alimentação')]),
        ),
    ]
