# Generated by Django 2.0.13 on 2019-08-05 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cardapio', '0005_auto_20190805_1057'),
        ('cardapio', '0004_auto_20190805_1103'),
    ]

    operations = [
    ]
