# Generated by Django 2.0.13 on 2019-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_auto_20190913_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoalimentacao',
            name='substituicoes',
            field=models.ManyToManyField(to='cardapio.TipoAlimentacao'),
        ),
    ]
