# Generated by Django 2.0.13 on 2019-07-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_suspensaoalimentacao_escola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspensaoalimentacao',
            old_name='periodos',
            new_name='periodos_escolares',
        ),
    ]
