# Generated by Django 2.0.13 on 2019-07-26 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_auto_20190723_1614'),
        ('cardapio', '0010_motivoalteracaocardapio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituicaoAlimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qtd_alunos', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='alteracaocardapio',
            options={'verbose_name': 'Alteração de cardápio', 'verbose_name_plural': 'Alterações de cardápio'},
        ),
        migrations.RemoveField(
            model_name='alteracaocardapio',
            name='tipo_de',
        ),
        migrations.RemoveField(
            model_name='alteracaocardapio',
            name='tipo_para',
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='data_final',
            field=models.DateField(default=datetime.date(2019, 7, 26), verbose_name='Data final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='data_inicial',
            field=models.DateField(default=datetime.date(2019, 7, 26), verbose_name='Data inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.MotivoAlteracaoCardapio'),
        ),
        migrations.AddField(
            model_name='alteracaocardapio',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        # migrations.AddField(
        #     model_name='alteracaocardapio',
        #     name='status',
        #     field=models.IntegerField(choices=[(0, 'A validar pela DRE'), (1, 'Aprovado pela DRE'), (2, 'Reprovado pela DRE'), (3, 'A validar pela CODAE'), (4, 'Aprovado pela CODAE'), (5, 'Reprovado pela CODAE'), (6, 'Terceirizada a visualizar'), (7, 'Terceirizada visualizado')], default=0),
        # ),
        migrations.AddField(
            model_name='substituicaoalimentacao',
            name='alteracao_cardapio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='cardapio.AlteracaoCardapio'),
        ),
        migrations.AddField(
            model_name='substituicaoalimentacao',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='substituicaoalimentacao',
            name='tipos_alimentacao',
            field=models.ManyToManyField(related_name='tipos_alimento_substituidos', to='cardapio.TipoAlimentacao'),
        ),
    ]
