# Generated by Django 2.0.13 on 2019-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_auto_20190816_1653'),
        ('cardapio', '0010_merge_20190816_1421'),
    ]

    operations = [
    ]
