# Generated by Django 2.0.13 on 2019-07-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_auto_20190723_1614'),
        ('cardapio', '0011_auto_20190726_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubstituicaoAlimentacao',
            new_name='SubstituicoesAlimentacaoNoPeriodoEscolar',
        ),
    ]
