# Generated by Django 2.0.13 on 2019-08-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_auto_20190820_1136'),
        ('cardapio', '0012_auto_20190820_1108'),
    ]

    operations = [
    ]
