# Generated by Django 2.0.13 on 2019-07-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_auto_20190726_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substituicoesalimentacaonoperiodoescolar',
            options={'verbose_name': 'Substituições de alimentação no período', 'verbose_name_plural': 'Substituições de alimentação no período'},
        ),
        migrations.RemoveField(
            model_name='alteracaocardapio',
            name='descricao',
        ),
    ]
