# Generated by Django 2.0.13 on 2019-08-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0014_auto_20190820_1406'),
        ('cardapio', '0013_merge_20190820_1424'),
    ]

    operations = [
    ]
