# Generated by Django 2.0.13 on 2019-07-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0014_alteracaocardapio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='alteracao_cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicao_periodo_escolar', to='cardapio.AlteracaoCardapio'),
        ),
        migrations.AlterField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicao_periodo_escolar', to='escola.PeriodoEscolar'),
        ),
        migrations.AlterField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='tipos_alimentacao',
            field=models.ManyToManyField(related_name='substituicoes_periodo_escolar', to='cardapio.TipoAlimentacao'),
        ),
    ]
