# Generated by Django 2.0.13 on 2019-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cardapio', '0015_merge_20190820_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inversaocardapio',
            name='descricao',
        ),
        migrations.AddField(
            model_name='inversaocardapio',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        )
    ]
