# Generated by Django 2.0.13 on 2019-07-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0015_auto_20190729_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='alteracao_cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_periodo_escolar', to='cardapio.AlteracaoCardapio'),
        ),
        migrations.AlterField(
            model_name='substituicoesalimentacaonoperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_periodo_escolar', to='escola.PeriodoEscolar'),
        ),
    ]
