# Generated by Django 2.0.13 on 2019-08-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0016_auto_20190729_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversaocardapio',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
