# Generated by Django 2.0.13 on 2019-07-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0016_auto_20190729_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inversaocardapio',
            name='status',
        ),
    ]
