# Generated by Django 2.0.13 on 2019-08-21 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cardapio', '0016_auto_20190820_1644'),
        ('cardapio', '0016_auto_20190821_0741'),
    ]

    operations = [
    ]
