# Generated by Django 2.0.13 on 2019-07-31 12:43

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0017_remove_inversaocardapio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversaocardapio',
            name='status',
            field=django_xworkflows.models.StateField(max_length=23, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_APROVADO', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO'])),
        ),
    ]
