# Generated by Django 2.0.13 on 2019-08-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0018_inversaocardapio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='editais', to='terceirizada.Edital'),
        ),
    ]
