# Generated by Django 2.0.13 on 2019-08-02 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_auto_20190731_1027'),
        ('cardapio', '0019_auto_20190801_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoSuspensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de suspensão de alimentação',
                'verbose_name_plural': 'Motivo de suspensão de alimentação',
            },
        ),
        migrations.CreateModel(
            name='SuspensaoAlimentacaoNoPeriodoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qtd_alunos', models.PositiveSmallIntegerField(default=0)),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes_periodo_escolar', to='escola.PeriodoEscolar')),
            ],
            options={
                'verbose_name': 'Suspensão de alimentação no período',
                'verbose_name_plural': 'Suspensões de alimentação no período',
            },
        ),
        migrations.RemoveField(
            model_name='suspensaoalimentacao',
            name='cardapio',
        ),
        migrations.RemoveField(
            model_name='suspensaoalimentacao',
            name='periodos_escolares',
        ),
        migrations.RemoveField(
            model_name='suspensaoalimentacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='suspensaoalimentacao',
            name='tipos_alimentacao',
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='suspensao_alimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_periodo_escolar', to='cardapio.SuspensaoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacaonoperiodoescolar',
            name='tipos_alimentacao',
            field=models.ManyToManyField(related_name='suspensoes_periodo_escolar', to='cardapio.TipoAlimentacao'),
        ),
        migrations.AddField(
            model_name='suspensaoalimentacao',
            name='motivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.MotivoSuspensao'),
            preserve_default=False,
        ),
    ]
