# Generated by Django 2.0.13 on 2019-08-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0020_auto_20190802_1634'),
        ('cardapio', '0018_auto_20190802_1613'),
    ]

    operations = [
    ]
