# Generated by Django 4.2.7 on 2024-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicao_inicial", "0036_merge_20240206_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaparacorrigir",
            name="infantil_ou_fundamental",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("INFANTIL", "INFANTIL"),
                    ("FUNDAMENTAL", "FUNDAMENTAL"),
                ],
                default="N/A",
                max_length=11,
            ),
        ),
    ]
