# Generated by Django 4.2.7 on 2024-03-13 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicao_inicial", "0038_clausuladedesconto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empenho",
            name="tipo_reajuste",
        ),
    ]
