# Generated by Django 4.2.7 on 2024-04-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0046_dataintervaloalteracaocardapiocemei"),
        ("escola", "0069_logalunopordia"),
        ("medicao_inicial", "0041_alter_parametrizacaofinanceira_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="faixa_etaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametrizacoes_valores",
                to="escola.faixaetaria",
            ),
        ),
        migrations.AlterField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="tipo_alimentacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametrizacoes_valores",
                to="cardapio.tipoalimentacao",
            ),
        ),
    ]
