# Generated by Django 4.2.7 on 2024-04-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0019_alter_contrato_ata"),
        ("escola", "0069_logalunopordia"),
        (
            "medicao_inicial",
            "0042_parametrizacaofinanceiratabelavalor_faixa_etaria_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diasobremesadoce",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="diasobremesadoce",
            name="edital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="terceirizada.edital",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="diasobremesadoce",
            unique_together={("tipo_unidade", "data", "edital")},
        ),
    ]
