# Generated by Django 4.2.7 on 2024-05-21 13:43

import uuid

import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0069_logalunopordia"),
        ("medicao_inicial", "0043_alter_diasobremesadoce_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioFinanceiro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ano", models.CharField(max_length=4, verbose_name="Ano")),
                ("mes", models.CharField(max_length=2, verbose_name="Mes")),
                (
                    "status",
                    django_xworkflows.models.StateField(
                        max_length=16,
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="EM_ANALISE",
                            name="RelatorioFinanceiroMedicaoInicialWorkflow",
                            states=["EM_ANALISE"],
                        ),
                    ),
                ),
                (
                    "grupo_unidade_escolar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_financeiros",
                        to="escola.grupounidadeescolar",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_financeiros",
                        to="escola.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Financeiro",
                "verbose_name_plural": "Relatórios Financeiros",
                "ordering": ["-alterado_em"],
                "unique_together": {("grupo_unidade_escolar", "lote", "mes", "ano")},
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="relatorio_financeiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_medicao_inicial",
                to="medicao_inicial.relatoriofinanceiro",
            ),
        ),
    ]
