# Generated by Django 2.0.13 on 2019-05-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymenu',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.SchoolAge'),
        ),
    ]
