# Generated by Django 2.0.13 on 2019-05-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.SchoolAge'),
        ),
        migrations.AddField(
            model_name='meal',
            name='grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.SchoolGroup'),
        ),
        migrations.AddField(
            model_name='meal',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.ManagementType'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal',
            field=models.ManyToManyField(to='food.Food'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.MealType'),
        ),
        migrations.AddField(
            model_name='meal',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.SchoolUnitType'),
        ),
    ]
