# Generated by Django 2.0.13 on 2019-05-16 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
        ('food', '0002_auto_20190516_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymenu',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daymenu',
            name='grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.SchoolGroup'),
        ),
        migrations.AddField(
            model_name='daymenu',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.ManagementType'),
        ),
        migrations.AddField(
            model_name='daymenu',
            name='meals',
            field=models.ManyToManyField(to='food.Meal'),
        ),
        migrations.AddField(
            model_name='daymenu',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.MenuStatus'),
        ),
        migrations.AddField(
            model_name='daymenu',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.SchoolUnitType'),
        ),
    ]
