# Generated by Django 2.0.13 on 2019-05-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190517_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_title',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='food.MealType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(default=1, max_length=120, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
