# Generated by Django 2.0.13 on 2019-05-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20190517_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='food.Food'),
        ),
    ]
