# Generated by Django 2.0.13 on 2019-05-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190517_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='title',
        ),
    ]
