# Generated by Django 2.0.13 on 2019-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_meal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meal Titles'},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
