# Generated by Django 2.0.13 on 2019-05-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20190517_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
