# Generated by Django 2.2.13 on 2020-10-05 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dieta_especial', '0015_tipocontagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0018_auto_20200924_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('frequencia', models.IntegerField(null=True)),
                ('lanche_4h', models.IntegerField(null=True)),
                ('lanche_5h', models.IntegerField(null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola_periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.EscolaPeriodoEscolar')),
                ('tipo_dieta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dieta_especial.ClassificacaoDieta')),
            ],
            options={
                'abstract': False,
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.Logs, models.Model),
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_oferta', models.IntegerField(null=True)),
                ('ref_repet', models.IntegerField(null=True)),
                ('sob_oferta', models.IntegerField(null=True)),
                ('sob_repet', models.IntegerField(null=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='lancamento_inicial.LancamentoDiario')),
            ],
        ),
    ]
