# Generated by Django 2.2.13 on 2020-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento_inicial', '0003_lancamentodiario_eh_dia_de_sobremesa_doce'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentodiario',
            name='merenda_seca',
            field=models.IntegerField(null=True),
        ),
    ]
