# Generated by Django 2.0.13 on 2019-08-26 18:04

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('telefone2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSolicitacoesUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('status_evento', models.PositiveSmallIntegerField(choices=[(0, 'Solicitação Realizada'), (1, 'CODAE aprovou'), (2, 'Terceirizada tomou ciência'), (3, 'Terceirizada recusou'), (4, 'CODAE reprovou'), (5, 'CODAE pediu revisão'), (6, 'DRE revisou'), (7, 'DRE aprovou'), (8, 'DRE pediu revisão'), (9, 'DRE reprovou'), (10, 'Escola revisou'), (11, 'Escola cancelou')])),
                ('solicitacao_tipo', models.PositiveSmallIntegerField(choices=[(0, 'Solicitação de kit lanche avulsa'), (1, 'Alteração de cardápio'), (2, 'Suspensão de cardápio'), (3, 'Inversão de cardápio'), (4, 'Inclusão de alimentação normal'), (5, 'Inclusão de alimentação contínua'), (6, 'Solicitação de kit lanche unificada')])),
                ('uuid_original', models.UUIDField()),
            ],
            options={
                'ordering': ('criado_em',),
            },
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Alteração de cardápio'), (1, 'Inclusão de alimentação'), (2, 'Inclusão de alimentação contínua'), (3, 'Suspensão de alimentação'), (4, 'Solicitação de kit lanche avulsa'), (5, 'Solicitação de kit lanche unificada'), (6, 'Inversão de cardápio')], unique=True)),
                ('assunto', models.CharField(blank=True, max_length=256, null=True, verbose_name='Assunto')),
                ('template_html', models.TextField(blank=True, null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Template de mensagem',
            },
        ),
    ]
