# Generated by Django 2.0.13 on 2019-09-02 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_logsolicitacoesusuario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsolicitacoesusuario',
            options={},
        ),
        migrations.AlterField(
            model_name='contato',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='assunto',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Assunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='template_html',
            field=models.TextField(blank=True, default='', verbose_name='Template'),
            preserve_default=False,
        ),
    ]
