# Generated by Django 2.0.13 on 2019-09-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0004_auto_20190911_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsolicitacoesusuario',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
    ]
