# Generated by Django 2.0.13 on 2019-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0005_logsolicitacoesusuario_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Justificativa'),
        ),
    ]
