# Generated by Django 2.2.8 on 2020-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0006_auto_20200203_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField()),
                ('fim', models.IntegerField()),
            ],
        ),
    ]
