# Generated by Django 2.2.6 on 2019-10-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_remove_escola_endereco'),
        ('terceirizada', '0009_remove_terceirizada_endereco'),
        ('dados_comuns', '0007_auto_20190919_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
