# Generated by Django 2.2.6 on 2019-11-14 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0008_delete_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
