# Generated by Django 2.2.6 on 2019-12-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0009_auto_20191114_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='solicitacao_tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação de kit lanche avulsa'), (1, 'Alteração de cardápio'), (2, 'Suspensão de cardápio'), (3, 'Inversão de cardápio'), (4, 'Inclusão de alimentação normal'), (5, 'Inclusão de alimentação contínua'), (6, 'Dieta Especial'), (7, 'Solicitação de kit lanche unificada')]),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Alteração de cardápio'), (1, 'Inclusão de alimentação'), (2, 'Inclusão de alimentação contínua'), (3, 'Suspensão de alimentação'), (4, 'Solicitação de kit lanche avulsa'), (5, 'Solicitação de kit lanche unificada'), (6, 'Inversão de cardápio'), (7, 'Dieta Especial')], unique=True),
        ),
    ]
