# Generated by Django 2.2.10 on 2020-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0009_auto_20200423_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='solicitacao_tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação de kit lanche avulsa'), (1, 'Alteração de cardápio'), (2, 'Suspensão de cardápio'), (3, 'Inversão de cardápio'), (4, 'Inclusão de alimentação normal'), (5, 'Inclusão de alimentação da CEI'), (6, 'Suspensão de alimentação da CEI'), (7, 'Inclusão de alimentação contínua'), (8, 'Dieta Especial'), (9, 'Solicitação de kit lanche unificada'), (10, 'Homologação de Produto')]),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Alteração de cardápio'), (1, 'Inclusão de alimentação'), (2, 'Inclusão de alimentação contínua'), (3, 'Suspensão de alimentação'), (4, 'Solicitação de kit lanche avulsa'), (5, 'Solicitação de kit lanche unificada'), (6, 'Inversão de cardápio'), (7, 'Dieta Especial'), (8, 'Homologação de Produto')], unique=True),
        ),
    ]
