# Generated by Django 2.2.8 on 2020-04-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0010_categoriaperguntafrequente_uuid'),
        ('dados_comuns', '0010_auto_20200423_1535'),
    ]

    operations = [
    ]
