# Generated by Django 2.2.10 on 2020-06-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0014_anexologsolicitacoesusuario'),
        ('dados_comuns', '0014_auto_20200618_1042'),
    ]

    operations = [
    ]
