# Generated by Django 2.2.10 on 2020-06-19 19:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0016_auto_20200619_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexologsolicitacoesusuario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
