# Generated by Django 2.2.13 on 2021-01-11 10:34

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0025_auto_20201219_0530'),
    ]

    operations = [
        UnaccentExtension()
    ]
