# Generated by Django 2.2.13 on 2021-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0036_auto_20210821_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='nome',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nome'),
        ),
    ]
