# Generated by Django 2.2.13 on 2021-10-25 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0037_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
