# Generated by Django 2.2.13 on 2021-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0037_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação Realizada'), (1, 'CODAE autorizou'), (2, 'Terceirizada tomou ciência'), (3, 'Terceirizada recusou'), (4, 'CODAE negou'), (5, 'CODAE pediu revisão'), (6, 'DRE revisou'), (7, 'DRE validou'), (8, 'DRE pediu revisão'), (9, 'DRE não validou'), (10, 'Escola revisou'), (13, 'Escola cancelou'), (14, 'DRE cancelou'), (11, 'Questionamento pela CODAE'), (12, 'Terceirizada respondeu questionamento'), (15, 'Escola solicitou inativação'), (16, 'CODAE autorizou inativação'), (17, 'CODAE negou inativação'), (18, 'Terceirizada tomou ciência da inativação'), (19, 'Cancelada por atingir data de término'), (20, 'Pendente homologação da CODAE'), (21, 'CODAE homologou'), (22, 'CODAE não homologou'), (23, 'CODAE pediu análise sensorial'), (24, 'Terceirizada cancelou homologação'), (29, 'Homologação inativa'), (30, 'Terceirizada cancelou solicitação de homologação de produto'), (25, 'CODAE suspendeu o produto'), (26, 'Escola/Nutricionista reclamou do produto'), (27, 'CODAE pediu análise da reclamação'), (28, 'CODAE autorizou reclamação'), (37, 'CODAE recusou reclamação'), (38, 'CODAE questionou terceirizada sobre reclamação'), (33, 'CODAE questionou U.E. sobre reclamação'), (39, 'CODAE respondeu ao reclamante da reclamação'), (36, 'CODAE questionou nutrisupervisor sobre reclamação'), (31, 'Terceirizada respondeu a reclamação'), (34, 'U.E. respondeu a reclamação'), (35, 'Nutrisupervisor respondeu a reclamação'), (32, 'Terceirizada respondeu a análise'), (41, 'Papa enviou a requisição'), (42, 'Dilog Enviou a requisição'), (43, 'Distribuidor confirmou requisição'), (44, 'Distribuidor pede alteração da requisição'), (45, 'Papa cancelou a requisição'), (46, 'Papa aguarda confirmação do cancelamento da solicitação'), (47, 'Dilog Aceita Alteração'), (48, 'Dilog Nega Alteração'), (49, 'Cancelamento por alteração de unidade educacional'), (50, 'Cancelamento para aluno não matriculado na rede municipal')]),
        ),
    ]
