# Generated by Django 2.2.13 on 2021-10-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0038_auto_20211019_1431'),
        ('dados_comuns', '0041_auto_20211025_2200'),
    ]

    operations = [
    ]
