# Generated by Django 2.2.13 on 2021-10-27 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0042_merge_20211027_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
