# Generated by Django 2.2.13 on 2021-10-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0042_merge_20211027_0129'),
        ('dados_comuns', '0043_auto_20211027_1146'),
    ]

    operations = [
    ]
