# Generated by Django 2.2.13 on 2021-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0044_merge_20211028_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='solicitacao_tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação de kit lanche avulsa'), (1, 'Alteração do tipo de alimentação'), (2, 'Suspensão de cardápio'), (3, 'Inversão de cardápio'), (4, 'Inclusão de alimentação normal'), (5, 'Inclusão de alimentação da CEI'), (6, 'Suspensão de alimentação da CEI'), (7, 'Inclusão de alimentação contínua'), (8, 'Dieta Especial'), (9, 'Solicitação de kit lanche unificada'), (10, 'Homologação de Produto'), (11, 'Reclamação de Produto'), (33, 'Responde Análise Sensorial'), (12, 'Solicitação de remessa'), (13, 'Solicitação de Ateração de requisição'), (14, 'Abastecimento de guia de remessa')]),
        ),
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação Realizada'), (1, 'CODAE autorizou'), (2, 'Terceirizada tomou ciência'), (3, 'Terceirizada recusou'), (4, 'CODAE negou'), (5, 'CODAE pediu revisão'), (6, 'DRE revisou'), (7, 'DRE validou'), (8, 'DRE pediu revisão'), (9, 'DRE não validou'), (10, 'Escola revisou'), (13, 'Escola cancelou'), (14, 'CODAE negou cancelamento'), (15, 'DRE cancelou'), (11, 'Questionamento pela CODAE'), (12, 'Terceirizada respondeu questionamento'), (16, 'Escola solicitou inativação'), (17, 'CODAE autorizou inativação'), (18, 'CODAE negou inativação'), (19, 'Terceirizada tomou ciência da inativação'), (20, 'Cancelada por atingir data de término'), (21, 'Pendente homologação da CODAE'), (22, 'CODAE homologou'), (23, 'CODAE não homologou'), (24, 'CODAE pediu análise sensorial'), (25, 'Terceirizada cancelou homologação'), (30, 'Homologação inativa'), (31, 'Terceirizada cancelou solicitação de homologação de produto'), (26, 'CODAE suspendeu o produto'), (27, 'Escola/Nutricionista reclamou do produto'), (28, 'CODAE pediu análise da reclamação'), (29, 'CODAE autorizou reclamação'), (38, 'CODAE recusou reclamação'), (39, 'CODAE questionou terceirizada sobre reclamação'), (34, 'CODAE questionou U.E. sobre reclamação'), (40, 'CODAE respondeu ao reclamante da reclamação'), (37, 'CODAE questionou nutrisupervisor sobre reclamação'), (32, 'Terceirizada respondeu a reclamação'), (35, 'U.E. respondeu a reclamação'), (36, 'Nutrisupervisor respondeu a reclamação'), (33, 'Terceirizada respondeu a análise'), (42, 'Papa enviou a requisição'), (43, 'Dilog Enviou a requisição'), (44, 'Distribuidor confirmou requisição'), (45, 'Distribuidor pede alteração da requisição'), (46, 'Papa cancelou a requisição'), (47, 'Papa aguarda confirmação do cancelamento da solicitação'), (48, 'Dilog Aceita Alteração'), (49, 'Dilog Nega Alteração'), (50, 'Cancelamento por alteração de unidade educacional'), (51, 'Cancelamento para aluno não matriculado na rede municipal')]),
        ),
    ]
