# Generated by Django 2.2.13 on 2021-12-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0045_auto_20211122_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('ALERTA', 'Alerta'), ('AVISO', 'Aviso'), ('PENDENCIA', 'PENDENCIA')], default='AVISO', max_length=15, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('REQUISICAO_DE_ENTREGA', 'Requisição de entrega'), ('ALTERACAO_REQUISICAO_ENTREGA', 'Alteração de requisição de entrega'), ('GUIA_DE_REMESSA', 'Guia de Remessa')], max_length=30, verbose_name='Categoria')),
                ('titulo', models.CharField(blank=True, default='', max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', max_length=1000, verbose_name='Descrição')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('lido', models.BooleanField(default=False, verbose_name='Foi Lido?')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Foi resolvido?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
