# Generated by Django 2.2.13 on 2021-12-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0046_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('ALERTA', 'Alerta'), ('AVISO', 'Aviso'), ('PENDENCIA', 'Pendência')], default='AVISO', max_length=15, verbose_name='Tipo'),
        ),
    ]
