# Generated by Django 2.2.13 on 2021-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0047_auto_20211203_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Link'),
        ),
    ]
