# Generated by Django 2.2.13 on 2021-12-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0043_auto_20211020_1414'),
        ('dados_comuns', '0049_auto_20211209_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_da_requisicao', to='logistica.SolicitacaoRemessa'),
        ),
    ]
