# Generated by Django 2.2.13 on 2022-03-23 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0053_auto_20220225_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralDeDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identificador', models.CharField(default='', max_length=200, verbose_name='Nome do arquivo')),
                ('arquivo', models.FileField(blank=True, upload_to='', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='EM_PROCESSAMENTO', max_length=20, verbose_name='status')),
                ('msg_erro', models.CharField(blank=True, max_length=300, verbose_name='Mensagem erro')),
                ('visto', models.BooleanField(default=False, verbose_name='Foi visto?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Central de Download',
                'verbose_name_plural': 'Central de Downloads',
            },
        ),
    ]
