# Generated by Django 2.2.13 on 2022-05-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0056_auto_20220421_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsolicitacoesusuario',
            options={'ordering': ('-criado_em',)},
        ),
    ]
