# Generated by Django 2.2.13 on 2023-01-06 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0065_solicitacaoaberta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoaberta',
            name='datetime_ultimo_acesso',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
