# Generated by Django 3.2.16 on 2023-02-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0069_auto_20230203_1228'),
        ('dados_comuns', '0069_auto_20230205_1805'),
    ]

    operations = [
    ]
