# Generated by Django 3.2.16 on 2023-02-09 09:26

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0072_auto_20230208_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=21, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='CronogramaWorkflow', states=['RASCUNHO', 'ENVIADO_AO_FORNECEDOR', 'ALTERACAO_CODAE', 'APROVADO', 'REPROVADO', 'ALTERACAO_FORNECEDOR', 'VALIDADO_FORNECEDOR', 'SOLICITADO_ALTERACAO', 'ASSINADO_CRONOGRAMA'])),
        ),
    ]
