# Generated by Django 3.2.16 on 2023-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0073_alter_fluxocronograma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='solicitacao_tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação de kit lanche avulsa'), (1, 'Alteração do tipo de alimentação'), (2, 'Suspensão de cardápio'), (3, 'Inversão de cardápio'), (4, 'Inclusão de alimentação normal'), (5, 'Inclusão de alimentação da CEI'), (6, 'Suspensão de alimentação da CEI'), (7, 'Inclusão de alimentação contínua'), (8, 'Dieta Especial'), (9, 'Solicitação de kit lanche unificada'), (10, 'Homologação de Produto'), (11, 'Reclamação de Produto'), (35, 'Responde Análise Sensorial'), (12, 'Solicitação de remessa'), (13, 'Solicitação de Ateração de requisição'), (14, 'Abastecimento de guia de remessa'), (15, 'Solicitação de medição inicial'), (16, 'Inclusão de Alimentação CEMEI'), (17, 'Solicitação de kit lanche CEMEI'), (18, 'Cronograma')]),
        ),
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação Realizada'), (1, 'CODAE autorizou'), (2, 'Terceirizada tomou ciência'), (3, 'Terceirizada recusou'), (4, 'CODAE negou'), (5, 'CODAE Atualizou o protocolo'), (6, 'CODAE pediu revisão'), (7, 'DRE revisou'), (8, 'DRE validou'), (9, 'DRE pediu revisão'), (10, 'DRE não validou'), (11, 'Escola revisou'), (14, 'Escola cancelou'), (15, 'CODAE negou cancelamento'), (16, 'DRE cancelou'), (12, 'Questionamento pela CODAE'), (13, 'Terceirizada respondeu questionamento'), (17, 'Escola solicitou cancelamento'), (18, 'CODAE autorizou cancelamento'), (19, 'CODAE negou cancelamento'), (20, 'Terceirizada tomou ciência do cancelamento'), (21, 'Cancelada por atingir data de término'), (22, 'Pendente homologação da CODAE'), (23, 'CODAE homologou'), (24, 'CODAE não homologou'), (25, 'CODAE pediu análise sensorial'), (26, 'CODAE cancelou análise sensorial'), (27, 'Terceirizada cancelou homologação'), (32, 'Homologação inativa'), (33, 'Terceirizada cancelou solicitação de homologação de produto'), (28, 'CODAE suspendeu o produto'), (29, 'Escola/Nutricionista reclamou do produto'), (30, 'CODAE pediu análise da reclamação'), (31, 'CODAE autorizou reclamação'), (40, 'CODAE recusou reclamação'), (41, 'CODAE questionou terceirizada sobre reclamação'), (36, 'CODAE questionou U.E. sobre reclamação'), (42, 'CODAE respondeu ao reclamante da reclamação'), (39, 'CODAE questionou nutrisupervisor sobre reclamação'), (34, 'Terceirizada respondeu a reclamação'), (37, 'U.E. respondeu a reclamação'), (38, 'Nutrisupervisor respondeu a reclamação'), (35, 'Terceirizada respondeu a análise'), (44, 'Papa enviou a requisição'), (45, 'Dilog Enviou a requisição'), (46, 'Distribuidor confirmou requisição'), (47, 'Distribuidor pede alteração da requisição'), (48, 'Papa cancelou a requisição'), (49, 'Papa aguarda confirmação do cancelamento da solicitação'), (50, 'Distribuidor confirmou cancelamento e Papa cancelou a requisição'), (51, 'Dilog Aceita Alteração'), (52, 'Dilog Nega Alteração'), (53, 'Cancelamento por alteração de unidade educacional'), (54, 'Cancelamento para aluno não matriculado na rede municipal'), (55, 'Em aberto para preenchimento pela UE'), (56, 'Informação encerrada pela CODAE'), (57, 'Cronograma Criado'), (58, 'Enviado ao Fornecedor'), (59, 'Assinado Fornecedor'), (60, 'Alteração Fornecedor'), (61, 'Suspenso em alguns editais'), (62, 'Ativo em alguns editais'), (63, 'Assinado Cronograma')]),
        ),
    ]
