# Generated by Django 3.2.16 on 2023-02-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0075_alter_logsolicitacoesusuario_status_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FluxoAlteracaoCronograma',
        ),
        migrations.DeleteModel(
            name='FluxoCronograma',
        ),
    ]
