# Generated by Django 3.2.18 on 2023-06-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0090_alter_logsolicitacoesusuario_solicitacao_tipo'),
        ('dados_comuns', '0090_alter_logsolicitacoesusuario_status_evento'),
    ]

    operations = [
    ]
