# Generated by Django 3.2.18 on 2023-09-18 15:27

from django.db import migrations, models

from sme_terceirizadas.dados_comuns.models import Notificacao


def atualizar_valores(apps, schema_editor):
    categoria_atual = Notificacao.CATEGORIA_NOTIFICACAO_ALTERACAO_CRONOGRAMA
    nova_categoria = Notificacao.CATEGORIA_NOTIFICACAO_SOLICITACAO_ALTERACAO_CRONOGRAMA

    for notificacao in Notificacao.objects.filter(categoria=categoria_atual):
        notificacao.categoria = nova_categoria
        notificacao.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dados_comuns', '0097_alter_notificacao_categoria'),
    ]

    operations = [
        migrations.RunPython(atualizar_valores),
    ]
