# Generated by Django 3.2.20 on 2023-09-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0097_auto_20230919_1647'),
        ('dados_comuns', '0099_alter_notificacao_categoria'),
    ]

    operations = [
    ]
