# Generated by Django 4.1.12 on 2023-10-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0103_alter_logsolicitacoesusuario_solicitacao_tipo_and_more'),
        ('dados_comuns', '0103_alter_logsolicitacoesusuario_status_evento'),
    ]

    operations = [
    ]
