# Generated by Django 4.1.12 on 2023-11-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0106_alter_notificacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('REQUISICAO_DE_ENTREGA', 'Requisição de entrega'), ('ALTERACAO_REQUISICAO_ENTREGA', 'Alteração de requisição de entrega'), ('GUIA_DE_REMESSA', 'Guia de Remessa'), ('CRONOGRAMA', 'Assinatura do Cronograma'), ('SOLICITACAO_ALTERACAO_CRONOGRAMA', 'Solicitação de Alteração do Cronograma'), ('ALTERACAO_CRONOGRAMA', 'Alteração do Cronograma'), ('LAYOUT_DE_EMBALAGENS', 'Layout de Embalagens')], max_length=50, verbose_name='Categoria'),
        ),
    ]
