# Generated by Django 4.2.7 on 2023-11-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0110_alter_logsolicitacoesusuario_solicitacao_tipo'),
        ('dados_comuns', '0110_alter_notificacao_categoria'),
    ]

    operations = [
    ]
