# Generated by Django 2.2.6 on 2019-12-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceirizada', '0001_initial'),
        ('kit_lanche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0002_auto_20191205_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='diretoria_regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheunificada_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_escolas',
            field=models.ManyToManyField(blank=True, editable=False, related_name='kit_lanche_solicitacaokitlancheunificada_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheunificada_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheunificada_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='solicitacao_kit_lanche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kit_lanche.SolicitacaoKitLanche'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_kit_lanche_avulsa', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheavulsa_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheavulsa_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheavulsa_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheavulsa_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='solicitacao_kit_lanche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kit_lanche.SolicitacaoKitLanche'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlanche',
            name='kits',
            field=models.ManyToManyField(blank=True, to='kit_lanche.KitLanche'),
        ),
        migrations.AddField(
            model_name='kitlanche',
            name='itens',
            field=models.ManyToManyField(to='kit_lanche.ItemKitLanche'),
        ),
        migrations.AddField(
            model_name='escolaquantidade',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='escolaquantidade',
            name='kits',
            field=models.ManyToManyField(blank=True, to='kit_lanche.KitLanche'),
        ),
        migrations.AddField(
            model_name='escolaquantidade',
            name='solicitacao_unificada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolas_quantidades', to='kit_lanche.SolicitacaoKitLancheUnificada'),
        ),
    ]
