# Generated by Django 2.0.13 on 2019-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0003_auto_20190829_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemkitlanche',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitlanche',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivosolicitacaounificada',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaokitlanche',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaokitlanche',
            name='motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='outro_motivo',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
