# Generated by Django 2.2.8 on 2020-03-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terceirizada', '0003_auto_20191213_1339'),
        ('escola', '0015_auto_20200313_1521'),
        ('kit_lanche', '0005_auto_20200102_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoKitLancheCEIAvulsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('foi_solicitado_fora_do_prazo', models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?')),
                ('status', django_xworkflows.models.StateField(max_length=37, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_VALIDADO', 'DRE_PEDIU_ESCOLA_REVISAR', 'DRE_NAO_VALIDOU_PEDIDO_ESCOLA', 'CODAE_AUTORIZADO', 'CODAE_QUESTIONADO', 'CODAE_NEGOU_PEDIDO', 'TERCEIRIZADA_RESPONDEU_QUESTIONAMENTO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'CANCELADO_AUTOMATICAMENTE']))),
                ('local', models.CharField(max_length=160)),
                ('alunos_com_dieta_especial_participantes', models.ManyToManyField(to='escola.Aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_kit_lanche_cei_avulsa', to='escola.Escola')),
                ('rastro_dre', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheceiavulsa_rastro_dre', to='escola.DiretoriaRegional')),
                ('rastro_escola', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheceiavulsa_rastro_escola', to='escola.Escola')),
                ('rastro_lote', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheceiavulsa_rastro_lote', to='escola.Lote')),
                ('rastro_terceirizada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_lanche_solicitacaokitlancheceiavulsa_rastro_terceirizada', to='terceirizada.Terceirizada')),
                ('solicitacao_kit_lanche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kit_lanche.SolicitacaoKitLanche')),
            ],
            options={
                'verbose_name': 'Solicitação de kit lanche CEI avulsa',
                'verbose_name_plural': 'Solicitações de kit lanche CEI avulsa',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('kit_lanche_cei_avulsa'), django_xworkflows.models.BaseWorkflowEnabled, sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, sme_terceirizadas.dados_comuns.behaviors.TemPrioridade, sme_terceirizadas.dados_comuns.behaviors.Logs, models.Model),
        ),
        migrations.CreateModel(
            name='FaixaEtariaSolicitacaoKitLancheCEIAvulsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.FaixaEtaria')),
                ('solicitacao_kit_lanche_avulsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_etarias', to='kit_lanche.SolicitacaoKitLancheCEIAvulsa')),
            ],
            options={
                'verbose_name': 'Faixa Etária de solicitação de kit lanche CEI avulsa',
                'verbose_name_plural': 'Faixas Etárias de solicitação de kit lanche CEI avulsa',
            },
        ),
    ]
