# Generated by Django 2.0.13 on 2019-09-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0006_auto_20190912_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaokitlancheunificada',
            name='motivo',
        ),
        migrations.DeleteModel(
            name='MotivoSolicitacaoUnificada',
        ),
    ]
