# Generated by Django 2.0.13 on 2019-09-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0008_auto_20190913_1037'),
        ('kit_lanche', '0007_auto_20190912_1734'),
    ]

    operations = [
    ]
