# Generated by Django 2.0.13 on 2019-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0009_merge_20190913_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemkitlanche',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='kitlanche',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
