# Generated by Django 2.2.13 on 2021-11-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0010_solicitacaokitlancheavulsa_alunos_com_dieta_especial_participantes'),
        ('kit_lanche', '0010_auto_20211110_2023'),
    ]

    operations = [
    ]
