# Generated by Django 2.2.13 on 2022-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0011_merge_20211130_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaokitlancheavulsa',
            name='quantidade_alunos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
