# Generated by Django 2.2.13 on 2022-07-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0012_auto_20220714_0817'),
        ('paineis_consolidados', '0020_solicitacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaokitlancheavulsa',
            name='quantidade_alunos',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
