# Generated by Django 2.2.6 on 2019-10-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0012_auto_20191022_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_escolas',
            field=models.ManyToManyField(blank=True, editable=False, related_name='kit_lanche_solicitacaokitlancheunificada_rastro_escola', to='escola.Escola'),
        ),
    ]
