# Generated by Django 2.2.6 on 2019-11-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0013_auto_20191022_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaokitlancheunificada',
            name='quantidade_max_alunos_por_escola',
        ),
    ]
