# Generated by Django 2.2.6 on 2019-12-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0014_remove_solicitacaokitlancheunificada_quantidade_max_alunos_por_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='solicitacao_fora_do_prazo',
            field=models.BooleanField(default=False, verbose_name='Solicitação está fora do prazo?'),
        ),
    ]
