# Generated by Django 2.2.13 on 2022-11-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0014_faixasquantidadeskitlancheceidacemei_solicitacaokitlancheceidacemei_solicitacaokitlanchecemei_solici'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitlanche',
            options={'ordering': ('nome',), 'verbose_name': 'Kit lanche', 'verbose_name_plural': 'Kit lanches'},
        ),
    ]
