# Generated by Django 2.2.13 on 2022-11-25 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0015_auto_20221123_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixaetariasolicitacaokitlancheceiavulsa',
            name='matriculados_quando_criado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='faixasquantidadeskitlancheceidacemei',
            name='matriculados_quando_criado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheemeidacemei',
            name='matriculados_quando_criado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
