# Generated by Django 2.2.6 on 2019-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0016_auto_20191205_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='observacao_questionamento_codae',
            field=models.TextField(blank=True, verbose_name='Observação sobre o questionamento da CODAE'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='observacao_questionamento_terceirizada',
            field=models.TextField(blank=True, verbose_name='Observação sobre o questionamento da Terceirizada'),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='resposta_questionamento',
            field=models.BooleanField(default=False, verbose_name='Resposta do Questionamento'),
        ),
    ]
