# Generated by Django 3.2.18 on 2023-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0017_auto_20230120_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='evento',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheceiavulsa',
            name='evento',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='solicitacaokitlanchecemei',
            name='evento',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
