# Generated by Django 2.2.6 on 2019-12-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0017_auto_20191205_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaokitlancheavulsa',
            name='observacao_questionamento_codae',
        ),
        migrations.RemoveField(
            model_name='solicitacaokitlancheavulsa',
            name='observacao_questionamento_terceirizada',
        ),
        migrations.RemoveField(
            model_name='solicitacaokitlancheavulsa',
            name='resposta_questionamento',
        ),
        migrations.RemoveField(
            model_name='solicitacaokitlancheavulsa',
            name='solicitacao_fora_do_prazo',
        ),
        migrations.AddField(
            model_name='solicitacaokitlancheavulsa',
            name='foi_solicitado_fora_do_prazo',
            field=models.BooleanField(default=False, verbose_name='Solicitação foi criada em cima da hora (5 dias úteis ou menos)?'),
        ),
    ]
