# Generated by Django 3.2.18 on 2023-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0018_auto_20230920_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaokitlanchecemei',
            name='evento',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
