# Generated by Django 4.1.12 on 2023-10-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0015_auto_20230925_1221'),
        ('escola', '0062_diasuspensaoatividades'),
        ('kit_lanche', '0019_solicitacaokitlancheunificada_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheavulsa',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheceiavulsa',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheceiavulsa',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheceiavulsa',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheceiavulsa',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlanchecemei',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlanchecemei',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlanchecemei',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlanchecemei',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_dre', to='escola.diretoriaregional'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_escolas',
            field=models.ManyToManyField(blank=True, editable=False, related_name='%(app_label)s_%(class)s_rastro_escola', to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_lote', to='escola.lote'),
        ),
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
    ]
