# Generated by Django 4.2.7 on 2024-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0068_add_historico_matricula_aluno"),
        ("kit_lanche", "0021_alter_faixasquantidadeskitlancheceidacemei_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitlanche",
            name="tipos_unidades",
            field=models.ManyToManyField(
                related_name="tipo_unidade_kit_lanche", to="escola.tipounidadeescolar"
            ),
        ),
    ]
