# Generated by Django 2.0.13 on 2019-08-05 13:03

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('telefone2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Alteração de cardápio'), (1, 'Inclusão de alimentação'), (2, 'Inclusão de alimentação contínua'), (3, 'Suspensão de alimentação'), (4, 'Solicitação de kit lanche avulsa'), (5, 'Solicitação de kit lanche unificada'), (6, 'Inversão de cardápio')], unique=True)),
                ('assunto', models.CharField(blank=True, max_length=256, null=True, verbose_name='Assunto')),
                ('template_html', models.TextField(blank=True, null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Template de mensagem',
            },
        ),
    ]
