# Generated by Django 2.0.13 on 2019-07-12 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
