# Generated by Django 2.0.13 on 2019-08-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSolicitacoesUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status_evento', models.PositiveSmallIntegerField(choices=[(0, 'Inicio de fluxo'), (1, 'CODAE aprovou'), (2, 'Terceirizada toma ciência'), (3, 'CODAE cancelou pedido'), (4, 'CODAE pede revisão'), (5, 'DRE revisou'), (6, 'DRE aprovou'), (7, 'DRE pediu revisão'), (8, 'DRE cancelou pedido'), (9, 'Escola revisou')])),
                ('solicitacao_tipo', models.PositiveSmallIntegerField(choices=[(0, 'Solicitação de kit lanche avulsa'), (1, 'Alteração de cardápio'), (2, 'Suspensão de cardápio'), (3, 'Inversão de cardápio'), (4, 'Inclusão de alimentação normal'), (5, 'Inclusão de alimentação contínua'), (6, 'Solicitação de kit lanche unificada')])),
                ('uuid_original', models.UUIDField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LogUsuario',
        ),
    ]
