# Generated by Django 2.0.13 on 2019-07-12 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_contato_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
