# Generated by Django 2.0.13 on 2019-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_auto_20190815_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsolicitacoesusuario',
            options={'ordering': ('criado_em',)},
        ),
        migrations.AlterField(
            model_name='logsolicitacoesusuario',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação Realizada'), (1, 'CODAE aprovou'), (2, 'Terceirizada tomou ciência'), (3, 'Terceirizada recusou'), (4, 'CODAE reprovou'), (5, 'CODAE pediu revisão'), (6, 'DRE revisou'), (7, 'DRE aprovou'), (8, 'DRE pediu revisão'), (9, 'DRE reprovou'), (10, 'Escola revisou'), (11, 'Escola cancelou')]),
        ),
    ]
