# Generated by Django 2.0.13 on 2019-08-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_auto_20190820_1108'),
        ('dados_comuns', '0003_auto_20190820_1136'),
    ]

    operations = [
    ]
