# Generated by Django 2.0.13 on 2019-07-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_contato_telefone2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaSemana',
        ),
    ]
