# Generated by Django 2.0.13 on 2019-08-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_auto_20190820_1111'),
        ('dados_comuns', '0004_merge_20190820_1424'),
    ]

    operations = [
    ]
