# Generated by Django 2.0.13 on 2019-08-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0006_auto_20190801_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatemensagem',
            options={'verbose_name': 'Template de mensagem', 'verbose_name_plural': 'Template de mensagem'},
        ),
    ]
