# Generated by Django 2.0.13 on 2019-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionistprofile',
            options={'verbose_name': 'Nutricionista', 'verbose_name_plural': 'Nutricionistas'},
        ),
        migrations.AlterModelOptions(
            name='regionaldirectorprofile',
            options={'verbose_name': 'DRE', 'verbose_name_plural': 'DREs'},
        ),
    ]
