# Generated by Django 2.0.13 on 2019-03-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Functional register')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='E-mail')),
                ('functional_register', models.CharField(blank=True, max_length=60, null=True, unique=True,
                                                         verbose_name='Functional register')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Phone')),
                ('mobile_phone', models.CharField(max_length=11, null=True, verbose_name='Mobile phone')),
                ('status',
                 models.CharField(choices=[('act', 'Active'), ('ina', 'Inactive')], default='act', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Functional register')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='E-mail')),
                ('functional_register', models.CharField(blank=True, max_length=60, null=True, unique=True,
                                                         verbose_name='Functional register')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Phone')),
                ('mobile_phone', models.CharField(max_length=11, null=True, verbose_name='Mobile phone')),
                ('status',
                 models.CharField(choices=[('act', 'Active'), ('ina', 'Inactive')], default='act', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='regionaldirectorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regionaldirectorprofile',
            name='functional_register',
        ),
        migrations.RemoveField(
            model_name='regionaldirectorprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regionaldirectorprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='mobile_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='outsourcedprofile',
            name='mobile_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='outsourcedprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='nutritionistprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='nutritionistprofile',
            name='functional_register',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True,
                                   verbose_name='Functional register'),
        ),
        migrations.AlterField(
            model_name='nutritionistprofile',
            name='status',
            field=models.CharField(choices=[('act', 'Active'), ('ina', 'Inactive')], default='act', max_length=3),
        ),
        migrations.AlterField(
            model_name='outsourcedprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='outsourcedprofile',
            name='functional_register',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True,
                                   verbose_name='Functional register'),
        ),
        migrations.AlterField(
            model_name='outsourcedprofile',
            name='status',
            field=models.CharField(choices=[('act', 'Active'), ('ina', 'Inactive')], default='act', max_length=3),
        ),
        migrations.AddField(
            model_name='regionaldirectorprofile',
            name='alternate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='user_profiles.AlternateProfile'),
        ),
        migrations.AddField(
            model_name='regionaldirectorprofile',
            name='sub_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='user_profiles.SubManagerProfile'),
        ),
    ]
