# Generated by Django 2.0.13 on 2019-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseperson',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
