# Generated by Django 2.0.13 on 2019-04-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0002_auto_20190402_1745'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateprofile',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='nutritionistprofile',
            name='regional_director',
        ),
        migrations.RemoveField(
            model_name='nutritionistprofile',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='outsourcedprofile',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='submanagerprofile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='AlternateProfile',
        ),
        migrations.DeleteModel(
            name='NutritionistProfile',
        ),
        migrations.DeleteModel(
            name='OutSourcedProfile',
        ),
        migrations.DeleteModel(
            name='SubManagerProfile',
        ),
    ]
