# Generated by Django 2.0.13 on 2019-08-26 18:04

import environ
from django.db import migrations, models

ROOT_DIR = environ.Path(__file__) - 2

with open(ROOT_DIR.path('sql', '0001_DRE_Solicitacoes_Autorizadas.sql'), 'r') as f:
    sql1 = f.read()

with open(ROOT_DIR.path('sql', '0002_DRE_Solicitacoes_Pendentes.sql'), 'r') as f:
    sql2 = f.read()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql1),
        migrations.RunSQL(sql2),
        migrations.CreateModel(
            name='SolicitacoesAutorizadasDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dre_solicitacoes_autorizadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesPendentesDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dre_solicitacoes_pendentes',
                'managed': False,
            },
        ),
    ]
