# Generated by Django 2.0.13 on 2019-08-23 16:21

import environ
from django.db import migrations, models

ROOT_DIR = environ.Path(__file__) - 2

sql_path = ROOT_DIR.path('sql', '0001_DRE_Solicitacoes_Autorizadas.sql')
with open(sql_path, 'r') as f:
    sql = f.read()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='SolicitacoesAutorizadasDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dre_solicitacoes_autorizadas',
                'managed': False,
            },
        ),
    ]
