# Generated by Django 2.0.13 on 2019-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesAutorizadasDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dre_solicitacoes_autorizadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesPendentesDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dre_solicitacoes_pendentes',
                'managed': False,
            },
        ),
    ]
