# Generated by Django 2.0.13 on 2019-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis_consolidados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesPendentesDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dre_solicitacoes_pendentes',
                'managed': False,
            },
        ),
    ]
