# Generated by Django 2.0.13 on 2019-08-26 19:31

import environ
from django.db import migrations, models

ROOT_DIR = environ.Path(__file__) - 2

sql_path = ROOT_DIR.path('sql', '0003_CODAE_solicitacoes.sql')
with open(sql_path, 'r') as f:
    sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ('paineis_consolidados', '0002_solicitacoespendentesdre'),
    ]

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='SolicitacoesCODAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('lote', models.CharField(max_length=50)),
                ('diretoria_regional_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField()),
                ('tipo_doc', models.CharField(max_length=30)),
                ('status_evento', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'codae_solicitacoes',
                'managed': False,
            },
        ),
    ]
