# Generated by Django 2.0.13 on 2019-07-15 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissao',
            name='acoes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cria'), (1, 'Visualiza'), (3, 'Edita'), (2, 'Cancela'), (4, 'Recebe'), (5, 'Fica ciente'), (6, 'Ciente após autorização')], null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
