# Generated by Django 2.0.13 on 2019-07-15 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_permissao_acoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoes', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cria'), (1, 'Visualiza'), (3, 'Edita'), (2, 'Cancela'), (4, 'Recebe'), (5, 'Fica ciente'), (6, 'Ciente após autorização')], default=[], null=True), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='permissoes',
        ),
        migrations.RemoveField(
            model_name='permissao',
            name='acoes',
        ),
        migrations.AddField(
            model_name='perfilpermissao',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='perfilpermissao',
            name='permissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.Permissao'),
        ),
    ]
