# Generated by Django 2.0.13 on 2019-05-22 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denied_by_company', models.BooleanField(default=False)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Food Inclusion',
                'verbose_name_plural': 'Food Inclusions',
            },
        ),
        migrations.CreateModel(
            name='FoodInclusionDayReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('which_reason', models.TextField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('weekdays', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='FoodInclusionDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number_of_students', models.IntegerField()),
                ('food_inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_inclusion.FoodInclusion')),
                ('meal_type', models.ManyToManyField(to='food.MealType')),
            ],
            options={
                'verbose_name': 'Food Inclusion description',
                'verbose_name_plural': 'Food Inclusion descriptions',
            },
        ),
        migrations.CreateModel(
            name='FoodInclusionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('motivo', models.TextField(blank=True, max_length=256, null=True, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons',
            },
        ),
        migrations.CreateModel(
            name='FoodInclusionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('motivo', models.TextField(blank=True, max_length=256, null=True, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
    ]
