# Generated by Django 2.0.13 on 2019-05-22 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_inclusion', '0002_auto_20190522_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinclusion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodinclusion',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food_inclusion.FoodInclusionStatus'),
        ),
    ]
