# Generated by Django 4.2.7 on 2024-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0046_dataintervaloalteracaocardapiocemei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataintervaloalteracaocardapio",
            name="cancelado_justificativa",
            field=models.CharField(
                blank=True,
                max_length=1500,
                verbose_name="Porque foi cancelado individualmente",
            ),
        ),
        migrations.AlterField(
            model_name="dataintervaloalteracaocardapiocemei",
            name="cancelado_justificativa",
            field=models.CharField(
                blank=True,
                max_length=1500,
                verbose_name="Porque foi cancelado individualmente",
            ),
        ),
    ]
