# Generated by Django 2.0.13 on 2019-08-05 13:03

from django.db import migrations, models
import django_xworkflows.models
import sme_pratoaberto_terceirizadas.dados_comuns.models_abstract
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tempo_passeio', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Quatro horas'), (1, 'Cinco a sete horas'), (2, 'Oito horas')], null=True)),
                ('quantidade_alunos', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Escola quantidade',
                'verbose_name_plural': 'Escolas quantidades',
            },
        ),
        migrations.CreateModel(
            name='ItemKitLanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Item do kit lanche',
                'verbose_name_plural': 'Item do kit lanche',
            },
        ),
        migrations.CreateModel(
            name='KitLanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Kit lanche',
                'verbose_name_plural': 'Kit lanches',
            },
        ),
        migrations.CreateModel(
            name='MotivoSolicitacaoUnificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo da solicitação unificada',
                'verbose_name_plural': 'Motivos da solicitação unificada',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoKitLanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tempo_passeio', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Quatro horas'), (1, 'Cinco a sete horas'), (2, 'Oito horas')], null=True)),
            ],
            options={
                'verbose_name': 'Solicitação kit lanche base',
                'verbose_name_plural': 'Solicitações kit lanche base',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoKitLancheAvulsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=23, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaEscolaWorkflow', states=['RASCUNHO', 'DRE_A_VALIDAR', 'DRE_APROVADO', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO']))),
                ('local', models.CharField(max_length=160)),
                ('quantidade_alunos', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Solicitação de kit lanche avulsa',
                'verbose_name_plural': 'Solicitações de kit lanche avulsa',
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name='SolicitacaoKitLancheUnificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=23, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='PedidoAPartirDaDiretoriaRegionalWorkflow', states=['RASCUNHO', 'CODAE_A_VALIDAR', 'DRE_PEDE_ESCOLA_REVISAR', 'CODAE_APROVADO']))),
                ('outro_motivo', models.TextField(blank=True, null=True)),
                ('quantidade_max_alunos_por_escola', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('local', models.CharField(max_length=160)),
                ('lista_kit_lanche_igual', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Solicitação kit lanche unificada',
                'verbose_name_plural': 'Solicitações de  kit lanche unificadas',
            },
            bases=(sme_pratoaberto_terceirizadas.dados_comuns.models_abstract.TemIdentificadorExternoAmigavel, django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
    ]
