# Generated by Django 2.0.13 on 2019-07-10 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tempo_passeio', models.PositiveSmallIntegerField(choices=[(0, 'Quatro horas'), (1, 'Cinco a sete horas'), (2, 'Oito horas')], default=0)),
                ('quantidade_alunos', models.PositiveSmallIntegerField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
            ],
            options={
                'verbose_name': 'Escola quantidade',
                'verbose_name_plural': 'Escolas quantidades',
            },
        ),
        migrations.CreateModel(
            name='ItemKitLanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Item do kit lanche',
                'verbose_name_plural': 'Item do kit lanche',
            },
        ),
        migrations.CreateModel(
            name='KitLanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('itens', models.ManyToManyField(to='kit_lanche.ItemKitLanche')),
            ],
            options={
                'verbose_name': 'Kit lanche',
                'verbose_name_plural': 'Kit lanches',
            },
        ),
        migrations.CreateModel(
            name='MotivoSolicitacaoUnificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo da solicitação unificada',
                'verbose_name_plural': 'Motivos da solicitação unificada',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoKitLanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tempo_passeio', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Quatro horas'), (1, 'Cinco a sete horas'), (2, 'Oito horas')], null=True)),
                ('kits', models.ManyToManyField(blank=True, to='kit_lanche.KitLanche')),
            ],
            options={
                'verbose_name': 'Solicitação kit lanche base',
                'verbose_name_plural': 'Solicitações kit lanche base',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoKitLancheAvulsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('local', models.CharField(max_length=160)),
                ('quantidade_alunos', models.PositiveSmallIntegerField()),
                ('dado_base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kit_lanche.SolicitacaoKitLanche')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_kit_lanche_avulsa', to='escola.Escola')),
            ],
            options={
                'verbose_name': 'Solicitação de kit lanche avulsa',
                'verbose_name_plural': 'Solicitações de kit lanche avulsa',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoKitLancheUnificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outro_motivo', models.TextField(blank=True, null=True)),
                ('quantidade_max_alunos_por_escola', models.PositiveSmallIntegerField()),
                ('local', models.CharField(max_length=160)),
                ('lista_kit_lanche_igual', models.BooleanField(default=True)),
                ('dado_base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kit_lanche.SolicitacaoKitLanche')),
                ('diretoria_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.DiretoriaRegional')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kit_lanche.MotivoSolicitacaoUnificada')),
            ],
            options={
                'verbose_name': 'Solicitação kit lanche unificada',
                'verbose_name_plural': 'Solicitações de  kit lanche unificadas',
            },
        ),
        migrations.AddField(
            model_name='escolaquantidade',
            name='kits',
            field=models.ManyToManyField(blank=True, to='kit_lanche.KitLanche'),
        ),
        migrations.AddField(
            model_name='escolaquantidade',
            name='solicitacao_unificada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas_quantidades', to='kit_lanche.SolicitacaoKitLancheUnificada'),
        ),
    ]
