# Generated by Django 2.0.13 on 2019-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolaquantidade',
            name='tempo_passeio',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Quatro horas'), (1, 'Cinco a sete horas'), (2, 'Oito horas')], null=True),
        ),
    ]
