# Generated by Django 2.0.13 on 2019-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kit_lanche', '0002_auto_20190717_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaokitlancheavulsa',
            old_name='dado_base',
            new_name='solicitacao_kit_lanche',
        ),
        migrations.RenameField(
            model_name='solicitacaokitlancheunificada',
            old_name='dado_base',
            new_name='solicitacao_kit_lanche',
        ),
    ]
