# Generated by Django 2.0.13 on 2019-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0004_solicitacaokitlancheavulsa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaokitlancheunificada',
            name='quantidade_max_alunos_por_escola',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
