# Generated by Django 2.0.13 on 2019-08-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0004_auto_20190815_1225'),
        ('kit_lanche', '0005_auto_20190816_0821'),
    ]

    operations = [
    ]
