# Generated by Django 2.0.13 on 2019-07-30 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kit_lanche', '0005_auto_20190729_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaokitlancheunificada',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
