# Generated by Django 2.0.13 on 2019-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0006_merge_20190816_1421'),
        ('kit_lanche', '0005_auto_20190816_1653'),
    ]

    operations = [
    ]
