# Generated by Django 2.0.13 on 2019-07-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0006_solicitacaokitlancheunificada_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolaquantidade',
            name='solicitacao_unificada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolas_quantidades', to='kit_lanche.SolicitacaoKitLancheUnificada'),
        ),
    ]
