# Generated by Django 2.0.13 on 2019-08-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_lanche', '0009_merge_20190820_1424'),
        ('kit_lanche', '0009_auto_20190820_1113'),
    ]

    operations = [
    ]
