# Generated by Django 2.0.13 on 2019-05-02 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=60, verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProfileCategory',
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Institution'),
            preserve_default=False,
        ),
    ]
