# Generated by Django 2.0.13 on 2019-03-31 00:57

import uuid

from django.db import migrations, models


# https://docs.djangoproject.com/en/2.1/howto/writing-migrations/#migrations-that-add-unique-fields
class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
