# Generated by Django 2.0.13 on 2019-03-31 00:57

import uuid

from django.contrib.auth import get_user_model
from django.db import migrations, models


# https://docs.djangoproject.com/en/2.1/howto/writing-migrations/#migrations-that-add-unique-fields
# https://stackoverflow.com/questions/35281003/django-migration-with-uuid-field-generates-duplicated-values

def gen_uuid(apps, schema_editor):
    MyModel = get_user_model()
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_user_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(unique=True, editable=False),
        ),
    ]
