# Generated by Django 2.0.13 on 2019-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190320_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_alternate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nutritionist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_outsourced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_regional_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sub_manager',
            field=models.BooleanField(default=False),
        ),
    ]
