# Generated by Django 2.2.6 on 2019-12-05 21:15

import uuid

import django.core.validators
import django_prometheus.models
import django_xworkflows.models
from django.db import migrations, models

import sme_terceirizadas.dados_comuns.behaviors


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoDietaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=26, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='DietaEspecialWorkflow', states=['RASCUNHO', 'CODAE_A_AUTORIZAR', 'CODAE_NEGOU_PEDIDO', 'CODAE_AUTORIZADO', 'TERCEIRIZADA_TOMOU_CIENCIA']))),
                ('codigo_eol_aluno', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL do aluno')),
                ('nome_completo_aluno', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do aluno')),
                ('nome_completo_pescritor', models.CharField(blank=True, max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita')),
                ('registro_funcional_pescritor', models.CharField(blank=True, help_text='CRN/CRM/CRFa...', max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita')),
                ('data_nascimento_aluno', models.DateField(verbose_name='Data de nascimento do aluno')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Solicitação de dieta especial',
                'verbose_name_plural': 'Solicitações de dieta especial',
            },
        ),
    ]
