# Generated by Django 2.2.6 on 2019-11-27 19:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDietaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_eol_aluno', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL do aluno')),
                ('nome_completo_aluno', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do aluno')),
                ('nome_completo_pescritor', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita')),
                ('registro_funcional_pescritor', models.CharField(help_text='CRN/CRM/CRFa...', max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita')),
                ('data_nascimento_aluno', models.DateField(verbose_name='Data de nascimento do aluno')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de dieta especial',
                'verbose_name_plural': 'Solicitações de dieta especial',
            },
        ),
    ]
