# Generated by Django 2.2.6 on 2019-11-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.FileField(upload_to='')),
                ('solicitacao_dieta_especial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dieta_especial.SolicitacaoDietaEspecial')),
            ],
        ),
    ]
