# Generated by Django 2.2.6 on 2019-11-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0002_anexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo',
            old_name='planta',
            new_name='arquivo',
        ),
    ]
