# Generated by Django 2.2.8 on 2020-01-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0003_auto_20200103_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='justificativa_negacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
