# Generated by Django 2.2.6 on 2019-12-02 14:13

import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0011_auto_20191118_1147'),
        ('escola', '0010_remove_escola_endereco'),
        ('dieta_especial', '0003_auto_20191129_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='rastro_dre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dieta_especial_solicitacaodietaespecial_rastro_dre', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='rastro_escola',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dieta_especial_solicitacaodietaespecial_rastro_escola', to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dieta_especial_solicitacaodietaespecial_rastro_lote', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dieta_especial_solicitacaodietaespecial_rastro_terceirizada', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='status',
            field=django_xworkflows.models.StateField(max_length=26, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='CODAE_A_AUTORIZAR', name='DietaEspecialWorkflow', states=['CODAE_A_AUTORIZAR', 'CODAE_NEGOU_PEDIDO', 'CODAE_AUTORIZADO', 'TERCEIRIZADA_TOMOU_CIENCIA'])),
        ),
    ]
