# Generated by Django 2.2.8 on 2020-01-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_aluno'),
        ('dieta_especial', '0003_auto_20200116_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escola.Aluno'),
        ),
    ]
