# Generated by Django 2.2.8 on 2020-01-13 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0004_solicitacaodietaespecial_justificativa_negacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='alergias_intolerancias',
            field=models.ManyToManyField(blank=True, to='dieta_especial.AlergiaIntolerancia'),
        ),
        migrations.RemoveField(
            model_name='solicitacaodietaespecial',
            name='classificacao',
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dieta_especial.ClassificacaoDieta'),
        ),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='tipos',
            field=models.ManyToManyField(blank=True, to='dieta_especial.TipoDieta'),
        ),
    ]
