# Generated by Django 2.2.6 on 2019-12-02 17:40

import django.core.validators
from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0004_auto_20191202_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='nome_completo_pescritor',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita'),
        ),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='registro_funcional_pescritor',
            field=models.CharField(blank=True, help_text='CRN/CRM/CRFa...', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita'),
        ),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='status',
            field=django_xworkflows.models.StateField(max_length=26, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='DietaEspecialWorkflow', states=['RASCUNHO', 'CODAE_A_AUTORIZAR', 'CODAE_NEGOU_PEDIDO', 'CODAE_AUTORIZADO', 'TERCEIRIZADA_TOMOU_CIENCIA'])),
        ),
    ]
