# Generated by Django 2.2.8 on 2020-01-13 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0005_auto_20200112_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='registro_funcional_nutricionista',
            field=models.CharField(blank=True, help_text='CRN/CRM/CRFa...', max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nome completo do pescritor da receita'),
        ),
    ]
