# Generated by Django 2.2.8 on 2020-01-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0005_auto_20200120_1125'),
        ('dieta_especial', '0004_auto_20200121_1026'),
    ]

    operations = [
    ]
