# Generated by Django 2.2.8 on 2020-02-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_auto_20200122_1412'),
        ('dieta_especial', '0008_solicitacoes_ativas_inativas_por_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesDietaEspecialAtivasInativasPorAluno',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='escola.Aluno')),
                ('ativas', models.IntegerField()),
                ('inativas', models.IntegerField()),
            ],
            options={
                'db_table': 'dietas_ativas_inativas_por_aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubstituicaoAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Isento'), ('S', 'Substituir')], max_length=1)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dieta_especial.Alimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='eh_laudo_medico',
        ),
        migrations.RemoveField(
            model_name='solicitacaodietaespecial',
            name='tipos',
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='nome_protocolo',
            field=models.TextField(blank=True, verbose_name='Nome do Protocolo'),
        ),
        migrations.DeleteModel(
            name='TipoDieta',
        ),
        migrations.AddField(
            model_name='substituicaoalimento',
            name='solicitacao_dieta_especial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dieta_especial.SolicitacaoDietaEspecial'),
        ),
        migrations.AddField(
            model_name='substituicaoalimento',
            name='substitutos',
            field=models.ManyToManyField(related_name='substitutos', to='dieta_especial.Alimento'),
        ),
    ]
