# Generated by Django 2.2.8 on 2020-01-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_auto_20200122_1412'),
        ('dieta_especial', '0008_solicitacoes_ativas_inativas_por_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesDietaEspecialAtivasInativasPorAluno',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='escola.Aluno')),
                ('ativas', models.IntegerField()),
                ('inativas', models.IntegerField()),
            ],
            options={
                'db_table': 'dietas_ativas_inativas_por_aluno',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dietas_especiais', to='escola.Aluno'),
        ),
    ]
