# Generated by Django 2.2.8 on 2020-01-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0009_auto_20200129_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaodietaespecial',
            options={'ordering': ('-ativo', '-criado_em'), 'verbose_name': 'Solicitação de dieta especial', 'verbose_name_plural': 'Solicitações de dieta especial'},
        ),
    ]
