# Generated by Django 2.2.8 on 2020-01-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0009_solicitacoesdietaespecialativasinativasporaluno'),
        ('dieta_especial', '0010_auto_20200129_1806'),
    ]

    operations = [
    ]
