# Generated by Django 2.2.8 on 2020-02-25 14:55

from django.db import migrations, models
import sme_terceirizadas.dados_comuns.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0010_anexo_eh_laudo_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='data_expiracao',
            field=models.DateField(null=True, validators=[sme_terceirizadas.dados_comuns.validators.nao_pode_ser_no_passado]),
        ),
    ]
