# Generated by Django 2.2.8 on 2020-02-03 14:26

import django_xworkflows.models
import environ
from django.db import migrations

ROOT_DIR = environ.Path(__file__) - 3

sql_path_drop = ROOT_DIR.path('paineis_consolidados/sql', '0005_drop_view_solicitacoes.sql')
sql_path_recreate = ROOT_DIR.path('paineis_consolidados/sql', '0006_recreate_view_solicitacoes.sql')
with open(sql_path_drop, 'r') as f:
    sql_drop = f.read()
with open(sql_path_recreate, 'r') as f:
    sql_recreate = f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0011_merge_20200131_1449')
    ]

    operations = [
        migrations.RunSQL(sql_drop),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='status',
            field=django_xworkflows.models.StateField(max_length=27, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='DietaEspecialWorkflow', states=['RASCUNHO', 'CODAE_A_AUTORIZAR', 'CODAE_NEGOU_PEDIDO', 'CODAE_AUTORIZADO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'ESCOLA_SOLICITOU_INATIVACAO', 'CODAE_NEGOU_INATIVACAO', 'CODAE_AUTORIZOU_INATIVACAO'])),
        ),
        migrations.RunSQL(sql_recreate)
    ]
