# Generated by Django 2.2.8 on 2020-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0012_auto_20200203_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='eh_laudo_alta',
            field=models.BooleanField(default=False),
        ),
    ]
