# Generated by Django 2.2.13 on 2020-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0013_auto_20200825_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituicaoalimento',
            name='substitutos',
            field=models.ManyToManyField(blank=True, related_name='substitutos', to='dieta_especial.Alimento'),
        ),
    ]
