# Generated by Django 2.2.13 on 2020-10-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0015_tipocontagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ('nome',)},
        ),
    ]
