# Generated by Django 2.2.13 on 2020-10-19 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0023_auto_20201009_1259'),
        ('dieta_especial', '0016_auto_20201004_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAlteracaoUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo Alteração U.E',
                'verbose_name_plural': 'Motivo Alteração U.E',
            },
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='data_final_alteracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='data_inicial_alteracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='dieta_alterada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dieta_especial.SolicitacaoDietaEspecial'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='escola_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.Escola'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='observacoes_alteracao',
            field=models.TextField(blank=True, verbose_name='Observações Alteração'),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('ALUNO_NAO_MATRICULADO', 'Aluno não matriculado'), ('ALTERACAO_UE', 'Alteração U.E')], default='COMUM', max_length=30),
        ),
        migrations.AddField(
            model_name='solicitacaodietaespecial',
            name='motivo_alteracao_ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dieta_especial.MotivoAlteracaoUE'),
        ),
    ]
