# Generated by Django 2.2.13 on 2020-11-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0019_auto_20201124_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ('nome',)},
        ),
    ]
