# Generated by Django 2.2.13 on 2020-12-15 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0022_solicitacaodietaespecial_caracteristicas_do_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='registro_funcional_nutricionista',
            field=models.CharField(blank=True, help_text='CRN/CRM/CRFa...', max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Registro funcional do nutricionista'),
        ),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='registro_funcional_pescritor',
            field=models.CharField(blank=True, help_text='CRN/CRM/CRFa...', max_length=200, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(6)], verbose_name='Registro funcional do pescritor da receita'),
        ),
    ]
