# Generated by Django 2.2.13 on 2020-12-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0022_alimentoproprio'),
        ('dieta_especial', '0023_auto_20201215_1046'),
    ]

    operations = [
    ]
