# Generated by Django 2.2.13 on 2020-12-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0024_merge_20201215_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentoproprio',
            options={'verbose_name': 'alimento próprio CODAE', 'verbose_name_plural': 'alimentos próprios CODAE'},
        ),
    ]
