# Generated by Django 2.2.13 on 2021-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0026_planilhadietasativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilhadietasativas',
            name='resultado',
            field=models.FileField(blank=True, help_text='Arquivo com o resultado', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='planilhadietasativas',
            name='tempfile',
            field=models.CharField(blank=True, help_text='JSON temporario', max_length=100, null=True),
        ),
    ]
