# Generated by Django 2.2.13 on 2021-03-04 14:52

import django.core.validators
import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0027_auto_20210224_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='status',
            field=django_xworkflows.models.StateField(max_length=37, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='DietaEspecialWorkflow', states=['RASCUNHO', 'CODAE_A_AUTORIZAR', 'CODAE_NEGOU_PEDIDO', 'CODAE_AUTORIZADO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'ESCOLA_SOLICITOU_INATIVACAO', 'CODAE_NEGOU_INATIVACAO', 'CODAE_AUTORIZOU_INATIVACAO', 'TERCEIRIZADA_TOMOU_CIENCIA_INATIVACAO', 'TERMINADA_AUTOMATICAMENTE_SISTEMA', 'CANCELADO_ALUNO_MUDOU_ESCOLA', 'CANCELADO_ALUNO_NAO_PERTENCE_REDE'])),
        ),
        migrations.CreateModel(
            name='LogDietasAtivasCanceladasAutomaticamente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_eol_aluno', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Código EOL aluno')),
                ('nome_aluno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Aluno')),
                ('codigo_eol_escola_origem', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL escola origem')),
                ('nome_escola_origem', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nome da Escola origem')),
                ('codigo_eol_escola_destino', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL escola destino')),
                ('nome_escola_destino', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nome da Escola destino')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dietas_especiais', to='dieta_especial.SolicitacaoDietaEspecial')),
            ],
            options={
                'verbose_name': 'log dietas ativas canceladas automaticamente',
                'verbose_name_plural': 'log dietas ativas canceladas automaticamente',
                'ordering': ('-criado_em',),
            },
        ),
    ]
