# Generated by Django 2.2.13 on 2021-03-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0028_auto_20210304_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdietasativascanceladasautomaticamente',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_especiais', to='dieta_especial.SolicitacaoDietaEspecial'),
        ),
    ]
