# Generated by Django 2.2.13 on 2021-04-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0048_auto_20210316_1143'),
        ('dieta_especial', '0030_protocolopadraodietaespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituicaoAlimentoProtocoloPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('I', 'Isento'), ('S', 'Substituir')], max_length=1)),
                ('alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dieta_especial.Alimento')),
                ('alimentos_substitutos', models.ManyToManyField(blank=True, related_name='alimentos_substitutos_protocolo_padrao', to='dieta_especial.Alimento')),
                ('protocolo_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta_especial.ProtocoloPadraoDietaEspecial')),
                ('substitutos', models.ManyToManyField(blank=True, help_text='produtos substitutos', related_name='substitutos_protocolo_padrao', to='produto.Produto')),
            ],
            options={
                'verbose_name': 'Substituição de alimento para protocolo padrão de dieta',
                'verbose_name_plural': 'Substituições de alimentos para protocolos padrões de dietas',
            },
        ),
    ]
