# Generated by Django 2.2.13 on 2021-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0032_auto_20210416_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolopadraodietaespecial',
            name='orientacoes_gerais',
            field=models.TextField(blank=True, verbose_name='Orientações Gerais'),
        ),
    ]
