# Generated by Django 2.2.13 on 2021-06-16 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0033_protocolopadraodietaespecial_orientacoes_gerais'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoSubstituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dieta_especial.Alimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='substituicaoalimentoprotocolopadrao',
            name='alimentos_substitutos',
        ),
        migrations.AddField(
            model_name='substituicaoalimentoprotocolopadrao',
            name='alimentos_substitutos',
            field=models.ManyToManyField(blank=True, related_name='alimentos_substitutos_protocolo_padrao', through='dieta_especial.AlimentoSubstituto', to='dieta_especial.Alimento'),
        ),
        migrations.AddField(
            model_name='alimentosubstituto',
            name='substituicao_alimento_protocolo_padrao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dieta_especial.SubstituicaoAlimentoProtocoloPadrao'),
        ),
    ]
