# Generated by Django 2.2.13 on 2021-07-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0034_auto_20210616_0115'),
        ('dieta_especial', '0034_auto_20210628_1625'),
    ]

    operations = [
    ]
