# Generated by Django 2.2.13 on 2021-07-05 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0035_merge_20210705_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolopadraodietaespecial',
            name='historico',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
