# Generated by Django 2.2.13 on 2021-10-27 01:41

from django.db import migrations, models
import sme_terceirizadas.dados_comuns.constants
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0038_solicitacaodietaespecial_conferido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoCargaDietaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conteudo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO')], default=sme_terceirizadas.dados_comuns.constants.StatusProcessamentoArquivo('PENDENTE'), max_length=35, verbose_name='status')),
                ('log', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arquivo para importação de solicitações de Dieta Especial',
                'verbose_name_plural': 'Arquivos para importação de solicitações de Dieta Especial',
            },
        ),
    ]
