# Generated by Django 2.2.13 on 2021-10-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0039_arquivocargadietaespecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivocargadietaespecial',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
    ]
