# Generated by Django 2.2.13 on 2021-10-28 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0042_auto_20211028_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoCargaAlimentosSubstitutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conteudo', models.FileField(blank=True, default='', upload_to='')),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO'), ('PROCESSADO_COM_ERRO', 'PROCESSADO_COM_ERRO'), ('PROCESSANDO', 'PROCESSANDO')], default='PENDENTE', max_length=35, verbose_name='status')),
                ('log', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Arquivo para importação de Alimentos e Alimentos substitutos',
                'verbose_name_plural': 'Arquivos para importação de Alimentos e Alimentos substitutos',
            },
        ),
        migrations.AddField(
            model_name='alimento',
            name='tipo_listagem_protocolo',
            field=models.CharField(choices=[('SO_ALIMENTOS', 'Aparece somente na listagem de alimentos'), ('SO_SUBSTITUTOS', 'Aparece somente na listagem de alimentos substitutos'), ('AMBOS', 'Aparece nas listagem de alimentos e substitutos')], default='SO_ALIMENTOS', max_length=15),
        ),
    ]
