# Generated by Django 2.2.13 on 2021-10-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0043_arquivocargadietaespecial_resultado'),
        ('dieta_especial', '0043_auto_20211028_1907'),
    ]

    operations = [
    ]
