# Generated by Django 2.2.13 on 2021-11-22 17:59

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0045_arquivocargausuariosescola'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivonegacao',
            name='processo',
            field=models.CharField(choices=[('CANCELAMENTO', 'Solicitação de Cancelamento'), ('INCLUSAO', 'Solicitação de Inclusão')], default='INCLUSAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaodietaespecial',
            name='status',
            field=django_xworkflows.models.StateField(max_length=37, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='RASCUNHO', name='DietaEspecialWorkflow', states=['RASCUNHO', 'CODAE_A_AUTORIZAR', 'CODAE_NEGOU_PEDIDO', 'CODAE_AUTORIZADO', 'TERCEIRIZADA_TOMOU_CIENCIA', 'ESCOLA_CANCELOU', 'CODAE_NEGOU_CANCELAMENTO', 'ESCOLA_SOLICITOU_INATIVACAO', 'CODAE_NEGOU_INATIVACAO', 'CODAE_AUTORIZOU_INATIVACAO', 'TERCEIRIZADA_TOMOU_CIENCIA_INATIVACAO', 'TERMINADA_AUTOMATICAMENTE_SISTEMA', 'CANCELADO_ALUNO_MUDOU_ESCOLA', 'CANCELADO_ALUNO_NAO_PERTENCE_REDE'])),
        ),
    ]
