# Generated by Django 2.2.13 on 2022-07-12 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dieta_especial', '0047_auto_20220321_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaEmEdicaoAberta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao_dieta_especial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta_especial.SolicitacaoDietaEspecial')),
                ('usuario_com_dieta_aberta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
