# Generated by Django 2.2.13 on 2022-09-30 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0053_periodoescolar_tipo_turno'),
        ('dieta_especial', '0048_protocolopadraodietaespecial_editais'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogQuantidadeDietasAutorizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_dietas_autorizadas', to='dieta_especial.ClassificacaoDieta')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_dietas_autorizadas', to='escola.Escola')),
            ],
            options={
                'verbose_name': 'Log da quantidade de dietas autorizadas por unidade escolar',
                'verbose_name_plural': 'Logs da quantidade de dietas autorizadas por unidade escolar',
                'ordering': ('-data', 'escola__nome'),
            },
        ),
    ]
