# Generated by Django 2.2.13 on 2022-12-22 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dieta_especial', '0049_logquantidadedietasautorizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaEmEdicaoAberta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_solicitacao_dieta_especial', models.CharField(max_length=50)),
                ('usuario_com_dieta_aberta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
