# Generated by Django 2.2.13 on 2022-10-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0049_auto_20221004_1716'),
        ('dieta_especial', '0049_logquantidadedietasautorizadas'),
    ]

    operations = [
    ]
