# Generated by Django 2.2.13 on 2023-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0050_auto_20230116_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolopadraodietaespecial',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
    ]
