# Generated by Django 3.2.16 on 2023-02-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0051_protocolopadraodietaespecial_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolopadraodietaespecial',
            name='historico',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
