# Generated by Django 3.2.16 on 2023-03-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta_especial', '0050_merge_20221027_1529'),
        ('dieta_especial', '0052_alter_protocolopadraodietaespecial_historico'),
    ]

    operations = [
    ]
