# Generated by Django 3.2.18 on 2023-08-17 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0060_auto_20230815_1534'),
        ('dieta_especial', '0054_protocolopadraodietaespecial_outras_informacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogQuantidadeDietasAutorizadasCEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_dietas_autorizadas_cei', to='dieta_especial.classificacaodieta')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_dietas_autorizadas_cei', to='escola.escola')),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.faixaetaria')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_dietas_autorizadas_cei', to='escola.periodoescolar')),
            ],
            options={
                'verbose_name': 'Log da quantidade de dietas autorizadas por unidade escolar CEI',
                'verbose_name_plural': 'Logs da quantidade de dietas autorizadas por unidade escolar CEI',
                'ordering': ('-data', 'escola__nome'),
            },
        ),
    ]
