# Generated by Django 3.2.18 on 2023-08-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0060_auto_20230815_1534'),
        ('dieta_especial', '0055_logquantidadedietasautorizadascei'),
    ]

    operations = [
        migrations.AddField(
            model_name='logquantidadedietasautorizadas',
            name='periodo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_dietas_autorizadas', to='escola.periodoescolar'),
        ),
    ]
