import logging
import unicodedata

from django.db.models import F, Func, Value
from django.db.models.functions import Upper

from difflib import get_close_matches

from django.core.management import BaseCommand

from sme_terceirizadas.produto.models import Marca, Produto, Fabricante
from sme_terceirizadas.dieta_especial.models import Alimento

logger = logging.getLogger('sigpae.cmd_suja_base')


class Command(BaseCommand):
    """
    Script para corrigir marcas e produtos duplicados.
    """
    help = 'Corrige marcas e produtos duplicadoss'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS(f'*** Marcas ***'))
        self.corrige_marcas()
        self.normalizar_marcas()
        self.remove_duplicados_marcas()

        self.stdout.write(self.style.SUCCESS(f'*** Fabricantes ***'))
        self.corrige_fabricantes()
        self.normalizar_fabricantes()
        self.padronizar_SA_LTDA()
        self.remove_duplicados_fabricantes()

    def remove_duplicados_marcas(self):
        combinacoes_marcas = []
        marcas = [marca.nome for marca in Marca.objects.all()]
        for marca in marcas:
            combinacao = get_close_matches(marca, marcas, cutoff=1)
            combinacao.sort()
            if len(combinacao) > 1 and combinacao not in combinacoes_marcas:
                combinacoes_marcas.append(combinacao)
        for combinacao in combinacoes_marcas:
            try:
                marca_original = Marca.objects.filter(nome=combinacao[0]).first()
                marcas_duplicadas = Marca.objects.filter(nome=combinacao[0]).exclude(
                    id=marca_original.id)
                Produto.objects.filter(marca__nome=combinacao[0]).exclude(
                    marca=marca_original).update(marca=marca_original)
                Alimento.objects.filter(marca__nome=combinacao[0]).exclude(
                    marca=marca_original).update(marca=marca_original)
                marcas_duplicadas.delete()
            except:
                self.stdout.write(self.style.ERROR(f'Erro ao atualizar marca {combinacao[0]}'))

    def remove_duplicados_fabricantes(self):
        combinacoes_fabricantes = []
        fabricantes = [fabricante.nome for fabricante in Fabricante.objects.all()]
        for fabricante in fabricantes:
            combinacao = get_close_matches(fabricante, fabricantes, cutoff=1)
            combinacao.sort()
            if len(combinacao) > 1 and combinacao not in combinacoes_fabricantes:
                combinacoes_fabricantes.append(combinacao)
        for combinacao in combinacoes_fabricantes:
            try:
                fabricante_original = Fabricante.objects.filter(nome=combinacao[0]).first()
                fabricantes_duplicados = Fabricante.objects.filter(nome=combinacao[0]).exclude(
                    id=fabricante_original.id)
                Produto.objects.filter(fabricante__nome=combinacao[0]).exclude(
                    fabricante=fabricante_original).update(fabricante=fabricante_original)
                fabricantes_duplicados.delete()
            except:
                self.stdout.write(self.style.ERROR(f'Erro ao atualizar fabricante {combinacao[0]}'))

    def remove_acentos(self, text):
        text = unicodedata.normalize('NFD', text) \
            .encode('ascii', 'ignore') \
            .decode("utf-8")
        return str(text)

    def normalizar_marcas(self):
        self.stdout.write(self.style.SUCCESS(f'Convertendo marcas para UPPER'))
        Marca.objects.update(nome=Upper('nome'))
        self.stdout.write(self.style.SUCCESS(f'Removendo espaços duplos'))
        Marca.objects.filter(nome__icontains='  ').update(
            nome=Func(F('nome'), Value('  '), Value(' '), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Removendo acentos'))
        for marca in Marca.objects.all():
            if self.remove_acentos(marca.nome) != marca.nome:
                marca.nome = self.remove_acentos(marca.nome)
                marca.save()

    def normalizar_fabricantes(self):
        self.stdout.write(self.style.SUCCESS(f'Convertendo fabricantes para UPPER'))
        Fabricante.objects.update(nome=Upper('nome'))
        self.stdout.write(self.style.SUCCESS(f'Removendo espaços duplos'))
        Fabricante.objects.filter(nome__icontains='  ').update(
            nome=Func(F('nome'), Value('  '), Value(' '), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Removendo acentos'))
        for fabricante in Fabricante.objects.all():
            if self.remove_acentos(fabricante.nome) != fabricante.nome:
                fabricante.nome = self.remove_acentos(fabricante.nome)
                fabricante.save()

    def padronizar_SA_LTDA(self):
        self.stdout.write(self.style.SUCCESS(f'Substituindo S.A. por SA'))
        Fabricante.objects.filter(nome__icontains='S.A.').update(
            nome=Func(F('nome'), Value('S.A.'), Value('SA'), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Substituindo S.A por SA'))
        Fabricante.objects.filter(nome__icontains='S.A').update(
            nome=Func(F('nome'), Value('S.A'), Value('SA'), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Substituindo SA. por SA'))
        Fabricante.objects.filter(nome__icontains=' SA.').update(
            nome=Func(F('nome'), Value(' SA.'), Value(' SA'), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Substituindo S/A por SA'))
        Fabricante.objects.filter(nome__icontains='S/A').update(
            nome=Func(F('nome'), Value('S/A'), Value('SA'), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Substituindo S A por SA'))
        Fabricante.objects.filter(nome__icontains=' S A').update(
            nome=Func(F('nome'), Value(' S A'), Value(' SA'), function='replace'))
        self.stdout.write(self.style.SUCCESS(f'Substituindo LTDA. por LTDA'))
        Fabricante.objects.filter(nome__icontains='LTDA.').update(
            nome=Func(F('nome'), Value('LTDA.'), Value('LTDA'), function='replace'))

    def corrige_marcas(self):
        self.stdout.write(self.style.SUCCESS(f'Normalizando marcas para unificação'))
        Marca.objects.filter(nome='CORPO & SABOR').update(nome='CORPO E SABOR')
        Marca.objects.filter(nome='FAZENDA NOVA ALINAÇA').update(nome='FAZENDA NOVA ALIANÇA')
        Marca.objects.filter(nome="KARAM'S MAR").update(nome='KARAMS MAR')
        Marca.objects.filter(nome='MILNUTRI PREMIUM+').update(nome='MILNUTRI PREMIUM +')
        Marca.objects.filter(nome='MULTMEAT').update(nome='MULTIMEAT')
        Marca.objects.filter(nome='NESLAC CONFOR ZERO LACTOSE').update(nome='NESLAC COMFOR ZERO LACTOSE')

    def corrige_fabricantes(self):
        self.stdout.write(self.style.SUCCESS(f'Normalizando fabricantes para unificação'))
        Fabricante.objects.filter(nome='BRASIL CITRUS IND. E COM. LTDA').update(
            nome='BRASIL CITRUS INDÚSTRIA E COMÉRCIO LTDA')
        Fabricante.objects.filter(nome__in=['BRYK - IND. DE PANIFICAÇÃO LTDA',
                                            'BRYK - INDÚSTRIA DE PANIFICAÇÃO LTDA',
                                            'BRYK IND.DE PANIFICAÇÃO LTDA'],
                                  ).update(nome='BRYK INDÚSTRIA DE PANIFICAÇÃO LTDA')
        Fabricante.objects.filter(nome='COCAM CIA. DE CAFE SOLUVEL E DERIVADOS').update(
            nome='COCAM CIA DE CAFE SOLUVEL E DERIVADOS')
        Fabricante.objects.filter(nome__in=[
            'D. B. IND. E COM. DE CARNES E DERIVADOS LTDA',
            'D.B INDÚSTRIA E COMÉRCIO DE CARNES E DERIVADOS LTDA']
        ).update(nome='DB INDÚSTRIA E COMÉRCIO DE CARNES E DERIVADOS LTDA')
        Fabricante.objects.filter(
            nome='EBBA S/A- EMPRESA BRASILEIRA DE BEBIDAS E ALIMENTOS S/A').update(
            nome='EBBA S/A - EMPRESA BRASILEIRA DE BEBIDAS E ALIMENTOS S/A')
        Fabricante.objects.filter(nome__in=['F DOTTO & CIA LTDA', 'F. DOTTO E CIA LTDA.']).update(
            nome='F DOTTO E CIA LTDA')
        Fabricante.objects.filter(
            nome='Grani Amici Ind. e Com.de Alimentos S.A.').update(nome='Grani Amici Ind. e Com. de Alimentos S.A.')
        Fabricante.objects.filter(nome='HIBRA COMÉRCIO DE ALIMENTOS LTDA.').update(
            nome='HIBRA COMÉRCIO DE ALIMENTOS LTDA')
        Fabricante.objects.filter(nome='IBS - INDUSTRIA BRASILEIRA DE SUCOS LTDA').update(
            nome='IBS - INDÚSTRIA BRASILEIRA DE SUCOS LTDA')
        Fabricante.objects.filter(nome='INDÚSTRIA E COMÉRCIO DE LATICÍNIOS FLORESCER LTDA.').update(
            nome='INDÚSTRIA E COMÉRCIO DE LATICÍNIOS FLORESCER LTDA')
        Fabricante.objects.filter(nome='Indústria de massas alimentícias Rosane LTDA.').update(
            nome='Indústria de massas alimentícias Rosane LTDA'
        )
        Fabricante.objects.filter(nome='INDÚSTRIA DE TORRONE N.S. DE MONTEVERGINE LTDA').update(
            nome='INDÚSTRIA DE TORRONE N S DE MONTEVERGINE LTDA'
        )
        Fabricante.objects.filter(nome='J A COMÉRCIO DE GÊNEROS ALIMENTÍCIOS E SERVIÇOS EIRELI').update(
            nome='J. A. COMÉRCIO DE GÊNEROS ALIMENTÍCIOS E SERVIÇOS EIRELI'
        )
        Fabricante.objects.filter(nome__in=['JASMINE COM. DE PRODUTOS ALIMENTICIOS LTDA',
                                            'JASMINE COM. DE PRODUTOS ALIMENTICIOS LTDA.']).update(
            nome='JASMINE COMERCIO DE PRODUTOS ALIMENTICIOS LTDA'
        )
        Fabricante.objects.filter(nome__in=['JOSAPAR - JOAQUIM OLIVEIRA S.A PARTICIPAÇÕES',
                                            'JOSAPAR - JOAQUIM OLIVEIRA S.A PARTICIPAÇÕES',
                                            'JOSAPAR-JOAQUIM OLIVEIRA SA PARTICIPAÇÕES']).update(
            nome='JOSAPAR JOAQUIM OLIVEIRA SA PARTICIPAÇÕES')
        Fabricante.objects.filter(nome__in=['KIM NETO IND. E COM. DE PANIFICAÇÃO LTDA',
                                            'KIM NETO IND. E COM. DE PANIFICAÇÃO LTDA.',
                                            'KIM NETOIND. E COM. DE PANIFICAÇÃO LTDA.',
                                            'KIM NETO IND. E OCM. DE PANIFICACAO LTDA',
                                            'KIM NETO INDUSTRIA E COMERCIO DE PANIFICAÇÃO LTDA']).update(
            nome='KIM NETO INDUSTRIA E COMERCIO DE PANIFICAÇÃO LTDA'
        )
        Fabricante.objects.filter(nome__in=[
            'LOUIS DREYFUS COMPANY BRASIL S.A',
            'LOUIS DREYFUS COMPANY BRASIL S.A.',
            'LOUIS DREYFUS COMPANY BRASIL S/A'
        ]).update(nome='LOUIS DREYFUS COMPANY BRASIL SA')
        Fabricante.objects.filter(nome__in=[
            'M DIAS BRANCO S A', 'M. DIAS BRANCO S.A'
        ]).update(nome='M DIAS BRANCO SA')
        Fabricante.objects.filter(nome='KIM NETOIND. E COM. DE PANIFICAÇÃO LTDA.').update(
            nome='KIM NETO IND. E COM. DE PANIFICAÇÃO LTDA')
        Fabricante.objects.filter(nome='NESTLE BRASIL LTDA').update(nome='NESTLÉ BRASIL LTDA')
        Fabricante.objects.filter(nome__in=['PARATI S.A', 'PARATI S.A.']).update(nome='PARATI SA')
        Fabricante.objects.filter(nome='PASTIFÍCIO SANTA AMÁLIA S.A').update(nome='PASTIFÍCIO SANTA AMÁLIA SA')
        Fabricante.objects.filter(nome__in=[
            'PANIFICADORA E DISTRIBUIDORA RE- ALI JUNIOR',
            'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR',
            'PANIFICADORA E DISTRIBUIDORA RE- ALI JÚNIOR',
            'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR LTDA']).update(
            nome='PANIFICADORA E DISTRIBUIDORA RE ALI JUNIOR LTDA')
        Fabricante.objects.filter(nome__in=[
            'PASTIFÍCIO SELMI', 'PASTIFÍCIO SELMI S.A', 'PASTIFÍCIO SELMI S/A', 'PASTIFÍCIO SELMI S A']).update(
            nome='PASTIFICIO SELMI SA'
        )
        Fabricante.objects.filter(nome='VALE FÉRTIL INDÚSTRIAS ALIMENTÍCIAS LTDA').update(
            nome='VALE FÉRTIL INDUSTRIAS ALIMENTÍCIAS LTDA')
        Fabricante.objects.filter(nome__in=['PRODIET NUTRIÇÃO CLÍNICA LTDA.', 'PRODIET NUTRIÇÃO CLÍNICA LTDS']).update(
            nome='PRODIET NUTRIÇÃO CLÍNICA LTDA'
        )
        Fabricante.objects.filter(
            nome__in=['PRODUTOS DE MANDIOCA SÃO PAULO', 'PRODUTOS DE MANDIOCA SÃO PAULO LTDA']).update(
            nome='PRODUTOS DE MANDIOCA SAO PAULO LTDA')
        Fabricante.objects.filter(nome__in=['Pantera alimentos Ltda.', 'pantera alimentos ltda']).update(
            nome='PANTERA ALIMENTOS LTDA'
        )
        Fabricante.objects.filter(nome='REFINORTE - REF. DE SAL DUNORTE INDUSTRIA E COMÉRCIO LTDA.').update(
            nome='REFINORTE - REFINARIA DE SAL DUNORTE INDÚSTRIA E COMÉRCIO LTDA'
        )
        Fabricante.objects.filter(nome='SEM GLÚTEN MARILIS PROD. ALIM. LTDA').update(
            nome='SEM GLÚTEN MARILIS PRODUTOS ALIMENTÍCIOS LTDA'
        )

marcas = ['3 FAZENDAS',
 '5 ESTRELAS',
 '5 ESTRELAS',
 '88',
 'A GOSTO',
 'ABBOTT',
 'ABC',
 "AD'0RO",
 "AD'ORO",
 'ADES',
 'ADOCYL',
 'ADRIA',
 'AD´ORO',
 'AGROBAL',
 'AGROLAF',
 'AJA',
 'ALBARUSKA',
 'ALCA FOODS',
 'ALCA FOODS',
 'ALCA FOODS',
 'ALHO TOP',
 'ALHO TOP',
 'ALIBABÁ',
 'ALIMENTARE',
 'ALIMENTO COM SOJA SEM LACTOSE - SABOR IOGURTE',
 'ALIMENTTA',
 "ALL' DORO",
 'ALQUIMYA',
 'ALTO ALEGRE',
 'AMORE',
 'ANINHA',
 'ANNIELA',
 'APETITE',
 'APTAMIL AR',
 'APTAMIL PREMIUM 1',
 'APTAMIL PREMIUM 2',
 'APTAMIL PRO EXPERT HA',
 'APTAMIL PRO EXPERT PEPTI',
 'APTAMIL PRO EXPERT SL',
 'APTAMIL PRO EXPERT SOJA 1',
 'APTAMIL PRO EXPERT SOJA 2',
 'APTAMIL PROFUTURA 2',
 'APTANUTRI PROFUTURA 3',
 'APTI',
 'APTI',
 'ARCO IRIS',
 'ARCO IRIS',
 'ARCO ÍRIS',
 'ARCO ÍRIS',
 'ARO',
 'ARRIFANA',
 'ARROVITA',
 'ART SUCO',
 'ATACAMA',
 'AURORA',
 'B J P',
 'BAPTISTELLA ALIMENTOS',
 'BAPTISTELLA ALIMENTOS LTDA',
 'BARRA',
 'BATAVO',
 'BAUDUCCO',
 'BAUDUCCO - MORANGO',
 'BECEL',
 'BEIJU BOM',
 'BELADRI',
 'BELADRI NUTRIÇÃO E SABOR',
 'BELIVE',
 'BELIVE',
 'BELIVE',
 'BELIVE',
 'BELO MINAS',
 'BEM NUTRIR',
 'BIG VALLEY',
 'BIGUÁ',
 'BIO2',
 'BIOLAC',
 'BIOLAT',
 'BISCOITO DE POLVILHO CASSINI',
 'BISCOITO DOCE MAISENA',
 'BISCOITO DOCE MARIA',
 'BISCOITO SALGADO CREAM CRACKER INTEGRAL',
 'BISCOLEVE',
 'BJP',
 'BLUE DIAMOND ALMONDS',
 'BOLO INDIVIDUAL ABACAXI',
 'BOLO INDIVIDUAL BAUNILHA',
 'BOLO INDIVIDUAL CHOCOLATE',
 'BOLO INDIVIDUAL COCO',
 'BOLO INDIVIDUAL FUBÁ',
 'BOLO INDIVIDUAL INTEGRAL BAUNILHA',
 'BOLO INDIVIDUAL INTEGRAL COCO',
 'BOLO INDIVIDUAL INTEGRAL LARANJA',
 'BOLO INDIVIDUAL LARANJA',
 'BOM SABOR',
 'BONARE',
 'BONDELÍ',
 'BRILHANTE',
 'BURITI',
 'C.VALE',
 'CABE',
 'CADEBE',
 'CADEBE',
 'CADORE',
 'CAFÉ BRASILEIRO',
 'CALDO NOBRE',
 'CALDO REI',
 'CALOGEN',
 'CAMIL',
 'CAMP',
 'CAMPO BELO',
 'CAMPO BOM',
 'CANÇÃO',
 "CAPPRY'S",
 'CARAVELAS',
 'CARREFOUR',
 'CASA GRANDE',
 'CASARÃO',
 'CASEIRO',
 'CASSINI',
 'CASTELO',
 'CASTELO DE CHAVES',
 'CATABY',
 'CATABY',
 'CATIVA',
 'CATUPIRY LACTOZERO',
 'CCGL',
 'CCR',
 'CELI VITA',
 'CELI VITA',
 'CELI VITA',
 'CELI VITA',
 'CELI VITA',
 'CELIA',
 'CELLI TOP',
 'CELLI TOP',
 'CENTRAL NSALIMENTOS',
 'CENTROESTE ALIMENTOS',
 'CHAMINÉ',
 'CHOCO CELLI',
 'CHOCO FORTE',
 'CHÁ LEÃO',
 'CHÁ LEÃO (CAMOMILA)',
 'CHÁ LEÃO - CAMOMILA',
 'CIA DA SAÚDE',
 'CIA DA SAÚDE',
 'CIA DA SAÚDE',
 'CIAGRO',
 'CLAYBOM',
 'CLUBE DO FEIJÃO',
 'COAPROCOR',
 'COCAM',
 'COCAMAR',
 'COCINERO',
 'COMBRASIL',
 'CONGE FRUTAS',
 'COOPERVASS',
 'COPA',
 'COPAGRO',
 'COPAGRO',
 'COPRA',
 'COQUEIRO',
 'CORPO & SABOR',
 'CORPO E SABOR',
 'COSSARI',
 'COYOTE',
 'CRI ALIMENTOS',
 'CRIALIMENTOS',
 'CRIOULO',
 'D & D',
 'DA BARRA',
 'DA FRUTA',
 'DA ROLT',
 'DA ROZ',
 'DA ROZ',
 'DA SABOR',
 'DACOLI ALIMENTOS',
 'DALLAS',
 'DALLAS - AVEIA E MEL',
 'DALLAS GREEN',
 'DANATA',
 'DANDONG HAILONG / HAILONG FOODS',
 'DANIELI',
 'DANIELI',
 'DANKY',
 'DANKY MAX',
 'DANONE',
 'DANONE',
 'DANONE - CALOGEN',
 'DANONE - NUTRIDRINK COMPACT PROTEIN',
 'DAROLT',
 'DASABOR',
 'DE LA MARIE',
 'DE PARMA',
 'DECORA',
 'DELAMARIE',
 'DELEON ALHOS',
 'DELEON ALHOS',
 'DELICIA',
 'DELIFOODS',
 'DELLA',
 'DELLA',
 'DELÍCIA',
 'DELÍCIA',
 'DEPARMA',
 'DI FILETTO',
 'DIANA',
 'DIO SANTO',
 'DIRETO DA FRUTA',
 'DIVINA DIETA',
 'DIVINA DIETA',
 'DIZA',
 'DO BEM',
 'DO CHEF',
 'DO CHEF',
 'DO VALLE',
 'DO ZÉ',
 'DOBÁ',
 'DOCE MENOR',
 'DONA BENTA',
 'DONA BENTA (COM FERMENTO)',
 'DONA JURA',
 'DONA LAURA',
 'DONA MALU',
 'DONA ZEZÉ',
 'DORI',
 'DORIANA',
 'DOTTO',
 'DOTTO',
 'DR. OETKER',
 'DUCOCO',
 'DUNGA',
 'DUNORTE',
 'DÁLIA',
 'DÁSABE',
 'DÁSABOR',
 'EITA',
 'ELEGÊ',
 'ELOS FRUTI',
 'ENERGY',
 'ENFAGROW',
 'ENFAMIL PREMIUM PRO EVOLUT 2',
 'ENFAMIL PREMIUM PRO EVOLUT GENTLEASE',
 'ENFANUTRI PREMIUM PRO EVOLUT',
 'ENSURE',
 'EUROLAT',
 'FAMIL',
 'FAST MAX FOOD',
 'FAZENDA BELA VISTA',
 'FAZENDA NOVA ALIANÇA',
 'FAZENDA NOVA ALINAÇA',
 'FAZENDA ORGANICA',
 'FAZENDA ORGÂNICA',
 'FAZENDAS DO RIO',
 'FAZENDINHA',
 'FAZENDÃO POP',
 'FEINKOST',
 'FEINKOST',
 'FHOM',
 'FINA FLOR',
 'FLOR DE LIS',
 'FLORIANI',
 'FORTINI COMPLETE',
 'FORTINI MULTI FIBER',
 'FORTINI PLUS',
 'FREBINI',
 'FREBINI ORIGINAL FIBRE',
 'FRESKITO',
 'FRESUBIN PROTEIN ENERGY DRINK',
 'FRIBOI',
 'FRIGBRASIL',
 'FRIGOFORTE',
 'FRIGONOSSA',
 'FRIGORÍFICO MORRO GRANDE',
 'FRIGORÍFICO SÃO PAULO',
 'FRIMESA',
 'FRIMINHO',
 'FRIOLINS',
 'FRUTAP',
 'FRUTTILIFE',
 'FUDAO',
 'FUGINI',
 'GABI',
 'GALO',
 'GALO INTEGRAL',
 'GALO INTEGRAL',
 'GALO SHOW',
 'GALÁCTIKO',
 'GALÁCTIKO VITAMINADO',
 'GAROA',
 'GARÇA',
 'GELIALGAS',
 'GELÉIA DIET SABOR GOIABA',
 'GIRASSOL',
 'GLOBO',
 'GLORIA',
 'GOIABAL',
 'GOLD FLAKES',
 'GOMES DA COSTA',
 'GRAN REAL',
 'GRANI AMICI',
 'GRANJA BRASIL',
 'GRANJA BRASIL',
 'GRANJA GEMAR',
 'GRANJA SHIDA',
 'GRANO BRASILIS',
 'GRANOLA GRAIN FLAKES DIET - CRANBERRY & GOJIBERRY',
 'GRINGS',
 'GRINGS',
 'GURI',
 'GUTH',
 'HELCE',
 'HELLMANNS',
 'HERO BRASIL',
 'HOMEL',
 'HORMEL',
 'HUÉ',
 'IANA',
 'IGLU',
 'INTEGRAL SOUL',
 'INTEIRÃO',
 'ISOSOURCE 1,5',
 'ISOSOURCE SOYA',
 'ITAGUARY',
 'ITALAC',
 'ITAMBÉ',
 'ITAMBÉ',
 'ITAMBÉ (COM VITAMINAS)',
 'ITAMBÉ ZERO LACTOSE - NOLAC',
 'ITORORO',
 'IZZY',
 'IZZY',
 'IZZY',
 'J.A. JORDANESIA ALIMENTOS',
 'J.A. JORDANESIA ALIMENTOS',
 'JAGUÁ',
 'JAMAVA',
 'JAMAVA',
 'JAMAVA',
 'JASMINE',
 'JASMINE GRAIN FLAKES DIET',
 'JESSY SEAFOODS',
 'JJ FOODS',
 'JOTA',
 'JOTA',
 'JOVANIL',
 'JUNIOR',
 'JUSSARA',
 'JUSSARA MAX',
 'JÓIA',
 "KARAM'S MAR",
 "KARAM'S MAR",
 "KARAM'S MAR",
 "KARAM'S MAR",
 "KARAM'S MAR",
 'KARAMS MAR',
 'KEGGS',
 'KELLOGG´S SUCRILHOS',
 'KI-APETITE',
 'KIBELLO',
 'KICALDO',
 'KIM',
 'KIM',
 'KIM',
 'KISABOR',
 'KITANO',
 'KOBBER',
 'KOBBER',
 'KORIN',
 'LA SERENÍSSIMA',
 'LA VIE',
 'LANGUIRU',
 'LARANJA PERA',
 'LARANJA PERA',
 'LATCO',
 'LATICÍNIOS PORTO ALEGRE',
 'LATICÍNIOS PORTO ALEGRE',
 'LATICÍNIOS PORTO ALEGRE',
 'LATICÍNIOS PORTO ALEGRE',
 'LATICÍNIOS PORTO ALEGRE',
 'LAZPER',
 'LBS FOODS',
 'LE PETIT',
 'LE VIDA',
 'LEFORTH',
 'LEITINO',
 'LEO',
 'LEO',
 'LEVE CROCK',
 'LEVE CROCK',
 'LEVIT',
 'LEVIT - MAIZENA INTEGRAL',
 'LEVIT - MARIA CACAU INTEGRAL',
 'LEVO',
 'LIANE',
 'LIDER',
 'LIDER',
 'LIFE MIX',
 'LIFE SUCOS',
 'LINEA',
 'LINEA',
 'LIZA',
 'LOLLA',
 'LOPES',
 'LOWÇUCAR',
 'LÍDER',
 'MACEDO',
 'MAGRO',
 'MAGUARY',
 'MAGUARY',
 'MAIS CERTA',
 'MAISCERTA',
 'MAIZENA',
 'MALAQUIA',
 'MANI',
 'MANTIQUEIRA',
 'MANUELA',
 'MAR & RIO PESCADOS',
 'MARATÁ',
 'MARIA INÊS',
 'MARILAN',
 'MARILIS',
 'MARILIS',
 'MARRAKECH',
 'MASTER',
 'MASTER KUKA',
 'MATINAL CEREALLE',
 'MATTE LEÃO',
 'MATTE LEÃO (CHÁ MATE A GRANEL - ORIGINAL)',
 'MAVALÉRIO',
 'MEATFOODS',
 'MEGA',
 'MEGA',
 'MEGA',
 'MEIO DIA',
 'MELITTA',
 'MESA +',
 'MESTRE KUKA',
 'MEU BIJU',
 'MEZATO FOODS',
 'MIL CORES',
 'MILKLIFE',
 'MILNUTRI PREMIUM +',
 'MILNUTRI PREMIUM+',
 'MILUPA 1',
 'MILUPA 2',
 'MIMO',
 'MIMOSAL',
 'MINERVA',
 'MIRAHY',
 'MIX',
 'MOCOCA',
 'MOINHO GLOBO',
 'MOINHO SPECIAL',
 'MONAMA',
 'MONOPOL',
 'MORRO GRANDE',
 'MOSMANN',
 'MOSMANN',
 'MOSMANN - MARIA AVEIA E MEL',
 'MUCILON',
 'MULAC',
 'MULT BEEF',
 'MULT BEEF COMERCIAL LTDA',
 'MULTIMEAT',
 'MULTMEAT',
 'NAMORADO',
 'NAN COMFOR 1',
 'NAN COMFOR 2',
 'NAN ESPESSAR',
 'NAN HA',
 'NAN SL',
 'NAN SOJA',
 'NAN SUPREME 2',
 'NAN SUPREME I',
 'NAT',
 'NATIVO',
 'NATURALE',
 'NATURALLIFE',
 'NAZINHA',
 'NEC ALIANÇA',
 'NEC ALIANÇA',
 'NEC ALIANÇA',
 'NEILAR',
 'NEOCATE LCP',
 'NEOFORTE',
 'NESCAFÉ MATINAL SUAVE',
 'NESCAFÉ ORIGINAL EXTRAFORTE',
 'NESCAFÉ TRADIÇÃO FORTE',
 'NESCAU',
 'NESFIT',
 'NESFIT - AVEIA E MEL',
 'NESLAC COMFOR ZERO LACTOSE',
 'NESLAC CONFOR ZERO LACTOSE',
 'NESLAC SUPREME',
 'NESTLÉ',
 'NESTLÉ - DOIS FRADES',
 'NESTOGENO 1',
 'NESTOGENO 2',
 'NESTONUTRI',
 'NEW CHOCO',
 'NILZA',
 'NINFA',
 'NINHO',
 'NINHO FASES PREBIO 1',
 'NINHO FASES PREBIO 3',
 'NINHO FORTI +',
 'NITA',
 'NOLAR',
 'NORDESTE',
 'NOT MILK',
 'NOVA PÃES ROIAM',
 'NOVAMIL RICE',
 'NS ALIMENTOS',
 'NUTRELLA VIVA',
 'NUTRELLA VIVA',
 'NUTREN',
 'NUTREN 2.0',
 'NUTREN JUNIOR',
 'NUTRI COOKIE',
 'NUTRI COOKIE',
 'NUTRI COOKIE',
 'NUTRICOOKIE',
 'NUTRIDRINK COMPACT PROTEIN',
 'NUTRIDRINK PROTEIN',
 'NUTRIL INTEGRAL',
 'NUTRIL INTEGRAL',
 'NUTRIMAX',
 'NUTRINI ENERGY MULTI FIBER 1,5 KCAL/ML',
 'NUTRINI STANDARD',
 'NUTRIPAR',
 'NUTRIPLENO',
 'NUTRY',
 'NUTS',
 'NUTS',
 'NaturalLife',
 'OCEANI',
 'ODEBRECHT',
 'OFÉLIA',
 'OGATA',
 'OKOSHI',
 'OLÉ',
 'ORGANIC ALIMENTOS',
 'OS AVENTUREIROS',
 'OURO BRANCO',
 'OVOS DOIS IRMÃOS',
 'OVOS YOSHIOKA',
 'PACAEMBU',
 'PALLADIO',
 'PANCO',
 'PARATI',
 'PARATI',
 'PARATI - AVEIA',
 'PARMALAT',
 'PATEKO',
 'PATRIOTA',
 'PATÉKO',
 'PAULISTA',
 'PAULISTA',
 'PAULISTA',
 'PAULISTA',
 'PAULISTA',
 'PAULISTA',
 'PAULISTINHA',
 'PEDIASURE',
 'PEGJÁ',
 'PELÉ',
 'PERDIGÃO',
 'PERDIGÃO',
 'PERGOLA',
 'PIC NIC',
 'PICININ',
 'PICININ PRETO',
 'PIF PAF',
 'PILECCO NOBRE',
 'PINK',
 'PIRACANJUBA',
 'PIRAMIDE',
 'PIT STOP',
 'POLENGUINHO',
 'POLIDINHO',
 'POLLY',
 'POLLY MINUS',
 'POLPA DE FRUTA CONGELADA GOIABA',
 'PONTUAL',
 'PORTO ALEGRE',
 'PORTO ALEGRE',
 'PORTO ALEGRE',
 'PORTOGUASSU',
 'PQ ALIMENTOS',
 'PQ ALIMENTOS',
 'PQ ALIMENTOS',
 'PQ ALIMENTOS',
 'PREDILECTA',
 'PREDILECTA',
 'PREGOMIN PEPTI',
 'PRETO BOM',
 'PRIMALATTE',
 'PRISMARA',
 'PROCOOKING ALIMENTOS',
 'PRODUTOS MS',
 'PULLMAN',
 'PURINHA',
 'PURO GRÃO',
 'PÃO DE FORMA INTEGRAL',
 'PÃO DE LIZ',
 'PÃO TIPO HAMBURGUER',
 'QUALICAU',
 'QUALIMAX',
 'QUALITÁ',
 'QUALY',
 'QUALY VITA',
 'QUATÁ KIDS',
 'QUEENSBERRY',
 'QUERO',
 'Qualitá',
 'RACINE',
 'RAGUTS ALIMENTOS',
 'RAMPINELLI',
 'RAROZ',
 'RAVAN',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'RE-ALI JUNIOR',
 'REI DA ALMÔNDEGA',
 'REI DA MESA',
 'RENATA',
 'RENATA - AVEIA E MEL',
 'RENATA - LEITE E MEL COM GRANOLA',
 'RF FOODS',
 'RICAELI',
 'RIO FORTE',
 'RIO PRETO PESCADO/CENTRAL FISH',
 'RIOLAT',
 'RISOVITA',
 'RISOVITA',
 'RIVOLI',
 'ROMANO',
 'ROOTS TO GO',
 'ROSANE',
 'ROSEANE',
 'ROYAL',
 'S.H.A SERVIÇOS EM ALIMENTAÇÃO',
 'SABOR MÁXIMO',
 'SABOREL',
 'SABOREL',
 'SABORES DA ROÇA',
 'SABOROSO',
 'SACCIALI',
 'SACCIALI (ARROZ INTEGRAL)',
 'SACCIALI (ERVILHA)',
 'SACCIALI (MILHO)',
 'SADIA',
 'SAINT PAUL',
 'SALMONETE',
 'SANNABOM',
 'SANNABOM',
 'SANNABOM',
 'SANPER',
 'SANTA AMÁLIA',
 'SANTA AMÁLIA S.A',
 'SANTA CLARA',
 'SANTA CLARA',
 'SANTA CLARA',
 'SANTA CLARA',
 'SANTA CLARA',
 'SANTA FELICIDADE',
 'SANTA MONICA',
 'SARAPUÍ',
 'SAÚDE',
 'SCHAR',
 'SEARA',
 'SEMBEI',
 'SERENATA',
 'SHA',
 'SHA',
 'SHEFA',
 'SIL-BOM',
 'SILK',
 'SILK',
 'SIMPLES ASSIM',
 'SINGLE',
 'SINHÁ',
 'SOLITO',
 'SORA',
 'SOY',
 'SOY',
 'SOY MAIS',
 'SOY ORIGINAL ZERO ADIÇÃO DE AÇÚCARES',
 'SOY+',
 'SOY+',
 'SOY+ ORIGINAL',
 'SOYMILKE',
 'SOYMIX',
 'SPECHT',
 'STELLA D ORO',
 'STELLA D ORO',
 'STELLA D´ORO',
 'SUAVIPAN',
 'SUAVIT',
 'SUPER CHEF',
 'SUPER CHEF',
 'SUPER CHEF',
 'SUPER CHEF',
 'SUPER ECCO',
 'SUPER SOLTO',
 'SUPRA SOY',
 'SUPRA SOY',
 'SUSTAGEN KIDS',
 'SUSTENTARE',
 'SUVALAN',
 'SWEET FLAKES',
 'SÓ PEIXE',
 'SÓ PESCA',
 'TALISMÃ',
 'TATITÂNIA',
 'TEC SABOR',
 'TECNUTRI',
 'TERRA BRASIL',
 'TERRA LIVRE',
 'THICK & EASY',
 'THICKENUP CLEAR',
 'TIAL KIDS',
 'TIAL KIDS',
 'TIGRE',
 'TIO JOSÉ',
 'TIO JOTA',
 'TIO JOÃO',
 'TIROLEZ',
 'TIROLEZ LIGHT',
 'TIROLEZ ZERO LACTOSE',
 'TIVVA',
 'TODESCHINI',
 'TOP CARNES',
 'TOSCANO',
 'TRADELLI',
 'TRADIÇÃO BRASILEIRA',
 'TRAVESSO',
 'TREVINHO',
 'TREVINHO TRIPLA ATITUDE SABOR FRUTAS',
 'TRISANTI',
 'TROPES',
 'TROPHIC BASIC',
 'TROPHIC INFANT',
 'TRÊS CORAÇÕES',
 'TRÊS COROAS',
 'TRÊS MARIAS',
 'TUI',
 'TUTTI LIFE',
 'TUTTY LIFE',
 'UNIBABY',
 'UNIFLAVORS',
 'UNIU',
 'UNIÃO',
 'URBANO',
 'UTAM',
 'VAL',
 'VALE FÉRTIL',
 'VALE FÉRTIL',
 'VANESSA',
 'VANTAJOSO',
 'VASCAÍNA',
 'VERDE CAMPO',
 'VERMICELLI',
 'VIDA VEG',
 'VIGOR',
 'VILMA',
 'VISCONDE',
 'VITA',
 'VITA SUCO',
 'VITAKI',
 'VITALIA',
 'VITALIN',
 'VITALIV',
 'VITAO',
 'VITAO ALIMENTOS LTDA',
 'VITARELLA SALT VIP',
 'VITASUCO',
 'VOLKMANN',
 'Vitao',
 'WICKBOLD',
 'WICKBOLD',
 'WICKBOLD',
 'WICKBOLD',
 'WICKBOLD',
 'WICKBOLD',
 'XODÓMILHO',
 'YARA',
 'YOKI',
 'YUMMY',
 'ZABET',
 'ZANCHETTA',
 'ZANIN',
 'ZERO CAL']



# fabricantes = ['A D´ORO SA ABATEDOURO FRIGORÍFICO', 'ABBOTT LABORATORIOS DO BRASIL LTDA', "AD'ORO SA MATADOURO  DE AVES E COELHOS", "AD'ORO SA MATADOURO DE AVES E COELHOS", 'ADM DO BRASIL  LTDA', 'ADM RONDONÓPOLIS', 'AGARGEL INDÚSTRIA E COMÉRCIO LTDA.', 'AGRARFROST GMBH & CO', 'AGRO-INDUSTRIAL COOPERATIVA CENTRAL', 'AGROBAL INDÚSTRIA E COMÉRCIO LTDA', 'AGRODANIELI INDÚSTRIA E COMÉRCIO LTDA', 'AGRODANIELI INDÚSTRIA E COMÉRCIO LTDA', 'AGROINDÚSTRIA E COMÉRCIO DE CEREAIS TRÊS IRMÃOS LTDA', 'AGROINDÚSTRIA SÃO SEBASTIÃO DA BELA VISTA LTDA', 'AGROLAF COM. DE PROD. ALIMENTÍCIOS LTDA', 'AGROPECUÁRIA RIO MACHADO IND E COM LTDA', 'AGROPECUÁRIA TUIUTI S/A', 'AGROPECUÁRIA TUIUTI SA', 'AGROPECUÁRIA TUÍUTI S A', 'ALCA  FOODS LTDA', 'ALCA FOODS', 'ALCA FOODS', 'ALCA FOODS LTDA', 'ALCA FOODS LTDA', 'ALHO TOP - SÃO JOSÉ', 'ALHO TOP - SÃO JOSÉ', 'ALIMENTOS DALLAS IND E COM LTDA', 'ALL DORO COMÉRCIO DE PRODUTOS ALIMENTÍCIOS EIRELI', 'ALNUTRI ALIMENTOS LTDA', 'ALPENAS BOA NUTRIÇÃO INDÚSTRIA DE ALIMENTOS LTDA', 'ALQUIMYA NATURAL COMÉRCIO DE ALIMENTOS EIRELI', 'AMAFIL INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'AMBEV S A FILIAL JAGUARIUNA', 'AMIDOS SÃO JOÃO LTDA', 'ANGELO AURICCHIO & CIA LTDA', 'ANTONIAZZI & CIA LTDA', 'ANTONIO BORIN IND E COM. DE VINAGRE LTDA', 'APTI', 'APTI ALIMENTOS LTDA', 'ARC LOGÍSTICA E ALIMENTOS LTDA', 'ARCO ÍRIS', 'ARCO ÍRIS', 'ARCO ÍRIS', 'ARRIFANA INDL. IMP E EXP DE ALIMENTOS LTDA', 'ARROZEIRA PELOTAS INDÚSTRIA E COMÉRCIO DE CEREAIS LTDA', 'ARROZEIRA WERPPE LTDA', 'ASSOCIAÇÃO FARTURA ALIMENTOS', 'AÇÚCAR NUMERO UM SA', 'B J P COMERCIO E DISTRIBUIÇÃO DE ALIMENTOS LTDA', 'BAPTISTELLA ALIMENTOS LTDA', 'BEBA BRASIL INDÚSTRIA E COMÉRCIO LTDA', 'BELADRI MASSAS E CONFEITOS LTDA', 'BELARINA ALIMENTOS SA', 'BEM NUTRIR INDÚSTRIA E COMÉRCIO DE PRODUTOS ALIMENTÍCIOS', 'BEM NUTRIR INDÚSTRIA E COMÉRCIO DE PRODUTOS ALIMENTÍCIOS SEM GLÚTEN LTDA', 'BENEF GERALDO A CARRERA LTDA', 'BENEFICIADORA GERALDO A CARRERA LTDA', 'BH FOODS COMÉRCIO E INDÚSTRIA LTDA', 'BIFUM BRASIL ALIMENTOS LTDA', 'BIGUÁ ALIMENTOS LTDA', 'BIMBO DO BRASIL LTDA', 'BIMBO DO BRASIL LTDA', 'BIOTEC INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'BIOTEC INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'BISCOITO DUNGA PRODUTOS ALIMENTÍCIOS LTDA', 'BISCOITONE INDÚSTRIA DE PRODUTOS ALIMENTÍCIOS LTDA', 'BJP COMÉRCIO E DISTRIBUIÇÃO DE ALIMENTOS EIRELI', 'BLANKE INDUSTRIA DE PESCADO LTDA.', 'BOA FÉ INDÚSTRIA E COMÉRCIO LTDA', 'BOA FÉ INDÚSTRIA E COMÉRCIO LTDA', 'BOA FÉ INDÚSTRIA E COMÉRCIO LTDA', 'BOA FÉ INDÚSTRIA E COMÉRCIO LTDA', 'BOM GOSTO ALIMENTOS LTDA', 'BOYERCO S.A.', 'BRASIL CITRUS IND. E COM. LTDA', 'BRASIL CITRUS INDÚSTRIA E COMÉRCIO LTDA', 'BRASIL CITRUS INDÚSTRIA E COMÉRCIO LTDA', 'BRASVALLE TRASNP E COMÉRCIO DE CEREAIS LTDA', 'BRASÍLIA ALIMENTOS LTDA', 'BRF - BRASIL FOODS SA', 'BRF SA', 'BROTO LEGAL ALIMENTOS SA', 'BROTO LEGAL ALIMENTOS SA', 'BRYK - IND. DE PANIFICAÇÃO LTDA', 'BRYK - INDÚSTRIA DE PANIFICAÇÃO LTDA', 'BRYK IND. DE PANIFICAÇÃO', 'BRYK IND.DE PANIFICAÇÃO LTDA', 'BRYK INDÚSTRIA DE PANIFICAÇÃO LTDA', 'BUNGE ALIMENTOS SA', 'BUNGE ALIMENTOS SA', 'C.VALE - COOPERATIVA AGROINDUSTRIAL', 'CACAU FOODS DO BRASIL ALIMENTOS LTDA', 'CACAU FOODS DO BRASIL ALIMENTOS LTDA', 'CADORE', 'CAMIL ALIMENTOS S.A.', 'CAMIL ALIMENTOS SA', 'CAMPO BOM INDÚSTRIA E COMÉRCIO, IMP. E EXP. LTDA', 'CAPODIFOGLIO & CIA LTDA', 'CAPODIFOGLIO & CIA LTDA', 'CAPODIFOGLIO & CIA LTDA', 'CARAMURU ALIMENTOS SA', 'CARBA INDÚSTRIA DE ALIMENTOS EIRELLI', 'CARBA INDÚSTRIA DE ALIMENTOS EIRELLI', 'CARBA INDÚSTRIA DE ALIMENTOS EIRELLI', 'CARGILL AGRÍCOLA S A', 'CARPE ETIAM ALIMENTOS LTDA', 'CASSINI ALIMENTOS LTDA', 'CASTELO ALIMENTOS S.A.', 'CASTELO ALIMENTOS S/A', 'CASTELO DE CHAVES INDÚSTRIA E COMÉRCIO DE ALIMENTOS EIRELI', 'CATABY IND. E COMÉRCIO DE CARNES', 'CATABY IND. E COMÉRCIO DE CARNES LTDA', 'CATAPY IND. E COMÉRCIO DE CARNES LTDA', 'CCR', 'CENTRAL FISH INDÚSTRIA E COMÉRCIO DE PESCADOS LTDA', 'CENTRAL NSALIMENTOS', 'CENTROESTE CARNES E DERIVADOS LTDA.', 'CEREAIS  CELIA LTDA', 'CEREALISTA ALBARUSKA LTDA.', 'CEREALISTA MENDES LTDA', 'CEREALISTA MIRAGUAIA LTDA', 'CIA CACIQUE DE CAFÉ SOLÚVEL', 'CIAGRO ALIMENTOS LTDA', 'CLAUDINO JOSÉ FARIA -  GRANJA AVÍCOLA', 'CLAUDIO BIANCHI TAVARES CEREAIS EIRELI', 'COAPROCOR COOPERATIVA AGROINDUSTRIAL DE PRODUTORES DE CORUMBATAÍ DO SUL E REGIÃO', 'COASUL COOPERATIVA AGROINDUSTRIAL', 'COCAM CIA DE CAFÉ SOLÚVEL E DERIVADOS', 'COCAM CIA. DE CAFÉ SOLÚVEL E DERIVADOS', 'COCAMAR COOPERATIVA AGROINDUSTRIAL', 'COLOMBO AGROINDÚSTRIA', 'COMAL ARROZ LTDA', 'COMBRASIL', 'COMERCIAL AJA COM. ATACAD. DE OVOS LTDA', 'COMERCIAL DE ALIMENTOS TALISMÃ LTDA', 'COMERCIAL LEOPOLDINA IMP. E EXP. LTDA', 'COMERCIAL SABOR DO TEMPERO LTDA', 'COMERCIAL SABOR DO TEMPERO LTDA', 'COMPANHIA CACIQUE DE CAFÉ SOLÚVEL', 'COMÉRCIO DE ALIMENTOS DA SABOR LTDA', 'COMÉRCIO DE ALIMENTOS DASABOR', 'COMÉRCIO DE CEREAIS GOOD LTDA', 'COMÉRCIO DE OVOS E CEREAIS GEMAR LTDA.', 'COMÉRCIO E EMPACOTAMENTO DE ALIMENTOS O SICILIANO LTDA', 'COMÉRCIO E EMPACOTAMENTO DE ALIMENTOS O SICILIANO LTDA', 'COMÉRCIO E EMPACOTAMENTO DE ALIMENTOS O SICILIANO LTDA', 'COMÉRCIO E EMPACOTAMENTO DE ALIMENTOS O SICILIANO LTDA', 'COMÉRCIO E INDÚSTRIA DE MANDIOCA PAULISTA LTDA', 'CONFEPAR  AGRO INDUSTRIAL - COOPERATIVA CENTRAL', 'CONFEPAR AGRO-INDUSTRIAL LTDA.', 'CONGE FRUTAS LTDA', 'COOPERATIVA AGROINDUSTRIAL NOVA ALIANÇA LTDA', 'COOPERATIVA AGROINDUSTRIAL ROSARIENSE', 'COOPERATIVA AGROPECUÁRIA DE TUBARÃO', 'COOPERATIVA AGROPECUÁRIA DE TUBARÃO', 'COOPERATIVA CENTRAL GAÚCHA LTDA', 'COOPERATIVA COOPERSULCA', 'COOPERATIVA DE PROD. AGROPECUÁRIA NOVA SANTA RITA LTDA', 'COOPERATIVA DÁLIA ALIMENTOS LTDA', 'COOPERATIVA JURITI', 'COOPERATIVA SUL RIOGRANDENSE DE LATICÍNIOS LTDA', 'COOPERATIVA VINÍCOLA AURORA', 'COOPERATIVA VINÍCOLA AURORA LTDA', 'COOTAP- COOPERATIVA DOS TRABALHADORES ASSENTADOS DA REGIÃO DE PORTO ALEGRE LTDA', 'COPAVIDI', 'COPERATIVA JURITI', 'COPOLFOOD COM. DE PRODUTOS ALIMENTÍCIOS', 'COSMED INDUSTRIA DE COSMETICOS E MEDICAMENTOS S/A', 'COSMED INDUSTRIA DE COSMETICOS E MEDICAMENTOS S/A', 'COSSARI INDÚSTRIA E COMÉRCIO DE PRODUTOS ALIMENTÍCIOS LTDA', 'CPN ALIMENTOS LTDA', 'CRI ALIMENTOS IND. E COMÉRCIO LTDA', 'CRIALIMENTOS INDÚSTRIA E COMÉRCIO LTDA', 'CRISF IND. E COM. DE PRODUTOS ALIMENTÍCIOS LTDA', 'CURIONI & BIOLLO LTDA', 'Cossari  Ind. Com. Prod. Alim. Ltda.', 'Crialimentos Indústria e Comércio LTDA', 'D & D SEMENTES E TEMPEROS', 'D. B. IND. E COM. DE CARNES E DERIVADOS LTDA', 'D.B INDÚSTRIA E COMÉRCIO DE CARNES E DERIVADOS LTDA', 'DAILAN TAIFU FOOD CO. LTDA', 'DAIRY PARTNERS AMERICAS MANUFACTURING BRASIL LTDA', 'DALIAN FUDAO AQUATIC PRODUCTS AND FOOD CO LTD', 'DALIAN TIANBAO GREEN FOODS CO LTDA', 'DALIAN YUANFENG FOODS CO, LTD', 'DALLAS', 'DAN VIGOR INDÚSTRIA E COMÉRCIO DE LATICÍNIOS LTDA', 'DANATA COMÉRCIO ATACADISTA IMP E EXP DE PRODUTOS ALIMENTÍCIOS LTDA', 'DANDONG HAILONG FOODSTUFF CO LTDA', 'DANONE LTDA', 'DANONE LTDA FÁBRICA DE LATICÍNIOS', 'DELAMARIE INDÚSTRIA E COMÉRCIO LTDA', 'DELIFOODS ALIMENTOS', 'DELIFOODS ALIMENTOS EIRELI', 'DEMELLO ALIMENTOS LTDA.', 'DEPTO. DIVINA DIETA DA APAE DE SP', 'DIELAT INDÚSTRIA E COMÉRCIO DE LATICÍNIOS LTDA', 'DIELAT INDÚSTRIA E COMÉRCIO DE LATICÍNIOS LTDA FÁBRICA DE LATICÍNIOS', 'DIST. E EMP. DE PRODUTOS ALIMENTÍCIOS CORDEIRO LTDA', 'DISTRIBUIDORA DE PRODUTOS ALIMENTÍCIOS HERNANDES LTDA', 'DIVINA DIETA DA ASSOCIAÇÃO DE PAIS E AMIGOS DOS EXCEPCIONAIS DE SÃO PAULO', 'DIZA COMERCIAL E IMPORTADORA LTDA', 'DOCES MIRAHY LTDA', 'DOCES TATITÂNIA LTDA', 'DOMINGOS COSTA INDÚSTRIAS ALIMENTÍCIAS S.A.', 'DOMINGOS COSTA INDÚSTRIAS ALIMENTÍCIAS SA', 'DORI ALIMENTOS S.A.', 'DR. OETKER BRASIL LTDA', 'DR. SCHAR AG/SPA', 'DR. SHAR AG/SPA', 'DUAS RODAS INDUSTRIAL LTDA', 'DUCOCO ALIMENTOS S/A', 'DUNGA PRODUTOS ALIMENTÍCIOS LTDA', 'DUNGA PRODUTOS ALIMENTÍCIOS LTDA', 'DUNGA PRODUTOS ALIMENTÍCIOS LTDA', 'EBBA S/A - EMPRESA BRASILEIRA DE BEBIDAS E ALIMENTOS S/A', 'EBBA S/A - EMPRESA BRASILEIRA DE BEBIDAS E ALIMENTOS S/A', 'EBBA S/A- EMPRESA BRASILEIRA DE BEBIDAS E ALIMENTOS S/A', 'EDENILSON PEREIRA RODRIGUES COMÉRCIO DE FEIJÃO EIRELLI', 'EDER C GOMES DE OLIVEIRA (ARCO ÍRIS POLPAS)', 'EDER C. GOMES DE OLIVEIRA', 'EIC DO BRASIL IND. E COM. DE ALIMENTOS S/A', 'EIC DO BRASIL IND. E COM. DE ALIMENTOS S/A', 'ELOS FRUTI ENVASAMENTO E EMPACOTAMENTO EIRELI', 'ENERGY COMERCIAL IMPORTADORA E EXPORTADORA LTDA', 'ENTREPOSTO DE CARNES E DERIVADOS MULTIMEAT IND. E COM.DE ALIM.LTDA', 'Equilibre Indústria e Comércio de Alimentos Ltda', 'Equilibre Indústria e Comércio de Alimentos Ltda.', 'F DOTTO & CIA LTDA', 'F-CORRECTA IND. E COM. LTDA', 'F. BAPTISTELLA & CIA LTDA', 'F. DOTTO E CIA LTDA.', 'FABRICA DE LATICÍNIOS IND. E COM. ALIMENTÍCIOS FRUTAP LTDA', 'FABRICA DE LATICÍNIOS LEITE FAZENDA BELA VISTA', 'FABRICA DE LATICÍNIOS LEITE FAZENDA BELA VISTA LTDA', 'FALC COMERCIAL DE ALIMENTOS LTDA - EPP', 'FAZENDA NOVA ALIANÇA', 'FEA FOODS COM E IND DE PRODUTOS ALIMENTÍCIOS LTDA ME', 'FEA FOODS COMÉRCIO E INDÚSTRIA DE PRODUTOS ALIMENTÍCIOS LTDA', 'FECULARIA COLI LTDA', 'FECULARIA COLI LTDA EPP', 'FECULARIA NOSSA SENHORA DAS DORES LTDA.', 'FEINKOST', 'FEINKOST IND. E COM. DE ALIMENTOS LTDA', 'FEINKOST IND. E COM. DE ALIMENTOS LTDA', 'FEMAGAM DO VALLE DISTRIBUIDORA DE CEREAIS LTDA', 'FF IND E COM DE CARNES E DERIVADOS LTDA', 'FHOM IND. COM. E BEM. DE PRODUTOS LTDA', 'FHOM INDÚSTRIA COMÉRCIO E EMB DE PRODUTOS ALIMENTÍCIOS LTDA', 'FOOD BRANDS INDÚSTRIA DE PRODUTOS ALIMENTÍCIOS S A', 'FRANGO DM - INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'FREDERICO GREGIO FILHO', 'FRESENIUS KABI', 'FRESKITO PRODUTOS ALIMENTÍCIOS', 'FRESKITO PRODUTOS ALIMENTÍCIOS LTDA', 'FRIBOI - JBS S/A', 'FRIGBRASIL COMERCIAL DE CARNES E ALIMENTOS LTDA', 'FRIGORÍFICO E ATACADISTA DE ALIMENTOS MORRO GRANDE EIRELI ENTREPOSTO DE CARNES E DERIVADOS LTDA', 'FRIGORÍFICO EVEREST LTDA', 'FRIGORÍFICO NOSSA SENHORA DA SAÚDE LTDA', 'FRIMESA COOPERATIVA CENTRAL - FÁBRICA DE LATICÍNIOS', 'FRIMESA COOPERATIVA CENTRAL - USINA DE BENEFICIAMENTO', 'FRIOLINS INDÚSTRIA E COMÉRCIO DE PESCADOS LTDA', 'FRUTTI LIFE INDUSTRIA E COMERCIO DE SUCOS EIRELI', 'FUGINI ALIMENTOS LTDA', 'Femagem do Valle Distribuidora', 'Frigorífico Everest LTDA.', 'Frigorífico Everest LTDA.', 'Frigorífico Everest LTDA.', 'Frigorífico Everest LTDA.', 'Frigorífico Everest LTDA.', 'Friolins PESCADOS LTDA.', 'Fumacense Alimentos Ltda.', 'Fumacense Alimentos Ltda.', 'FÁBRICA DE LATICÍNIOS MASGOVI IND. COM. SERV. IMP. E EXP. LTDA', 'FÁBRICA DE LATICÍNIOS MOCOCA S A PRODUTOS ALIMENTÍCIOS', 'FÁBRICA DE LATICÍNIOS VITAO ALIMENTOS LTDA', 'Fábrica de Laticícios Vitao Alimentos Ltda.', 'Fábrica de Laticínios Campo Verde Alimentos Ltda', 'GADKIN ALIMENTOS S/A', 'GDC ALIMENTOS S.A.', 'GELITA DO BRASIL LTDA', 'GENERAL MILLS BRASIL ALIMENTOS LTDA', 'GHADIEH & CIA LTDA', 'GOEMIL S/A', 'GOIASMINAS INDUSTRIA DE LATICÍNIOS LTDA', 'GOIÁS VERDE ALIMENTOS LTDA', 'GOIÁS VERDE ALIMENTOS LTDA', 'GRADIFF MAGDIEL COMÉRCIO DE CEREAIS LTDA', 'GRAN REAL', 'GRAN REAL ALIMENTOS LTDA', 'GRANI AMICI IND. E COM. DE ALIMENTOS LTDA', 'GRANJA BRASIL ROBERTO K. TSURO', 'GRANJA BRASIL ROBERTO K. TSURO', 'GRANO BRASILIS LTDA', 'GREENY DISTRIBUIDORA DE ALIMENTOS COM. E DISTRIBUIÇÃO EIRELI', 'GRINGS & FILHOS LTDA', 'GRINGS & FILHOS LTDA', 'GRINGS & FILHOS LTDA', 'GTFOODS', 'General Mills Brasil Alimentos LTDA', 'General Mills Brasil Alimentos LTDA', 'Goias Verde Alimentos Ltda', 'Grani Amici Ind. e Com. Alimentos Ltda.', 'Grani Amici Ind. e Com. de Alimentos S.A.', 'Grani Amici Ind. e Com. de Alimentos S.A.', 'Grani Amici Ind. e Com. de Alimentos S.A.', 'Grani Amici Ind. e Com. de alimentos S.A', 'Grani Amici Ind. e Com.de Alimentos S.A.', 'H.E. INDÚSTRIA E COMÉRCIO DE LATICÍNIOS LTDA', 'HEINZ BRASIL S A', 'HELCE - INDUSTRIA DE PRODUTOS ALIMENTÍCIOS LTDA', 'HERO BRASIL S A', 'HERO BRASIL S.A', 'HIBRA COMÉRCIO DE ALIMENTOS LTDA', 'HIBRA COMÉRCIO DE ALIMENTOS LTDA', 'HIBRA COMÉRCIO DE ALIMENTOS LTDA', 'HIBRA COMÉRCIO DE ALIMENTOS LTDA', 'HIBRA COMÉRCIO DE ALIMENTOS LTDA.', 'HIPER HOLDING LTDA', 'HIPER HOLDING LTDA', 'HORIZONTE AMIDOS', 'HORMEL', 'IBS - INDUSTRIA BRASILEIRA DE SUCOS LTDA', 'IBS - INDÚSTRIA BRASILEIRA DE SUCOS LTDA', 'IBS - INDÚSTRIA BRASILEIRA DE SUCOS LTDA', 'IBS - INDÚSTRIA BRASILEIRA DE SUCOS LTDA', 'IBS - INDÚSTRIA BRASILEIRA DE SUCOS LTDA', 'ID 2 - MOINHO BALESTRIN LTDA.', 'IGLU COMERCIAL E IMPORTADORA LTDA', 'INDUSTRIA E COMERCIO DE ALIMENTOS IANA - LTDA', 'INDUSTRIA E COMERCIO DE LATICINIOS FLORESCER LTDA', 'INDUSTRIA E COMÉRCIO DE ALIMENTOS FUCHINA', 'INDUSTRIAS ALIMENTÍCIAS LIANE LTDA', 'INDÚSTRIA DE MASSAS ALIMENTÍCIAS ROSANE LTDA', 'INDÚSTRIA DE POLPA E CONSERVAS VAL LTDA', 'INDÚSTRIA DE PRODUTOS ALIMENTÍCIOS MAVALÉRIO LTDA', 'INDÚSTRIA DE PRODUTOS DE MANDIOCA SANTA LÚCIA LTDA-ME', 'INDÚSTRIA DE TORRONE N S DE MONTEVERGINE LTDA', 'INDÚSTRIA DE TORRONE N.S. DE MONTEVERGINE LTDA', 'INDÚSTRIA E COMÉRCIO DE FRUTAS RICAELI LTDA', 'INDÚSTRIA E COMÉRCIO DE LATICÍNIOS FLORESCER LTDA.', 'INDÚSTRIA E COMÉRCIO JOSÉ DE PAULA S A', 'INDÚSTRIAS ALIMENTÍCIAS LIANE LTDA', 'INTERBRASIL ALIMENTOS INDUSTRIA EXPORTAÇÃO IMPORTAÇÃO EIRELI', 'INTERCONTINENTAL FOODS COMÉRCIO DE ALIMENTOS LTDA', 'INVESTALIMENTOS S A', 'INÁCIO YOSHIHARU SHIDA', 'IRANO ALIMENTOS', 'IRMÃOS TREVISAN S A INDÚSTRIA E COMÉRCIO E AGRICULTURA', 'ITAMBÉ ALIMENTOS S/A', 'ITAMBÉ ALIMENTOS S/A', 'Indústria de massas alimentícias Rosane LTDA', 'Indústria de massas alimentícias Rosane LTDA.', 'J A COMÉRCIO DE GÊNEROS ALIMENTÍCIOS E SERVIÇOS EIRELI', 'J C OLIVEIRA & FILHOS LTDA', 'J MACÊDO', 'J MACÊDO S A', 'J W GUARNIERI CEREAIS LTDA', 'J.A. COMÉRCIO DE GÉNEROS ALIMENTÍCIOS E SERVIÇOS EIRELI', 'JACIARA COMÉRCIO E INDÚSTRIA DE ALIMENTOS LTDA', 'JAGUAFRANGOS INDUSTRIA E COMERCIO DE ALIMENTOS LTDA.', 'JASMINE COM. DE PRODUTOS ALIMENTICIOS LTDA', 'JASMINE COM. DE PRODUTOS ALIMENTICIOS LTDA.', 'JASMINE COMÉRCIO DE PRODUTOS ALIMENTÍCIOS LTDA', 'JAV INDÚSTRIA DE ALIMENTOS LTDA', 'JBS', 'JBS AVES LTDA', 'JHB VITA SUCOS NATURAIS LTDA', 'JHB VITA SUCOS NATURAIS LTDA EPP', 'JJ FOODS LTDA', 'JOSAPAR', 'JOSAPAR - JOAQUIM OLIVEIRA S.A PARTICIPAÇÕES', 'JOSAPAR - JOAQUIM OLIVEIRA S.A PARTICIPAÇÕES', 'JOSAPAR-JOAQUIM OLIVEIRA SA PARTICIPAÇÕES', 'JOTA ALIMENTO LTDA', 'JOTA ALIMENTOS EIRELI', 'JOTA ALIMENTOS LTDA', 'JOTA ALIMENTOS LTDA', 'JOVANIL ILEDES LAMBERT DE SOUZA & CIA LTDA', 'JR ALIMENTOS LTDA', 'JR PEREIRA MAGALHÃES ME', 'Jasmine Comércio de produtos alimentícios Ltda.', 'Josapar Joaquim Oliveira S.A. Participações', 'KAIZEN ALIMENTOS LTDA', 'KALEFA INDUSTRIA DE COMERCIO DE PESCADOS', 'KALEFA INDUSTRIA E COMERCIO DE PESCADOS LTDA', 'KALEFA INDUSTRIA E COMERCIO DE PESCADOS LTDA', 'KALEFA INDUSTRIA E COMERCIO DE PESCADOS LTDA', 'KALEFA INDÚSTRIA E COMÉRCIO DE PESCADOS LTDA.', 'KALEFA INDÚSTRIA E COMÉRCIO DE PESCADOS LTDA.', 'KALEFA INDÚSTRIA E COMÉRCIO DE PESCADOS LTDA.', 'KEMY DO BRASIL LTDA', 'KERLAC INDÚSTRIA E COMÉRCIO DE LATICÍNIOS LTDA.', 'KI-GRÃOS DISTRIBUIDORA DE ALIMENTOS EIRELI', 'KIBELLO ALIMENTOS NATURAIS LTDA', 'KIM', 'KIM NETO IND. E COM. DE PANIFICAÇÃO LTDA', 'KIM NETO IND. E COM. DE PANIFICAÇÃO LTDA.', 'KIM NETO IND. E COM. DE PANIFICAÇÃO LTDA.', 'KIM NETO IND. E OCM. DE PANIFICAÇÃO LTDA.', 'KIM NETO INDUSTRIA E COMERCIO DE PANIFICAÇÃO LTDA', 'KIM NETOIND. E COM. DE PANIFICAÇÃO LTDA.', 'KOBBER ALIMENTOS LTDA', 'KOBBER ALIMENTOS LTDA', 'KORIN AGROPECUÁRIA LTDA', 'KWB FISHING FABRICAÇÃO DE PESCADOS EIRELLI', 'L. PRAXEDES GOMES', 'LACTALIS DO BRASIL - COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO DE LATICÍNIOS LTDA. ENTREPOSTO USINA.', 'LACTOJARA IND. E COMÉRCIO DE LATICÍNIOS S.A.', 'LATICINIO VALE DO PARDO LTDA', 'LATICINIOS DA ROLT', 'LATICINIOS SANTA RITA LTDA', 'LATICÍNIOS BELA VISTA LTDA USINA DE BENEFICIAMENTO', 'LATICÍNIOS CATUPIRY LTDA', 'LATICÍNIOS LATCO LTDA', 'LATICÍNIOS LATCO LTDA', 'LATICÍNIOS TIROLEZ LTDA', 'LATICÍNIOS VERDE CAMPO', 'LATICÍNIOS VERDE CAMPO LTDA', 'LBS FOODS', 'LBS FOODS EIRELLI - EPP', 'LCA IND. E COM. DE PROD. ALIM. LTDA', 'LEFORTH ALIMENTOS LTDA EPP', 'LEITESOL INDÚSTRIA E COMÉRCIO S.A.', 'LEONDENIS DE OLIVEIRA ALHOS - ME', 'LEPAN INDÚSTRIA DE ALIMENTOS LTDA - EPP', 'LEÃO ALIMENTOS E BEBIDAS LTDA', 'LEÃO ALIMENTOS E BEBIDAS LTDA', 'LGP de Castro ME', 'LIFE INDÚSTRIA E COMÉRCIO DE SUCOS LTDA - ME', 'LIGHTSWEET - IND. E COM. DE ALIMENTOS LTDA.', 'LIOTECNICA TECNOLOGIA EM ALIMENTOS S/A', 'LMB DISTRIBUIDORA E IMPORTADORA DE PRODUTOS ALIMENTÍCIOS', 'LOUIS DREYFUS COMPANY BRASIL S.A', 'LOUIS DREYFUS COMPANY BRASIL S.A.', 'LOUIS DREYFUS COMPANY BRASIL S/A', 'LUA NOVA IND. E COM. DE PRODUTOS ALIMENTÍCIOS LTDA', 'Leondenis de Oliveira Alhos - ME', 'M CARDOSO INDÚSTRIA, LOGÍSTICA E DISTRIBUIÇÃO DE ALIMENTOS E BEBIDAS EIRELI', 'M DIAS BRANCO S A', 'M H CEREALISTA EIRELI', 'M W A COM DE PRODUTOS ALIMENTÍCIOS LTDA', 'M. DIAS BRANCO S.A', 'MAGALUSI COMÉRCIO DE GÊNEROS ALIMENTÍCIOS LTDA', 'MAGRO', 'MANTIQUEIRA ALIMENTOS LTDA', 'MARATÁ SUCOS DO NORDESTE LTDA', 'MARCON COMÉRCIO DE CEREAIS LTDA', 'MARFIL COMÉRCIO E DISTRIBUIDORA DE ALIMENTOS LTDA', 'MARILAN ALIMENTOS S/A', 'MASF IND E COM DE PANIFICAÇÃO LTDA', 'MASSAS ALIMENTÍCIAS DA ROZ LTDA', 'MASTER KUKA PRODUTOS ALIMENTÍCIOS E REPRESENTAÇÃO', 'MAXUL ALIMENTOS LTDA', 'MAXUL ALIMENTOS LTDA', 'MAXUL ALIMENTOS LTDA', 'MEAD JOHNSON NUTRICIONALES DE MÉXICO, S DE R.L. DE C.V.', 'MEAD JONHSON NUTRITION', 'MEAT FOODS ALIMENTOS LTDA - EPP', 'MEATFOODS ALIMENTOS EIRELI', 'MECANO PACK EMBALAGENS S/A', 'MEGA SUCO PORDUTOS ALIMENTICIOS LTDA', 'MELITTA DO BRASIL INDÚSTRIA E COMÉRCIO LTDA', 'MELLORE ALIMENTOS LTDA', 'MERCOGRÃOS IMPORTAÇÃO E EXPORTAÇÃO LTDA', 'MEZATO FOODS', 'MICHI FOODS PROD COM DIST IMP E EXP', 'MILK VITTA COMÉRCIO E INDÚSTRIA LTDA', 'MILKY VITTA COMÉRCIO E INDÚSTRIA LTDA', 'MITSUKO UEHARA YOSHIOKA NÚCLEO COLONIAL DE GUATAPARA', 'MITUAKI SHIGUENO', 'MOINHO ARAPONGAS S A', 'MOINHO GLOBO ALIMENTOS S.A', 'MOINHO HORTOLÂNDIA EIRELI', 'MOINHO NORDESTE', 'MOINHO PAULISTA S/A', 'MOINHO SPECIAL ARTE E COZINHA LTDA', 'MOLINOS RIO DE LA PLATA S A', 'MOLINOS RIO DE LA PRATA SA URIBURU', 'MONAMA INDÚSTRIA E COMÉRCIO DE ALIMENTOS EIRELI EPP', 'MONDELEZ BRASIL LTDA', 'MORRO GRANDE DISTRIBUIDORA DE ALIMENTOS LTDA', 'MOSMANN ALIMENTOS LTDA', 'MOSMANN ALIMENTOS LTDA', 'MSDE IND. E COMÉRCIO DE PROD. ALIMENTÍCIOS', 'MULTICOM COMÉRCIO MULTIPLO DE ALIMENTOS LTDA', 'MULTIMEAT INDUSTRIA E COMERCIO DE ALIMENTOS LTDA', 'MULTMEAT', 'Mais Leve Alimentação Saudável Ltda', 'Mais Leve Alimentação Saudável Ltda', 'Maratá Sucos do Nordeste Ltda.', 'Massas Alimentícias Da Roz Ltda', 'Mult Beef Comercial Eireli', 'Mult Beef Comercial LTDA', 'MÁRCIA MARIA PENEDO NASCIMENTO ME', 'NAMORADO SA', 'NASCIMENTO E FILHO IND E COM DE DOCES LTDA', 'NAT CEREAIS E ALIMENTOS LTDA', 'NATI ALIMENTOS LTDA', 'NAZINHA PRODUTOS ALIMENTÍCIOS LTDA', 'NEILAR INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'NELSON IRANO', 'NESTLE BRASIL LTDA', 'NESTLÉ', 'NESTLÉ BRASIL LTDA', 'NESTLÉ S.A', 'NINFA INDÚSTRIA DE ALIMENTOS LTDA', 'NOVA ITAQUA COMÉRCIO E EMPACOTAMENTO DE CEREAIS LTDA', 'NOVA MIX INDUSTRIAL E COMERCIAL DE ALIMENTOS LTDA', 'NS ALIMENTOS LTDA', 'NUTREI INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'NUTREL INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'NUTRI-SUCO INDÚSTRIA E COMÉRCIO LTDA', 'NUTRICIA CUIJK BV. (EMPRESA DO GRUPO DANONE GROTESTRAAT 91- 5431 DJ CUIJK - HOLANDA)', 'NUTRICIA NV', 'NUTRIL', 'NUTRIL', 'NUTRIMENTAL S.A INDÚSTRIA E COMÉRCIO DE ALIMENTOS', 'NUTRITION & SANTÉ DO BRASIL LTDA', 'Nestlé Nordeste Alimentos e Bebidas Ltda', 'OCE, AMIDO DE MILHO, ÓLEO DE GIRASSOL, MOSTARDA, SAL E ESPESSANTE INS 46 6', 'ODEBRECHT COMÉRCIO DE INDÚSTRIA DE CAFÉ', 'ODEBRECHT COMÉRCIO E INDÚSTRIA DE CAFÉ LTDA', 'OLVEBRA INDUSTRIAL S.A.', 'ORIZICOLA DO VALE LTDA', 'PAN CHRISTIAN INDÚSTRIA E COMÉRCIO DE PRODUTOS ALIMENTÍCIOS', 'PANCO', 'PANDURATA ALIMENTOS LTDA', 'PANIFICADORA E DISTRIBUIDORA RE- ALI JUNIOR', 'PANIFICADORA E DISTRIBUIDORA RE- ALI JÚNIOR', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR LTDA', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR LTDA', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR LTDA', 'PANIFICADORA E DISTRIBUIDORA RE-ALI JUNIOR LTDA', 'PARATI IND E COM DE ALIMENTOS LTDA', 'PARATI S.A', 'PARATI S.A.', 'PASTIFÍCIO SANTA AMÁLIA S.A', 'PASTIFÍCIO SANTA AMÁLIA SA', 'PASTIFÍCIO SELMI', 'PASTIFÍCIO SELMI S A', 'PASTIFÍCIO SELMI S.A', 'PASTIFÍCIO SELMI S.A', 'PASTIFÍCIO SELMI S.A', 'PASTIFÍCIO SELMI S/A', 'PICININ ALIMENTOS LTDA', 'PILECCO NOBRE ALIMENTOS LTDA', 'PIRAPEIXES - COMÉRCIO ATACADISTA DE PESCADOS LTDA - ME', 'PLUSVAL AGROAVÍCOLA LTDA', 'POLENGHI INDÚSTRIAS ALIMENTÍCIAS LTDA', 'PREDILECTA ALIMENTOS LTDA', 'PREDILECTA ALIMENTOS LTDA', 'PROCOOKING INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA.', 'PRODIET', 'PRODIET NUTRIÇÃO CLÍNICA LTDA.', 'PRODIET NUTRIÇÃO CLÍNICA LTDS', 'PRODUTO SÃO JOSÉ', 'PRODUTOS DE MANDIOCA SÃO PAULO', 'PRODUTOS DE MANDIOCA SÃO PAULO LTDA', 'Pantera alimentos Ltda.', 'Pastifício Santa Amália S/A', 'Pastifício Santa Amália S/A', 'Pastifício Santa Amália S/A', 'PÃO DE LIZ LTDA ME', 'QUALICOCO', 'QUALICOCO LTDA', 'QUALICÔCO LTDA', 'QUATRELATI ALIMENTOS LTDA', 'RACINE DO BRASIL PRODUTOS ALIMENTÍCIOS', 'RAMPINELLI ALIMENTOS LTDA', 'RAROZ AGROINDÚSTRIA DO SUL LTDA', 'RB DE GARÇA COM E IND DE ALIMENTOS EIRELI', 'REALCAFÉ SOLÚVEL DO BRASIL S.A', 'REFINARIA DE SAL GARÇA LTDA', 'REFINARIA DE SAL GARÇA LTDA', 'REFINAÇÃO E MOAGEM DE SAL SANTA HELENA LTDA', 'REFINORTE - REF. DE SAL DUNORTE INDUSTRIA E COMÉRCIO LTDA.', 'REFINORTE - REFINARIA DE SAL DUNORTE', 'REFINORTE - REFINARIA DE SAL DUNORTE INDÚSTRIA E COMÉRCIO LTDA', 'REI DA ALMONDEGA INDÚSTRIA E COMÉRCIO DE PRODUTOS ALIMENTÍCIOS EIRELI', "RENK'S INDUSTRIAL LTDA", 'RET PRODUTOS ALIMENTICIOS LTDA.', 'RET PRODUTOS ALIMENTÍCIOS EIRELI', 'RET PRODUTOS ALIMENTÍCIOS LTDA', 'RF FOODS DERIVADOS DE CARNE LTDA – ME UNIDADE DE BENEFICIAMENTO DE CARNE E PRODUTOS CÁRNEOS', 'RIO BRANCO ALIMENTOS S A', 'RIOLAT ALIMENTOS LTDA FÁBRICA DE LATICÍNIOS', 'RIVOLI INDÚSTRIA E COMÉRCIO LTDA', 'ROFRAN FOODS COMÉRCIO E INDÚSTRIA DE PRODUTOS LÁCTEOS LTDA', 'ROSINA ALIMENTOS EIRELI', 'RUSTON ALIMENTOS LTDA', 'Roots to go', 'S.H.A Comércio de Alimentos LTDA', 'SABOR ALTERNATIVO PRODUTOS NATURAIS LTDA', 'SABOR ALTERNATIVO PRODUTOS NATURAIS LTDA', 'SABOR FINO COMÉRCIO E INDÚSTRIA LTDA', 'SANNA COMÉRCIO DE ALIMENTOS LTDA', 'SANNABOM ALIMENTOS LTDA', 'SANTA MONICA IND E COM LTDA', 'SANTI IND. E COM. LTDA', 'SEAL INDÚSTRIA E COMÉRCIO DE ALIMENTOS EIRELI', 'SEARA ALIMENTOS LTDA', 'SEARA INDÚSTRIA E COMÉRCIO DE PRODUTOS AGROPECUÁRIOS LTDA', 'SEM GLÚTEN MARILIS PROD. ALIM. LTDA', 'SEM GLÚTEN MARILIS PRODUTOS ALIMENTÍCIOS LTDA', 'SHA COMÉRCIO DE ALIMENTOS LTDA', 'SHA COMÉRCIO DE ALIMENTOS LTDA', 'SHEFA- USINA DE BENEFICIAMENTO AGROPECUÁRIA TUIUTI SA', 'SHS INTERNATIONAL LTD', 'SIL-BOM', 'SIOL ALIMENTOS LTDA.', 'SIVIERO ALIMENTOS E SEMENTES LTDA', 'SO FRUTAS ALIMENTOS LTDA', 'SOBASICO  INDÚSTRIA E COMÉRCIO DE ALIMENTOS LTDA', 'SPECHT - PRODUTOS ALIMENTÍCIOS LTDA', 'STELLA D ORO ALIMENTOS LTDA', 'STELLA D ORO ALIMENTOS LTDA', "STELLA D'ORO ALIME4NTOS LTDA", "STELLA D'ORO ALIMENTOS LTDA", 'STEVIAFARMA INDUSTRIAL S A', 'STEVIAFARMA INDUSTRIAL S/A', 'SUSTENTARE PRODUTOS ALIMENTICIOS LTDA', 'SUSTENTARE PRODUTOS ALIMENTICIOS LTDA', 'SUVALAN SUCOS DE FRUTAS INDUSTRIA E COMERCIO LTDA', 'SVILI INDUSTRIAL LTDA', 'Sannabom Alimentos Ltda.', 'Sannabom Alimentos Ltda.', 'Sora Alimentos Ltda', 'Stella d´oro Alimentos Ltda', 'Suco de fruta Suvalan', 'SÃO BRAZ SA INDÚSTRIA E COMÉRCIO DE ALIMENTOS', 'SÃO JOÃO ALIMENTOS LTDA', 'SÉSAMO REAL IND. E COM. DE PROD. ALIMENTÍCIOS LTDA', 'SÓ PESCA INDÚSTRIA E COMÉRCIO DE PEIXES LTDA', 'T SABOR ALIMENTOS EIRELI EPP', 'T SABOR ALIMENTOS EIRELLI  EPP', 'T. SABOR ALIMENTOS', 'TANGARÁ IMPORTADORA E EXPORTADORA S.A.', 'TECPOLPA INDÚSTRIA E COMÉRCIO DE SUCOS LTDA', 'TIGRE ALIMENTOS DO BRASIL EIRELI', 'TONDO S A', 'TONDO S.A.', 'TONYELCY IND COM DE BISCOITOS LTDA - ME', 'TORG ALIMENTOS INDÚSTRIA E COMÉRCIO LTDA', 'TRES FAZENDAS COMERCIAL DE CEREAIS EIRELI - EPP', 'TRES FAZENDAS COMERCIAL DE CEREAIS EIRELLI - EPP', 'TREVO LÁCTEOS S A', 'TROPICAL INDÚSTRIA DE ALIMENTOS S.A.', 'TROPICAL INDÚSTRIA DE ALIMENTOS SA', 'TUI ALIMENTOS LTDA', 'Tigre Alimentos do Brasil EIRELI', 'UNIDADE DE BENEFICIAMENTO DE OVOS E DERIVADOS IVAN KENTARO KAMIMURA - EPP', 'UNIFLAVORS INGREDIENTES ALIMENTÍCIOS LTDA', 'UNILEVER BRASIL INDUSTRIAL LTDA', 'UNILEVER BRASIL INDUSTRIAL LTDA', 'UNIU ALIMENTOS LTDA', 'UP INDUSTRIES  E IMPORTADO E DISTRIBUIDO POR BIOLAB SANUS FARMACÊUTICA LTDA', 'URBANO AGROINDUSTRIAL LTDA', 'USINA ALTO ALEGRE S.A. AÇÚCAR E ÁLCOOL', 'USINA DE BENEFICIAMENTO CELLES CORDEIRO ALIMENTOS LTDA', 'USINA DE BENEFICIAMENTO COOPERATIVA AGROPECUÁRIA DO VALE DO SAPUCAÍ LTDA', 'USINA DE BENEFICIAMENTO COOPERATIVA SANTA CLARA LTDA', 'USINA DE BENEFICIAMENTO COOPERATIVA SANTA CLARA LTDA', 'USINA DE BENEFICIAMENTO COOPERATIVA SANTA CLARA LTDA', 'USINA DE BENEFICIAMENTO COOPERATIVA SANTA CLARA LTDA', 'USINA DE BENEFICIAMENTO GOIASMINAS INDÚSTRIA DE LATICÍNIOS LTDA', 'USINA DE BENEFICIAMENTO INDÚSTRIA E COMÉRCIO DE LATICÍNIOS PEREIRA LTDA', 'USINA DE BENEFICIAMENTO LATICÍNIOS PORTO ALEGRE IND. COM. S/A', 'USINA DE BENEFICIAMENTO LATICÍNIOS PORTO ALEGRE IND. E COM. S.A.', 'USINA DE BENEFICIAMENTO LATICÍNIOS PORTO ALEGRE IND. E COM. S.A..', 'USINA DE BENEFICIAMENTO LATICÍNIOS PORTO ALEGRE IND. E COM. SA', 'USINA DE BENEFICIAMENTO LATICÍNIOS PORTO ALEGRE INDUSTRIA E COMERCIO LTDA', 'USINA DE BENEFICIAMENTO LATICÍNIOS PORTO ALEGRE INDÚSTRIA E COMÉRCIO S.A.', 'USINA DE LATICÍNIOS JUSSARA S.A', 'VALE FÉRTIL INDUSTRIAS ALIMENTÍCIAS LTDA', 'VALE FÉRTIL INDÚSTRIAS ALIMENTÍCIAS LTDA', 'VIBRA AGROINDUSTRIAL S/A', 'VIDA VEG LTDA', 'VIGOR', 'VINÍCOLA CAMPESTRE', 'VINÍCOLA CAMPESTRE LTDA', 'VITALIN ALIMENTOS LTDA', 'VITAO ALIMENTOS LTDA', 'VOLKMANN ALIMENTOS LTDA', 'W N LIDER COM E DISTRIB DE PRODUTOS ALIMENTICIOS LTDA', 'W PESQUISA , TECNOLOGIA E INDUSTRIA DE ALIMENTOS EIRELI', 'W. AMARAL INDÚSTRIA E COMÉRCIO LTDA.', 'WMA ALIMENTOS', 'WMA BRASIL ALIMENTOS', 'WOW NUTRITION INDÚSTRIA E COMÉRCIO S.A', 'ZANCHETTA ALIMENTOS LTDA', 'pantera alimentos ltda']

combinacoes_fabricantes = []
fabricantes = [fabricante.nome for fabricante in Marca.objects.all()]
for fabricante in fabricantes:
    combinacao = get_close_matches(fabricante, fabricantes, cutoff=0.8)
    combinacao.sort()
    if len(combinacao) > 1 and combinacao not in combinacoes_fabricantes:
        combinacoes_fabricantes.append(combinacao)
