# Generated by Django 2.2.13 on 2020-12-18 20:16

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_auto_20201207_1655'),
    ]

    operations = [
        UnaccentExtension()
    ]
