# Generated by Django 2.2.6 on 2019-12-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceirizada', '0001_initial'),
        ('dados_comuns', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='terceirizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lotes', to='terceirizada.Terceirizada'),
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_gestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lotes', to='escola.TipoGestao'),
        ),
        migrations.AddField(
            model_name='escola',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dados_comuns.Contato'),
        ),
        migrations.AddField(
            model_name='escola',
            name='diretoria_regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas', to='escola.DiretoriaRegional'),
        ),
        migrations.AddField(
            model_name='escola',
            name='idades',
            field=models.ManyToManyField(blank=True, to='escola.FaixaIdadeEscolar'),
        ),
        migrations.AddField(
            model_name='escola',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='escola.Lote'),
        ),
        migrations.AddField(
            model_name='escola',
            name='periodos_escolares',
            field=models.ManyToManyField(blank=True, to='escola.PeriodoEscolar'),
        ),
        migrations.AddField(
            model_name='escola',
            name='tipo_gestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.TipoGestao'),
        ),
        migrations.AddField(
            model_name='escola',
            name='tipo_unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.TipoUnidadeEscolar'),
        ),
    ]
