# Generated by Django 2.0.13 on 2019-09-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20190902_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='codigo_codae',
        ),
    ]
