# Generated by Django 2.2.8 on 2020-01-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0004_auto_20191210_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracaoQuantidadeAlunosPorEscolaEPeriodoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_alunos_atual', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de alunos atual')),
                ('quantidade_alunos_alterada', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de alunos alterada')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='escola_log_alteracao', to='escola.Escola')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='periodo_log_alteracao', to='escola.PeriodoEscolar')),
            ],
            options={
                'verbose_name': 'Log Alteração quantidade de alunos',
                'verbose_name_plural': 'Logs Alterações quantidade de alunos',
                'ordering': ('criado_em',),
            },
        ),
    ]
