# Generated by Django 2.0.13 on 2019-10-08 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_auto_20190927_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretoriaregional',
            name='codigo_eol',
            field=models.CharField(default=None, max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diretoriaregional',
            name='iniciais',
            field=models.CharField(blank=True, max_length=10, verbose_name='Iniciais'),
        ),
        migrations.AlterField(
            model_name='codae',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='diretoriaregional',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='diretoria_regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas', to='escola.DiretoriaRegional'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='quantidade_alunos',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de alunos'),
        ),
        migrations.AlterField(
            model_name='faixaidadeescolar',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subprefeitura',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipogestao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
