# Generated by Django 2.2.8 on 2020-01-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_logalteracaoquantidadealunosporescolaeperiodoescolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='quantidade_alunos',
        ),
        migrations.AlterField(
            model_name='logalteracaoquantidadealunosporescolaeperiodoescolar',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_alteracao_quantidade_alunos', to='escola.Escola'),
        ),
        migrations.AlterField(
            model_name='logalteracaoquantidadealunosporescolaeperiodoescolar',
            name='periodo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_alteracao_quantidade_alunos', to='escola.PeriodoEscolar'),
        ),
    ]
