# Generated by Django 2.2.8 on 2020-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20200107_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logalteracaoquantidadealunosporescolaeperiodoescolar',
            options={'ordering': ('criado_em',), 'verbose_name': 'Log Alteração quantidade de alunos', 'verbose_name_plural': 'Logs de Alteração quantidade de alunos'},
        ),
        migrations.RenameField(
            model_name='logalteracaoquantidadealunosporescolaeperiodoescolar',
            old_name='quantidade_alunos_alterada',
            new_name='quantidade_alunos_para',
        ),
        migrations.RemoveField(
            model_name='logalteracaoquantidadealunosporescolaeperiodoescolar',
            name='quantidade_alunos_atual',
        ),
        migrations.AddField(
            model_name='logalteracaoquantidadealunosporescolaeperiodoescolar',
            name='quantidade_alunos_de',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de alunos anterior'),
        ),
    ]
