# Generated by Django 2.0.13 on 2019-10-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20191008_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='diretoria_regional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas', to='escola.DiretoriaRegional'),
            preserve_default=False,
        ),
    ]
