# Generated by Django 2.2.6 on 2019-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20191023_1503'),
        ('escola', '0007_auto_20191008_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codae',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='diretoriaregional',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='codae',
            name='vinculos',
            field=models.ManyToManyField(blank=True, related_name='CODAE', to='perfil.Vinculo'),
        ),
        migrations.AddField(
            model_name='diretoriaregional',
            name='vinculos',
            field=models.ManyToManyField(blank=True, related_name='diretorias_regionais', to='perfil.Vinculo'),
        ),
        migrations.AddField(
            model_name='escola',
            name='vinculos',
            field=models.ManyToManyField(related_name='escolas', to='perfil.Vinculo'),
        ),
    ]
