# Generated by Django 2.2.8 on 2020-01-20 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
