# Generated by Django 2.2.6 on 2019-10-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_auto_20191023_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codae',
            name='vinculos',
        ),
        migrations.RemoveField(
            model_name='diretoriaregional',
            name='vinculos',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='vinculos',
        ),
    ]
