# Generated by Django 2.2.6 on 2019-10-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_auto_20191024_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
    ]
