# Generated by Django 2.2.8 on 2020-02-19 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_faixaetaria_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudancafaixasetarias',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
