# Generated by Django 2.2.13 on 2020-09-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0017_escola_tipo_contagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='periodo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.PeriodoEscolar'),
        ),
    ]
