# Generated by Django 2.2.13 on 2020-09-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0022_endereco'),
        ('escola', '0018_aluno_periodo_escolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dados_comuns.Endereco'),
        ),
    ]
