# Generated by Django 2.2.13 on 2020-10-02 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0018_auto_20200924_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='codigo_eol',
            field=models.CharField(blank=True, max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Código EOL'),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='escola.Aluno')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Reponsáveis',
            },
        ),
    ]
