# Generated by Django 2.2.13 on 2020-10-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0021_auto_20201002_2156'),
        ('escola', '0019_auto_20201006_1406'),
    ]

    operations = [
    ]
