# Generated by Django 2.2.13 on 2021-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0026_logrotinadiariaalunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='codigo_codae',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Código CODAE'),
        ),
    ]
