# Generated by Django 2.2.13 on 2021-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0031_aluno_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaEscolaDeParaCodigoEolCodigoCoade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('planilha', models.FileField(help_text='Deve ser inserido um arquivo excel em formato xlsx<br> '
                                                        'O arquivo deve conter as colunas código eol e código '
                                                        'codae.<br> '
                                                        'O nome de cada coluna deve ser exatamente como a seguir:<br> '
                                                        '<b>codigo_eol</b> e <b>codigo_unidade</b>', upload_to='')),
                ('codigos_codae_vinculados', models.BooleanField(default=False, editable=False, verbose_name='Códigos Codae Vinculados?')),
            ],
            options={
                'verbose_name': 'Planilha De-Para: Código EOL x Código Codae',
                'verbose_name_plural': 'Planilhas De-Para: Código EOL x Código Codae',
            },
        ),
    ]
