# Generated by Django 2.2.13 on 2021-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0036_auto_20210915_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosmatriculadosperiodoescolaregular',
            name='tipo_turma',
            field=models.CharField(blank=True, choices=[('REGULAR', 1), ('PROGRAMAS', 3)], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logalunosmatriculadosperiodoescolaregular',
            name='tipo_turma',
            field=models.CharField(blank=True, choices=[('REGULAR', 1), ('PROGRAMAS', 3)], max_length=255, null=True),
        ),
    ]
