# Generated by Django 2.2.13 on 2021-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0038_auto_20210915_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosmatriculadosperiodoescola',
            name='tipo_turma',
            field=models.CharField(blank=True, choices=[('REGULAR', 1), ('PROGRAMAS', 3)], default='REGULAR', max_length=255),
        ),
    ]
