# Generated by Django 2.2.13 on 2021-10-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0042_diacalendario_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='tipo_gestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.TipoGestao'),
        ),
    ]
