# Generated by Django 2.2.13 on 2022-07-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0048_planilhaatualizacaotipogestaoescola'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprefeitura',
            name='codigo_eol',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código EOL'),
        ),
    ]
