# Generated by Django 2.2.13 on 2022-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0049_subprefeitura_codigo_eol'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoescolar',
            name='posicao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
