# Generated by Django 2.2.13 on 2022-11-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0054_tipounidadeescolar_pertence_relatorio_solicitacoes_alimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounidadeescolar',
            options={'ordering': ('iniciais',), 'verbose_name': 'Tipo de unidade escolar', 'verbose_name_plural': 'Tipos de unidade escolar'},
        ),
    ]
