# Generated by Django 2.2.13 on 2023-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0055_auto_20221128_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtualizaDadosAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_eol', models.CharField(max_length=50, verbose_name='Codigo EOL da escola')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='Status da requisição')),
                ('msg_erro', models.TextField(blank=True, verbose_name='Mensagem erro')),
            ],
        ),
    ]
