# Generated by Django 2.2.13 on 2022-12-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0055_auto_20221128_1146'),
        ('escola', '0054_auto_20221004_1716'),
    ]

    operations = [
    ]
