# Generated by Django 3.2.16 on 2023-03-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0056_logatualizadadosaluno'),
        ('escola', '0056_merge_20221219_2251'),
    ]

    operations = [
    ]
