# Generated by Django 3.2.18 on 2023-08-03 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0057_merge_20230303_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlunosMatriculadosFaixaEtariaDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_alunos_matriculados_por_faixa_etaria', to='escola.escola')),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.faixaetaria')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_alunos_matriculados_por_faixa_etaria', to='escola.periodoescolar')),
            ],
            options={
                'verbose_name': 'Log quantidade de alunos por faixa etária, dia e período',
                'verbose_name_plural': 'Logs quantidades de alunos por faixas etárias, dias e períodos',
                'ordering': ('criado_em',),
            },
        ),
    ]
