# Generated by Django 3.2.18 on 2023-08-11 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0022_solicitacaomedicaoinicial_ue_possui_alunos_periodo_parcial'),
        ('escola', '0058_logalunosmatriculadosfaixaetariadia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPeriodoParcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_periodo_parcial', to='escola.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_periodo_parcial', to='escola.escola')),
                ('solicitacao_medicao_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_periodo_parcial', to='medicao_inicial.solicitacaomedicaoinicial')),
            ],
            options={
                'verbose_name': 'Aluno no período parcial',
                'verbose_name_plural': 'Alunos no período parcial',
                'ordering': ('criado_em',),
            },
        ),
    ]
