# Generated by Django 3.2.18 on 2023-08-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0060_auto_20230815_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logalunosmatriculadosperiodoescola',
            options={'ordering': ('-criado_em',), 'verbose_name': 'Log Alteração quantidade de alunos regular e programa', 'verbose_name_plural': 'Logs de Alteração quantidade de alunos regulares e de programas'},
        ),
    ]
