# Generated by Django 4.1.12 on 2023-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0063_aluno_ciclo_aluno_desc_ciclo_aluno_desc_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logalunosmatriculadosperiodoescola',
            name='cei_ou_emei',
            field=models.CharField(choices=[('N/A', 'N/A'), ('CEI', 'CEI'), ('EMEI', 'EMEI')], default='N/A', max_length=4),
        ),
    ]
