# Generated by Django 4.2.7 on 2023-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0064_logalunosmatriculadosperiodoescola_cei_ou_emei'),
    ]

    operations = [
        migrations.AddField(
            model_name='logalunosmatriculadosperiodoescola',
            name='infantil_ou_fundamental',
            field=models.CharField(choices=[('N/A', 'N/A'), ('INFANTIL', 'INFANTIL'), ('FUNDAMENTAL', 'FUNDAMENTAL')], default='N/A', max_length=11),
        ),
    ]
