# Generated by Django 4.2.7 on 2023-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0065_logalunosmatriculadosperiodoescola_infantil_ou_fundamental"),
    ]

    operations = [
        migrations.AddField(
            model_name="codae",
            name="acesso_modulo_medicao_inicial",
            field=models.BooleanField(default=False),
        ),
    ]
