# Generated by Django 2.2.13 on 2022-10-26 11:56

from django.db import migrations, models
import django.db.models.deletion
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados_comuns', '0061_auto_20221026_1156'),
        ('terceirizada', '0007_auto_20211008_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('fluxocronograma_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dados_comuns.FluxoCronograma')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Cronograma')),
                ('contrato_uuid', models.CharField(blank=True, max_length=50, verbose_name='UUID do Contrato no SAFI')),
                ('contrato', models.CharField(blank=True, max_length=50, verbose_name='Contrato')),
                ('empresa_uuid', models.CharField(blank=True, max_length=50, verbose_name='UUID da Empresa no SAFI')),
                ('nome_empresa', models.CharField(blank=True, max_length=100, verbose_name='Nome da Empresa')),
                ('processo_sei', models.CharField(blank=True, max_length=50, verbose_name='Nº Processo SEI')),
                ('produto_uuid', models.CharField(blank=True, max_length=50, verbose_name='UUID do Produto no SAFI')),
                ('nome_produto', models.CharField(blank=True, max_length=100, verbose_name='Nome do Produto')),
                ('qtd_total_programada', models.FloatField(blank=True, null=True, verbose_name='Qtd Total Programada')),
                ('unidade_medida', models.CharField(blank=True, max_length=20, verbose_name='Unidade de Medida')),
                ('tipo_embalagem', models.CharField(blank=True, choices=[('CAIXA', 'Caixa'), ('FARDO', 'Fardo'), ('TUBET', 'Tubet')], max_length=15)),
                ('armazem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='terceirizada.Terceirizada')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, sme_terceirizadas.dados_comuns.behaviors.Logs, 'dados_comuns.fluxocronograma', models.Model),
        ),
        migrations.CreateModel(
            name='ProgramacaoDoRecebimentoDoCronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_programada', models.CharField(blank=True, max_length=50)),
                ('tipo_carga', models.CharField(blank=True, choices=[('PALETIZADA', 'Paletizada'), ('ESTIVADA_BATIDA', 'Estivada / Batida')], max_length=20)),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacoes_de_recebimento', to='pre_recebimento.Cronograma')),
            ],
            options={
                'verbose_name': 'Programação do Recebimento do Cromograma',
                'verbose_name_plural': 'Programações dos Recebimentos dos Cromogramas',
            },
        ),
        migrations.CreateModel(
            name='EtapasDoCronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('empenho_uuid', models.CharField(blank=True, max_length=50, verbose_name='UUID do Empenho no SAFI')),
                ('numero_empenho', models.CharField(blank=True, max_length=50, verbose_name='Número do Empenho')),
                ('etapa', models.CharField(blank=True, max_length=15)),
                ('parte', models.CharField(blank=True, max_length=15)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('total_embalagens', models.PositiveSmallIntegerField(blank=True, verbose_name='Total de Embalagens')),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='pre_recebimento.Cronograma')),
            ],
            options={
                'verbose_name': 'Etapa do Cronograma',
                'verbose_name_plural': 'Etapas dos Cronogramas',
            },
        ),
    ]
