# Generated by Django 2.2.13 on 2022-10-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapasdocronograma',
            name='total_embalagens',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de Embalagens'),
        ),
    ]
