# Generated by Django 2.2.13 on 2022-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0002_auto_20221031_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapasdocronograma',
            name='data_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Data Programada'),
        ),
    ]
