# Generated by Django 2.2.13 on 2022-11-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0003_etapasdocronograma_data_programada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapasdocronograma',
            options={'ordering': ('etapa', 'parte'), 'verbose_name': 'Etapa do Cronograma', 'verbose_name_plural': 'Etapas dos Cronogramas'},
        ),
    ]
