# Generated by Django 2.2.13 on 2022-11-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0004_auto_20221111_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapasdocronograma',
            options={'ordering': ('etapa', 'data_programada'), 'verbose_name': 'Etapa do Cronograma', 'verbose_name_plural': 'Etapas dos Cronogramas'},
        ),
    ]
