# Generated by Django 2.2.13 on 2022-11-24 09:43

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0062_auto_20221108_2127'),
        ('pre_recebimento', '0005_auto_20221117_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=150, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=150, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=150, verbose_name='Estado')),
                ('credenciado', models.BooleanField(default=False, verbose_name='Está credenciado?')),
                ('contatos', models.ManyToManyField(blank=True, to='dados_comuns.Contato')),
            ],
            options={
                'verbose_name': 'Laboratório',
                'verbose_name_plural': 'Laboratórios',
            },
        ),
    ]
