# Generated by Django 2.2.13 on 2022-11-28 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0006_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbalagemQld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('abreviacao', models.CharField(max_length=15, verbose_name='Abreviação')),
            ],
            options={
                'verbose_name': 'Embalagem QLD',
                'verbose_name_plural': 'Embalagens QLD',
            },
        ),
    ]
