# Generated by Django 3.2.16 on 2023-03-23 09:32

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0007_alter_cronograma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoalteracaocronograma',
            name='justificativa_dilog_cronograma',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa de solicitação pela dilog cronograma'),
        ),
        migrations.AlterField(
            model_name='solicitacaoalteracaocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=17, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='EM_ANALISE', name='CronogramaAlteracaoWorkflow', states=['EM_ANALISE', 'CRONOGRAMA_CIENTE', 'ACEITA', 'NEGADA'])),
        ),
    ]
