# Generated by Django 3.2.16 on 2023-04-12 01:02

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0008_alter_solicitacaoalteracaocronograma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoalteracaocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=17, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='EM_ANALISE', name='CronogramaAlteracaoWorkflow', states=['EM_ANALISE', 'CRONOGRAMA_CIENTE', 'APROVADO_DINUTRE', 'REPROVADO_DINUTRE', 'APROVADO_DILOG', 'REPROVADO_DILOG', 'ACEITA', 'NEGADA'])),
        ),
    ]
