# Generated by Django 2.2.13 on 2023-01-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0009_auto_20230117_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.NomeDeProdutoEdital'),
        ),
    ]
