# Generated by Django 2.2.13 on 2023-01-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0067_auto_20230125_1317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pre_recebimento', '0010_auto_20230118_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoCronogramaEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nova_data_programada', models.DateField(blank=True, null=True, verbose_name='Nova Data Programada')),
                ('nova_quantidade', models.FloatField(blank=True, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pre_recebimento.EtapasDoCronograma')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoCronograma',
            fields=[
                ('fluxoalteracaocronograma_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dados_comuns.FluxoAlteracaoCronograma')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motivo', multiselectfield.db.fields.MultiSelectField(choices=[('ALTERAR_DATA_ENTREGA', 'Alterar data de entrega'), ('ALTERAR_QTD_ALIMENTO', 'Alterar quantidade de alimento'), ('OUTROS', 'Outros')], max_length=48)),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa de solicitação pelo fornecedor')),
                ('numero_solicitacao', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número da solicitação')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_de_alteracao', to='pre_recebimento.Cronograma')),
                ('etapas', models.ManyToManyField(to='pre_recebimento.AlteracaoCronogramaEtapa')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Cronograma',
                'verbose_name_plural': 'Solicitações de Alteração de Cronograma',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, 'dados_comuns.fluxoalteracaocronograma', models.Model),
        ),
    ]
