# Generated by Django 3.2.18 on 2023-07-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0012_alter_unidademedida_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='unidade_medida',
        ),
    ]
