# Generated by Django 3.2.18 on 2023-07-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0013_remove_cronograma_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pre_recebimento.unidademedida'),
        ),
    ]
