# Generated by Django 3.2.18 on 2023-07-27 18:09

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0014_cronograma_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoalteracaocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=17, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='EM_ANALISE', name='CronogramaAlteracaoWorkflow', states=['EM_ANALISE', 'ALTERACAO_CODAE', 'CRONOGRAMA_CIENTE', 'APROVADO_DINUTRE', 'REPROVADO_DINUTRE', 'APROVADO_DILOG', 'REPROVADO_DILOG', 'FORNECEDOR_CIENTE'])),
        ),
    ]
