# Generated by Django 3.2.18 on 2023-07-27 18:53

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0015_alter_solicitacaoalteracaocronograma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoalteracaocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=18, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='SOLICITACAO_CRIADA', name='CronogramaAlteracaoWorkflow', states=['SOLICITACAO_CRIADA', 'EM_ANALISE', 'ALTERACAO_CODAE', 'CRONOGRAMA_CIENTE', 'APROVADO_DINUTRE', 'REPROVADO_DINUTRE', 'APROVADO_DILOG', 'REPROVADO_DILOG', 'FORNECEDOR_CIENTE'])),
        ),
    ]
