# Generated by Django 3.2.18 on 2023-08-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0015_auto_20230814_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoalteracaocronograma',
            name='motivo',
        ),
    ]
