# Generated by Django 3.2.18 on 2023-09-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0017_solicitacaoalteracaocronograma_programacoes_novas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbalagemQld',
            new_name='TipoEmbalagemQld',
        ),
        migrations.AlterModelOptions(
            name='tipoembalagemqld',
            options={'verbose_name': 'Tipo de Embalagem (Qualidade)', 'verbose_name_plural': 'Tipos de Embalagens (Qualidade)'},
        ),
    ]
