# Generated by Django 3.2.18 on 2023-09-07 17:50

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0018_auto_20230905_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoalteracaocronograma',
            name='qtd_total_programada',
            field=models.FloatField(blank=True, null=True, verbose_name='Qtd Total Programada'),
        ),
        migrations.AlterField(
            model_name='solicitacaoalteracaocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=28, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='SOLICITACAO_CRIADA', name='CronogramaAlteracaoWorkflow', states=['SOLICITACAO_CRIADA', 'EM_ANALISE', 'ALTERACAO_ENVIADA_FORNECEDOR', 'CRONOGRAMA_CIENTE', 'APROVADO_DINUTRE', 'REPROVADO_DINUTRE', 'APROVADO_DILOG', 'REPROVADO_DILOG'])),
        ),
    ]
