# Generated by Django 3.2.18 on 2023-09-13 16:05

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0019_auto_20230907_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoalteracaocronograma',
            name='status',
            field=django_xworkflows.models.StateField(max_length=28, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='SOLICITACAO_CRIADA', name='CronogramaAlteracaoWorkflow', states=['SOLICITACAO_CRIADA', 'EM_ANALISE', 'ALTERACAO_ENVIADA_FORNECEDOR', 'FORNECEDOR_CIENTE', 'CRONOGRAMA_CIENTE', 'APROVADO_DINUTRE', 'REPROVADO_DINUTRE', 'APROVADO_DILOG', 'REPROVADO_DILOG'])),
        ),
    ]
