# Generated by Django 3.2.20 on 2023-09-19 16:18

from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0020_alter_solicitacaoalteracaocronograma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutDeEmbalagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=20, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='LAYOUT_CRIADO', name='LayoutDeEmbalagemWorkflow', states=['LAYOUT_CRIADO', 'ENVIADO_PARA_ANALISE', 'APROVADO']))),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layouts', to='pre_recebimento.cronograma')),
            ],
            options={
                'verbose_name': 'Layout de Embalagem',
                'verbose_name_plural': 'Layouts de Embalagem',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, sme_terceirizadas.dados_comuns.behaviors.Logs, django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name='TipoDeEmbalagemDeLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_embalagem', models.CharField(blank=True, choices=[('PRIMARIA', 'Primária'), ('SECUNDARIA', 'Secundária'), ('TERCIARIA', 'Terciária')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=9)),
                ('complemento_do_status', models.TextField(blank=True, verbose_name='Complemento do status')),
                ('layout_de_embalagem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_de_embalagens', to='pre_recebimento.layoutdeembalagem')),
            ],
            options={
                'verbose_name': 'Tipo de Embalagem de Layout',
                'verbose_name_plural': 'Tipos de Embalagens de Layout',
            },
        ),
        migrations.CreateModel(
            name='ImagemDoTipoDeEmbalagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(upload_to='')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('tipo_de_embalagem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='pre_recebimento.tipodeembalagemdelayout')),
            ],
            options={
                'verbose_name': 'Imagem do Tipo de Embalagem',
                'verbose_name_plural': 'Imagens dos Tipos de Embalagens',
            },
        ),
    ]
