# Generated by Django 3.2.20 on 2023-10-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0022_alter_layoutdeembalagem_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipodeembalagemdelayout',
            unique_together={('layout_de_embalagem', 'tipo_embalagem')},
        ),
    ]
