# Generated by Django 3.2.20 on 2023-10-03 17:19

from django.db import migrations, models


def migrate_default_values(apps, _):
    TipoDeEmbalagemDeLayout = apps.get_model('pre_recebimento', 'TipoDeEmbalagemDeLayout')
    TipoDeEmbalagemDeLayout.objects.filter(status='').update(
        status='EM_ANALISE')


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0024_alter_imagemdotipodeembalagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeembalagemdelayout',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM_ANALISE', 'Em análise')], default='EM_ANALISE', max_length=10),
        ),
        migrations.RunPython(migrate_default_values),
    ]
