# Generated by Django 4.1.12 on 2023-10-19 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import sme_terceirizadas.dados_comuns.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0025_alter_tipodeembalagemdelayout_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDeRecebimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=20, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='DOCUMENTO_CRIADO', name='DocumentoDeRecebimentoWorkflow', states=['DOCUMENTO_CRIADO', 'ENVIADO_PARA_ANALISE']))),
                ('numero_laudo', models.CharField(blank=True, max_length=50, verbose_name='Número do Laudo')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_de_recebimento', to='pre_recebimento.cronograma')),
            ],
            options={
                'verbose_name': 'Documento de Recebimento',
                'verbose_name_plural': 'Documentos de Recebimento',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, sme_terceirizadas.dados_comuns.behaviors.Logs, django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name='TipoDeDocumentoDeRecebimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('LAUDO', 'Laudo'), ('DECLARACAO_LEI_1512010', 'Declaração de atendimento a Lei Municipal: 15.120/10'), ('CERTIFICADO_CONF_ORGANICA', 'Certificado de conformidade orgânica'), ('RASTREABILIDADE', 'Rastreabilidade'), ('DECLARACAO_MATERIA_ORGANICA', 'Declaração de Matéria Láctea'), ('OUTROS', 'Outros')], max_length=35)),
                ('descricao_documento', models.TextField(blank=True, verbose_name='Descrição do Documento')),
                ('documento_recebimento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_de_documentos', to='pre_recebimento.documentoderecebimento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Recebimento',
                'verbose_name_plural': 'Tipos de Documentos de Recebimento',
                'unique_together': {('documento_recebimento', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='ArquivoDoTipoDeDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(upload_to='documentos_de_recebimento', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PDF', 'PNG', 'JPG', 'JPEG']), sme_terceirizadas.dados_comuns.validators.validate_file_size_10mb])),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('tipo_de_documento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='pre_recebimento.tipodedocumentoderecebimento')),
            ],
            options={
                'verbose_name': 'Arquivo do Tipo de Documento',
                'verbose_name_plural': 'Arquivos dos Tipos de Documentos',
            },
        ),
    ]
