# Generated by Django 4.1.12 on 2023-11-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0026_documentoderecebimento_tipodedocumentoderecebimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoderecebimento',
            name='correcao_solicitada',
            field=models.TextField(blank=True, verbose_name='Correção Solicitada'),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='data_fabricacao_lote',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fabricação do Lote'),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='data_final_lote',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final do Lote'),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='laboratorio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_de_recebimento', to='pre_recebimento.laboratorio'),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='numero_empenho',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do Empenho'),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='quantidade_laudo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='saldo_laudo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pre_recebimento.unidademedida'),
        ),
        migrations.AddField(
            model_name='documentoderecebimento',
            name='validade_produto',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Produto'),
        ),
    ]
