# Generated by Django 4.1.12 on 2023-11-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recebimento', '0029_alter_documentoderecebimento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoderecebimento',
            name='numero_empenho',
        ),
    ]
