# Generated by Django 4.2.7 on 2023-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pre_recebimento', '0031_fichatecnicadoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='agroecologico',
            field=models.BooleanField(default=False, verbose_name='É agroecológico?'),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='alergenicos',
            field=models.BooleanField(
                default=False, verbose_name='Pode conter alergênicos?'
            ),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='componentes_produto',
            field=models.CharField(
                blank=True, max_length=250, verbose_name='Componentes do Produto'
            ),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='gluten',
            field=models.BooleanField(default=False, verbose_name='Contém glúten?'),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='ingredientes_alergenicos',
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name='Ingredientes/aditivos alergênicos',
            ),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='lactose',
            field=models.BooleanField(default=False, verbose_name='Contém lactose?'),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='lactose_detalhe',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='Detalhar Lactose'
            ),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='mecanismo_controle',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CERTIFICACAO', 'Certificação'),
                    ('OPAC', 'OPAC'),
                    ('OCS', 'OCS'),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='numero_registro',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='Nº do Registro do Rótulo'
            ),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='organico',
            field=models.BooleanField(default=False, verbose_name='É orgânico?'),
        ),
        migrations.AddField(
            model_name='fichatecnicadoproduto',
            name='prazo_validade',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='Prazo de Validade'
            ),
        ),
    ]
