# Generated by Django 4.2.7 on 2024-01-10 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0038_fichatecnicadoproduto_produto_eh_liquido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cronograma",
            name="tipo_embalagem",
        ),
    ]
