# Generated by Django 4.2.7 on 2024-01-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0044_merge_20240115_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma",
            name="custo_unitario_produto",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Custo Unitário do Produto"
            ),
        ),
        migrations.AddField(
            model_name="cronograma",
            name="ficha_tecnica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pre_recebimento.fichatecnicadoproduto",
            ),
        ),
        migrations.AddField(
            model_name="etapasdocronograma",
            name="qtd_total_empenho",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Qtde. Total do Empenho"
            ),
        ),
    ]
