# Generated by Django 4.2.7 on 2024-01-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0045_cronograma_custo_unitario_produto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronograma",
            name="ficha_tecnica",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pre_recebimento.fichatecnicadoproduto",
            ),
        ),
    ]
