# Generated by Django 4.2.7 on 2024-01-29 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0047_alter_etapasdocronograma_total_embalagens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cronograma",
            name="tipo_embalagem",
        ),
    ]
