# Generated by Django 4.2.7 on 2024-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0054_alter_layoutdeembalagem_ficha_tecnica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentoderecebimento",
            name="data_fabricacao_lote",
        ),
        migrations.RemoveField(
            model_name="documentoderecebimento",
            name="validade_produto",
        ),
        migrations.AddField(
            model_name="datadefabricaoeprazo",
            name="data_validade",
            field=models.DateField(blank=True, null=True, verbose_name="Data Validade"),
        ),
        migrations.AddField(
            model_name="documentoderecebimento",
            name="numero_lote_laudo",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Número do Laudo"
            ),
        ),
    ]
