# Generated by Django 2.0.13 on 2019-05-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_kit', '0002_auto_20190516_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermealkit',
            name='meal_kits',
            field=models.ManyToManyField(to='meal_kit.MealKit'),
        ),
    ]
