# Generated by Django 2.0.13 on 2019-05-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_kit', '0002_auto_20190517_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermealkit',
            name='status',
            field=models.CharField(choices=[('SAVED', 'SALVO'), ('SENDED', 'ENVIADO')], default=0, max_length=6, verbose_name='Status'),
        ),
    ]
