# Generated by Django 2.0.13 on 2019-05-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_kit', '0003_ordermealkit_meal_kits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermealkit',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
