# Generated by Django 2.0.13 on 2019-05-02 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190502_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=90, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbs', models.CharField(default='R', max_length=2, verbose_name='Verbs')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.Permission')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='permissions',
            field=models.ManyToManyField(through='permission.ProfilePermission', to='users.Profile'),
        ),
    ]
