# Generated by Django 2.0.13 on 2019-05-23 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=90, verbose_name='title')),
                ('endpoint', models.CharField(max_length=90, verbose_name='endpoint')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbs', models.CharField(default='R', help_text='Campo utilizado para indenticar o nível de permissão do usuário (R : Read-only, W : Writer)', max_length=2, verbose_name='Verbs')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.Permission')),
            ],
            options={
                'verbose_name': 'Permission from Profile',
                'verbose_name_plural': 'Permissions from Profile',
            },
        ),
    ]
