# Generated by Django 2.0.13 on 2019-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepermission',
            name='verbs',
            field=models.CharField(default='R', help_text='Campo utilizado para indenticar o nível de permissão do usuário (R : Read-only, W : Writer)', max_length=2, verbose_name='Verbs'),
        ),
    ]
