# Generated by Django 2.0.13 on 2019-05-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepermission',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='permission',
            name='permissions',
            field=models.ManyToManyField(through='permission.ProfilePermission', to='users.Profile'),
        ),
    ]
