# Generated by Django 2.0.13 on 2019-05-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_auto_20190502_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepermission',
            options={'verbose_name': 'Permission from Profile', 'verbose_name_plural': 'Permissions from Profile'},
        ),
        migrations.AddField(
            model_name='permission',
            name='endpoint',
            field=models.CharField(default=1, max_length=90, verbose_name='endpoint'),
            preserve_default=False,
        ),
    ]
