# Generated by Django 4.2.7 on 2024-04-10 16:20

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sme_sigpae_api.dados_comuns.validators


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0019_alter_contrato_ata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaOcorrencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "posicao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "perfis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            blank=True,
                            choices=[
                                ("DIRETOR", "DIRETOR"),
                                ("SUPERVISAO", "SUPERVISAO"),
                            ],
                            default=[],
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria das Ocorrências",
                "verbose_name_plural": "Categorias das Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="TipoOcorrencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativo"), (False, "Inativo")],
                        default=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "posicao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "perfis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            blank=True,
                            choices=[
                                ("DIRETOR", "DIRETOR"),
                                ("SUPERVISAO", "SUPERVISAO"),
                            ],
                            default=[],
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("pontuacao", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tolerancia", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "modelo_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="IMR",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["XLS", "XLSX"]
                            ),
                            sme_sigpae_api.dados_comuns.validators.validate_file_size_10mb,
                        ],
                        verbose_name="Modelo de Anexo",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_ocorrencia",
                        to="imr.categoriaocorrencia",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_ocorrencia",
                        to="terceirizada.edital",
                    ),
                ),
                (
                    "penalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_ocorrencia",
                        to="imr.tipopenalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Ocorrência",
                "verbose_name_plural": "Tipos de Ocorrência",
            },
        ),
    ]
