# Generated by Django 4.2.7 on 2024-04-19 17:30

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0006_tipoocorrencia_eh_imr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaixaPontuacaoIMR",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "pontuacao_minima",
                    models.PositiveSmallIntegerField(verbose_name="Pontuação Mínima"),
                ),
                (
                    "pontuacao_maxima",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pontuação Máxima"
                    ),
                ),
                (
                    "porcentagem_desconto",
                    models.FloatField(
                        help_text="Desconto no faturamento do dia",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="% de Desconto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faixa de Pontuação - IMR",
                "verbose_name_plural": "Faixas de Pontuação - IMR",
                "ordering": ("pontuacao_minima",),
            },
        ),
    ]
