# Generated by Django 4.2.7 on 2024-04-23 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0019_alter_contrato_ata"),
        ("imr", "0008_importacaoplanilhatipopenalidade"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tipopenalidade",
            unique_together={("edital", "numero_clausula")},
        ),
    ]
