# Generated by Django 4.2.7 on 2024-05-10 16:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0021_respostautensiliomesa_respostautensiliocozinha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaNaoSeAplica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "grupo",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Grupo de respostas"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "formulario_base",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_nao_se_aplica",
                        to="imr.formularioocorrenciasbase",
                        verbose_name="Formulário de Ocorrências",
                    ),
                ),
                (
                    "tipo_ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_nao_se_aplica",
                        to="imr.tipoocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência Não se aplica",
                "verbose_name_plural": "Ocorrências Não se aplica",
                "unique_together": {("formulario_base", "tipo_ocorrencia", "grupo")},
            },
        ),
        migrations.DeleteModel(
            name="RespostaNaoSeAplica",
        ),
    ]
