# Generated by Django 4.2.7 on 2024-05-15 09:53

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0020_edital_eh_imr"),
        ("imr", "0023_remove_formulariosupervisao_apresentou_ocorrencias_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tipoocorrencia",
            managers=[
                ("para_nutrisupervisores", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="tipoocorrencia",
            unique_together={("edital", "categoria", "penalidade", "titulo")},
        ),
    ]
