# Generated by Django 4.2.7 on 2024-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0024_alter_tipoocorrencia_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tipoocorrencia",
            managers=[],
        ),
    ]
