# Generated by Django 4.2.7 on 2024-06-17 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0030_alter_formulariosupervisao_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipoocorrencia",
            options={
                "ordering": ("categoria__posicao", "posicao", "titulo"),
                "verbose_name": "Tipo de Ocorrência",
                "verbose_name_plural": "Tipos de Ocorrência",
            },
        ),
    ]
