# Generated by Django 4.2.7 on 2024-07-02 21:44

import django.core.validators
from django.db import migrations, models

import sme_sigpae_api.dados_comuns.validators


class Migration(migrations.Migration):
    dependencies = [
        ("imr", "0033_notificacoesassinadasformulariobase_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacoesassinadasformulariobase",
            name="notificacao_assinada",
            field=models.FileField(
                upload_to="IMR",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["PDF"]
                    ),
                    sme_sigpae_api.dados_comuns.validators.validate_file_size_10mb,
                ],
                verbose_name="Notificação Assinada",
            ),
        ),
    ]
