# Generated by Django 4.1.12 on 2023-10-25 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0015_auto_20230925_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="terceirizada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="terceirizada.terceirizada",
            ),
        ),
    ]
