# Generated by Django 4.2.7 on 2024-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0017_alter_contrato_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrato",
            name="pregao_chamada_publica",
        ),
        migrations.AddField(
            model_name="contrato",
            name="modalidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PREGAO_ELETRONICO", "Pregão Eletrônico"),
                    ("CHAMADA_PUBLICA", "Chamada Pública"),
                ],
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="numero_chamada_publica",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nº da Chamada Pública"
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="numero_pregao",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nº do Pregão Eletrônico"
            ),
        ),
    ]
