# Generated by Django 4.2.7 on 2024-12-18 12:05

import uuid

import django_prometheus.models
from django.db import migrations, models


def cria_modalidades(apps, schema_editor):
    Modalidade = apps.get_model("terceirizada", "Modalidade")

    Modalidade.objects.get_or_create(nome="Pregão Eletrônico")
    Modalidade.objects.get_or_create(nome="Chamada Pública")
    Modalidade.objects.get_or_create(nome="Emergencial")
    Modalidade.objects.get_or_create(nome="Contratação Direta")
    Modalidade.objects.get_or_create(nome="Carona de ATA")


def remove_modalidades(apps, schema_editor):
    Modalidade = apps.get_model("terceirizada", "Modalidade")
    Modalidade.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0020_edital_eh_imr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Modalidade",
                "verbose_name_plural": "Modalidades",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("modalidade"),
                models.Model,
            ),
        ),
        migrations.RunPython(cria_modalidades, reverse_code=remove_modalidades),
    ]
