# Generated by Django 4.2.7 on 2024-12-17 11:09

import django.db.models.deletion
from django.db import migrations, models


def altera_contratos(apps, schema_editor):
    Modalidade = apps.get_model("terceirizada", "Modalidade")
    Contrato = apps.get_model("terceirizada", "Contrato")

    pregao = Modalidade.objects.get(nome="Pregão Eletrônico")
    chamada = Modalidade.objects.get(nome="Chamada Pública")
    nao_definida = Modalidade.objects.get(nome="Não definida")

    mapeamento_modalidades = {
        "PREGAO_ELETRONICO": pregao.id,
        "CHAMADA_PUBLICA": chamada.id,
    }

    contratos_atualizados = []
    for contrato in Contrato.objects.all():
        if contrato.modalidade in mapeamento_modalidades:
            contrato.modalidade = mapeamento_modalidades.get(
                contrato.modalidade, nao_definida.id
            )
        else:
            contrato.modalidade = nao_definida.id
        contratos_atualizados.append(contrato)
    Contrato.objects.bulk_update(contratos_atualizados, ["modalidade"])


def reverte_contratos(apps, schema_editor):
    Modalidade = apps.get_model("terceirizada", "Modalidade")
    Contrato = apps.get_model("terceirizada", "Contrato")

    pregao = Modalidade.objects.get(nome="Pregão Eletrônico")
    chamada = Modalidade.objects.get(nome="Chamada Pública")
    nao_definida = Modalidade.objects.get(nome="Não definida")
    emergencial = Modalidade.objects.get(nome="Emergencial")
    contratacao = Modalidade.objects.get(nome="Contratação Direta")
    carona = Modalidade.objects.get(nome="Carona de ATA")

    mapeamento_modalidades = {
        pregao.id: "PREGAO_ELETRONICO",
        chamada.id: "CHAMADA_PUBLICA",
        emergencial.id: "EMERGENCIAL",
        contratacao.id: "CONTRATACAO_DIRETA",
        carona.id: "CARONA_DE_ATA",
        nao_definida.id: "NAO_DEFINIDA",
    }
    contratos_atualizados = []
    for contrato in Contrato.objects.all():
        if int(contrato.modalidade) in mapeamento_modalidades:
            contrato.modalidade = mapeamento_modalidades.get(int(contrato.modalidade))
        else:
            contrato.modalidade = "NAO_DEFINIDA"
        contratos_atualizados.append(contrato)
    Contrato.objects.bulk_update(contratos_atualizados, ["modalidade"])


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0021_modalidade"),
    ]

    operations = [
        migrations.RunPython(altera_contratos, reverse_code=reverte_contratos),
        migrations.AlterField(
            model_name="contrato",
            name="modalidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="terceirizada.modalidade",
            ),
        ),
    ]
