# Generated by Django 4.2.7 on 2024-12-18 15:17

import django.db.models.deletion
from django.db import migrations, models


def altera_contratos(apps, schema_editor):
    Modalidade = apps.get_model("terceirizada", "Modalidade")
    Contrato = apps.get_model("terceirizada", "Contrato")

    pregao = Modalidade.objects.get(nome="Pregão Eletrônico")
    chamada = Modalidade.objects.get(nome="Chamada Pública")

    mapeamento_modalidades = {
        "PREGAO_ELETRONICO": pregao.id,
        "CHAMADA_PUBLICA": chamada.id,
    }

    contratos_atualizados = []
    for contrato in Contrato.objects.all():
        if contrato.modalidade in mapeamento_modalidades:
            contrato.modalidade = mapeamento_modalidades.get(contrato.modalidade)
        else:
            contrato.modalidade = None
        contratos_atualizados.append(contrato)
    Contrato.objects.bulk_update(contratos_atualizados, ["modalidade"])


def reverte_contratos(apps, schema_editor):
    Modalidade = apps.get_model("terceirizada", "Modalidade")
    Contrato = apps.get_model("terceirizada", "Contrato")

    pregao = Modalidade.objects.get(nome="Pregão Eletrônico")
    chamada = Modalidade.objects.get(nome="Chamada Pública")
    emergencial = Modalidade.objects.get(nome="Emergencial")
    contratacao = Modalidade.objects.get(nome="Contratação Direta")
    carona = Modalidade.objects.get(nome="Carona de ATA")

    mapeamento_modalidades = {
        pregao.id: "PREGAO_ELETRONICO",
        chamada.id: "CHAMADA_PUBLICA",
        emergencial.id: "EMERGENCIAL",
        contratacao.id: "CONTRATACAO_DIRETA",
        carona.id: "CARONA_DE_ATA",
    }

    contratos_atualizados = []
    for contrato in Contrato.objects.all():
        if contrato.modalidade:
            modalidade_int = int(contrato.modalidade)
            if modalidade_int in mapeamento_modalidades:
                contrato.modalidade = mapeamento_modalidades.get(modalidade_int)
            else:
                contrato.modalidade = None
            contratos_atualizados.append(contrato)
    Contrato.objects.bulk_update(contratos_atualizados, ["modalidade"])


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0022_alter_contrato_modalidade"),
    ]
    operations = [
        migrations.RunPython(altera_contratos, reverse_code=reverte_contratos),
        migrations.AlterField(
            model_name="contrato",
            name="modalidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="terceirizada.modalidade",
            ),
        ),
    ]
