# Generated by Django 4.2.7 on 2023-11-28 17:28

import uuid

import django.core.validators
import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models

import sme_sigpae_api.dados_comuns.behaviors


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0081_alter_homologacaoproduto_rastro_terceirizada"),
        ("terceirizada", "0017_alter_contrato_numero"),
        ("pre_recebimento", "0030_remove_documentoderecebimento_numero_empenho"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaTecnicaDoProduto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    django_xworkflows.models.StateField(
                        max_length=16,
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="RASCUNHO",
                            name="FichaTecnicaDoProdutoWorkflow",
                            states=["RASCUNHO"],
                        ),
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número da Ficha Técnica",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERECIVEIS", "Perecíveis"),
                            ("NAO_PERECIVEIS", "Não Perecíveis"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "pregao_chamada_publica",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nº do Pregão Eletrônico",
                    ),
                ),
                (
                    "cnpj_fabricante",
                    models.CharField(
                        max_length=14,
                        validators=[django.core.validators.MinLengthValidator(14)],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "cep_fabricante",
                    models.CharField(blank=True, max_length=8, verbose_name="CEP"),
                ),
                (
                    "endereco_fabricante",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Endereco"
                    ),
                ),
                (
                    "numero_fabricante",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento_fabricante",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro_fabricante",
                    models.CharField(blank=True, max_length=150, verbose_name="Bairro"),
                ),
                (
                    "cidade_fabricante",
                    models.CharField(blank=True, max_length=150, verbose_name="Cidade"),
                ),
                (
                    "estado_fabricante",
                    models.CharField(blank=True, max_length=150, verbose_name="Estado"),
                ),
                ("email_fabricante", models.EmailField(blank=True, max_length=254)),
                (
                    "telefone_fabricante",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terceirizada.terceirizada",
                    ),
                ),
                (
                    "fabricante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produto.fabricante",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produto.marca",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produto.nomedeprodutoedital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Técnica do Produto",
                "verbose_name_plural": "Fichas Técnicas dos Produtos",
            },
            bases=(
                sme_sigpae_api.dados_comuns.behaviors.TemIdentificadorExternoAmigavel,
                sme_sigpae_api.dados_comuns.behaviors.Logs,
                django_xworkflows.models.BaseWorkflowEnabled,
                models.Model,
            ),
        ),
    ]
