# Generated by Django 4.2.7 on 2023-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0032_fichatecnicadoproduto_agroecologico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="agroecologico",
            field=models.BooleanField(null=True, verbose_name="É agroecológico?"),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="alergenicos",
            field=models.BooleanField(
                null=True, verbose_name="Pode conter alergênicos?"
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="gluten",
            field=models.BooleanField(null=True, verbose_name="Contém glúten?"),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="lactose",
            field=models.BooleanField(null=True, verbose_name="Contém lactose?"),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="organico",
            field=models.BooleanField(null=True, verbose_name="É orgânico?"),
        ),
    ]
