# Generated by Django 4.2.7 on 2023-12-19 18:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0082_informacaonutricional_eh_fixo"),
        ("pre_recebimento", "0034_fichatecnicadoproduto_porcao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformacoesNutricionaisFichaTecnica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("quantidade_por_100g", models.CharField(max_length=10)),
                ("quantidade_porcao", models.CharField(max_length=10)),
                ("valor_diario", models.CharField(max_length=10)),
                (
                    "ficha_tecnica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informacoes_nutricionais",
                        to="pre_recebimento.fichatecnicadoproduto",
                    ),
                ),
                (
                    "informacao_nutricional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="produto.informacaonutricional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informação Nutricional da Ficha Técnica",
                "verbose_name_plural": "Informações Nutricionais da Ficha Técnica",
            },
        ),
    ]
