# Generated by Django 4.2.7 on 2023-12-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0035_informacoesnutricionaisfichatecnica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida",
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida_porcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas_tecnicas_unidade_porcao",
                to="pre_recebimento.unidademedida",
            ),
        ),
    ]
