# Generated by Django 4.2.7 on 2024-01-01 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import sme_sigpae_api.dados_comuns.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "pre_recebimento",
            "0036_remove_fichatecnicadoproduto_unidade_medida_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="arquivo",
            field=models.FileField(
                null=True,
                upload_to="fichas_tecnicas",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["PDF"]
                    ),
                    sme_sigpae_api.dados_comuns.validators.validate_file_size_10mb,
                ],
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="condicoes_de_conservacao",
            field=models.TextField(
                blank=True,
                help_text="Condições de conservação e Prazo máximo para consumo após a abertura da embalagem primária",
                verbose_name="Condições de conservação",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="condicoes_de_transporte",
            field=models.TextField(blank=True, verbose_name="Condições de Transporte"),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="embalagem_primaria",
            field=models.TextField(blank=True, verbose_name="Embalagem Primária"),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="embalagem_secundaria",
            field=models.TextField(blank=True, verbose_name="Embalagem Secundária"),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="embalagens_de_acordo_com_anexo",
            field=models.BooleanField(
                help_text="Declaro que as embalagens primária e secundária em que serão entregues o produto estarão de acordo com as especificações do Anexo I do Edital",
                null=True,
                verbose_name="Embalagens de Acordo com Anexo?",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="habilitacao",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Habilitação"
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="informacoes_adicionais",
            field=models.TextField(blank=True, verbose_name="Informações Adicionais"),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="material_embalagem_primaria",
            field=models.TextField(
                blank=True, verbose_name="Material da Embalagem Primária"
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="modo_de_preparo",
            field=models.TextField(
                blank=True, verbose_name="Modo de Preparo do Produto"
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="nome_responsavel_tecnico",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Nome completo do Responsável Técnico",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="numero_registro_orgao",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Nº do Registro em Órgão Competente",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="peso_embalagem_primaria_vazia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="peso_embalagem_secundaria_vazia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="peso_liquido_embalagem_primaria",
            field=models.FloatField(
                blank=True,
                help_text="Peso Líquido do Produto na Embalagem Primária",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="peso_liquido_embalagem_secundaria",
            field=models.FloatField(
                blank=True,
                help_text="Peso Líquido do Produto na Embalagem Secundária",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="prazo_validade_descongelamento",
            field=models.CharField(
                blank=True,
                help_text="Prazo de Validade após o descongelamento e mantido sob refrigeração",
                max_length=50,
                verbose_name="Prazo de Validade Descongelamento",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="rotulo_legivel",
            field=models.BooleanField(
                help_text="Declaro que no rótulo da embalagem primária e, se for o caso, da secundária, constarão, de forma legível e indelével, todas as informações solicitadas do Anexo I do Edital",
                null=True,
                verbose_name="Rotulo Legível?",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="sistema_vedacao_embalagem_secundaria",
            field=models.TextField(
                blank=True, verbose_name="Sistema de Vedação da Embalagem Secundária"
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="temperatura_congelamento",
            field=models.CharField(
                blank=True,
                max_length=10,
                verbose_name="Temperatura de Congelamento do Produto",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="temperatura_veiculo",
            field=models.CharField(
                blank=True,
                max_length=10,
                verbose_name="Temperatura Interna do Veículo para Transporte",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida_primaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas_tecnicas_unidade_primaria",
                to="pre_recebimento.unidademedida",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida_primaria_vazia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas_tecnicas_primaria_vazia",
                to="pre_recebimento.unidademedida",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida_secundaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas_tecnicas_unidade_secundaria",
                to="pre_recebimento.unidademedida",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida_secundaria_vazia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas_tecnicas_secundaria_vazia",
                to="pre_recebimento.unidademedida",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="variacao_percentual",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
