# Generated by Django 4.2.7 on 2024-01-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0037_fichatecnicadoproduto_arquivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="produto_eh_liquido",
            field=models.BooleanField(null=True, verbose_name="O produto é líquido?"),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="unidade_medida_volume_primaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas_tecnicas_volume_primaria",
                to="pre_recebimento.unidademedida",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="volume_embalagem_primaria",
            field=models.FloatField(
                blank=True,
                help_text="Volume do Produto na Embalagem Primária",
                null=True,
            ),
        ),
    ]
