# Generated by Django 4.2.7 on 2024-01-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0039_remove_cronograma_tipo_embalagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma",
            name="tipo_embalagem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pre_recebimento.tipoembalagemqld",
            ),
        ),
    ]
