# Generated by Django 4.2.7 on 2024-01-09 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0040_fichatecnicadoproduto_porcao_float_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichatecnicadoproduto",
            name="porcao",
        ),
        migrations.RemoveField(
            model_name="fichatecnicadoproduto",
            name="valor_unidade_caseira",
        ),
    ]
