# Generated by Django 4.2.7 on 2024-01-09 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0041_remove_fichatecnicadoproduto_porcao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichatecnicadoproduto",
            old_name="porcao_float",
            new_name="porcao",
        ),
        migrations.RenameField(
            model_name="fichatecnicadoproduto",
            old_name="valor_unidade_caseira_float",
            new_name="valor_unidade_caseira",
        ),
    ]
