# Generated by Django 4.2.7 on 2024-01-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0040_cronograma_tipo_embalagem"),
        (
            "pre_recebimento",
            "0043_fichatecnicadoproduto_temperatura_congelamento_float_and_more",
        ),
    ]

    operations = []
