# Generated by Django 4.2.7 on 2024-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0046_alter_cronograma_ficha_tecnica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapasdocronograma",
            name="total_embalagens",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total de Embalagens"
            ),
        ),
    ]
