# Generated by Django 4.2.7 on 2024-01-29 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0048_remove_cronograma_tipo_embalagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cronograma",
            name="produto",
        ),
    ]
