# Generated by Django 4.2.7 on 2024-03-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0052_alter_fichatecnicadoproduto_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layoutdeembalagem",
            name="cronograma",
        ),
        migrations.AddField(
            model_name="layoutdeembalagem",
            name="ficha_tecnica",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pre_recebimento.fichatecnicadoproduto",
            ),
        ),
    ]
