# Generated by Django 4.2.7 on 2024-04-02 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0055_alter_etapasdocronograma_total_embalagens"),
        (
            "pre_recebimento",
            "0055_remove_documentoderecebimento_data_fabricacao_lote_and_more",
        ),
    ]

    operations = []
