# Generated by Django 4.2.7 on 2024-04-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0056_merge_20240402_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma",
            name="tipo_embalagem_secundaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pre_recebimento.tipoembalagemqld",
            ),
        ),
    ]
