# Generated by Django 4.2.7 on 2024-04-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0057_cronograma_tipo_embalagem_secundaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronograma",
            name="ficha_tecnica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pre_recebimento.fichatecnicadoproduto",
            ),
        ),
    ]
