# Generated by Django 4.2.7 on 2024-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cardapio",
            "0047_alter_dataintervaloalteracaocardapio_cancelado_justificativa_and_more",
        ),
        (
            "inclusao_alimentacao",
            "0038_alter_diasmotivosinclusaodealimentacaocei_cancelado_justificativa_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quantidadedealunosemeiinclusaodealimentacaocemei",
            name="tipos_alimentacao",
            field=models.ManyToManyField(to="cardapio.tipoalimentacao"),
        ),
    ]
