# Generated by Django 2.2.13 on 2022-08-03 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0052_auto_20220718_1810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSobremesaDoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tipo_unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.TipoUnidadeEscolar')),
            ],
            options={
                'verbose_name': 'Dia de sobremesa doce',
                'verbose_name_plural': 'Dias de sobremesa doce',
                'ordering': ('data',),
            },
        ),
    ]
