# Generated by Django 2.2.13 on 2022-08-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0052_auto_20220718_1810'),
        ('medicao_inicial', '0002_auto_20220804_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContagemAlimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de contagem das alimentações',
                'verbose_name_plural': 'Tipos de contagem das alimentações',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMedicaoInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mes', models.CharField(max_length=2, verbose_name='Mes')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('status', django_xworkflows.models.StateField(max_length=39, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='MEDICAO_EM_ABERTO_PARA_PREENCHIMENTO_UE', name='SolicitacaoMedicaoInicialWorkflow', states=['MEDICAO_EM_ABERTO_PARA_PREENCHIMENTO_UE', 'MEDICAO_ENCERRADA_PELA_CODAE']))),
                ('com_ocorrencias', models.BooleanField(default=False, verbose_name='Com ocorrências?')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_medicao_inicial', to='escola.Escola')),
                ('tipo_contagem_alimentacoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_medicao_inicial', to='medicao_inicial.TipoContagemAlimentacao')),
            ],
            options={
                'verbose_name': 'Solicitação de medição inicial',
                'verbose_name_plural': 'Solicitações de medição inicial',
                'ordering': ('-criado_em',),
                'unique_together': {('escola', 'mes', 'ano')},
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, django_xworkflows.models.BaseWorkflowEnabled, models.Model, sme_terceirizadas.dados_comuns.behaviors.Logs),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('rf', models.CharField(max_length=10)),
                ('solicitacao_medicao_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='medicao_inicial.SolicitacaoMedicaoInicial')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoOcorrenciaMedicaoInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='')),
                ('solicitacao_medicao_inicial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexo', to='medicao_inicial.SolicitacaoMedicaoInicial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
