# Generated by Django 2.2.13 on 2022-08-31 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0033_auto_20220817_0827'),
        ('escola', '0052_auto_20220718_1810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicao_inicial', '0003_anexoocorrenciamedicaoinicial_responsavel_solicitacaomedicaoinicial_tipocontagemalimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMedicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de medição',
                'verbose_name_plural': 'Categorias de medições',
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.PeriodoEscolar')),
                ('solicitacao_medicao_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='medicao_inicial.SolicitacaoMedicaoInicial')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, models.Model),
        ),
        migrations.CreateModel(
            name='ValorMedicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dia', models.CharField(max_length=2, verbose_name='Dia')),
                ('valor', models.TextField(verbose_name='Valor do Campo')),
                ('nome_campo', models.CharField(max_length=100)),
                ('categoria_medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_medicao', to='medicao_inicial.CategoriaMedicao')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_medicao', to='medicao_inicial.Medicao')),
                ('tipo_alimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.TipoAlimentacao')),
            ],
            options={
                'verbose_name': 'Valor da Medição',
                'verbose_name_plural': 'Valores das Medições',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, models.Model),
        ),
    ]
