# Generated by Django 2.2.13 on 2023-01-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0005_auto_20220928_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaomedicaoinicial',
            options={'ordering': ('-ano', '-mes'), 'verbose_name': 'Solicitação de medição inicial', 'verbose_name_plural': 'Solicitações de medição inicial'},
        ),
    ]
