# Generated by Django 2.2.13 on 2023-01-20 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


def inserir_nomes(apps, _):
    GrupoMedicao = apps.get_model('medicao_inicial', 'GrupoMedicao')
    for nome in ['Programas e Projetos', 'Solicitações de alimentação', 'ETEC']:
        GrupoMedicao.objects.create(nome=nome)


def backwards(apps, _):
    GrupoMedicao = apps.get_model('medicao_inicial', 'GrupoMedicao')
    GrupoMedicao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0006_auto_20230106_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMedicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo de medição',
                'verbose_name_plural': 'Grupos de medição',
            },
        ),
        migrations.AddField(
            model_name='medicao',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicao_inicial.GrupoMedicao'),
        ),
        migrations.RunPython(inserir_nomes, backwards),
    ]
