# Generated by Django 3.2.16 on 2023-03-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0013_auto_20230112_1152'),
        ('escola', '0056_logatualizadadosaluno'),
        ('medicao_inicial', '0013_auto_20230310_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_medicao_rastro_lote', to='escola.lote'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_medicao_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AddField(
            model_name='solicitacaomedicaoinicial',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_solicitacaomedicaoinicial_rastro_lote', to='escola.lote'),
        ),
        migrations.AddField(
            model_name='solicitacaomedicaoinicial',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_solicitacaomedicaoinicial_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
    ]
