# Generated by Django 3.2.16 on 2023-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0013_auto_20230310_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='valormedicao',
            name='habilitado_correcao',
            field=models.BooleanField(default=False),
        ),
    ]
