# Generated by Django 3.2.16 on 2023-04-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0014_auto_20230313_1231'),
        ('medicao_inicial', '0016_alter_medicao_periodo_escolar'),
    ]

    operations = [
    ]
