# Generated by Django 3.2.18 on 2023-05-12 04:13

from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0013_auto_20230112_1152'),
        ('escola', '0057_merge_20230303_1131'),
        ('medicao_inicial', '0017_merge_20230413_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoocorrenciamedicaoinicial',
            name='rastro_lote',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_anexoocorrenciamedicaoinicial_rastro_lote', to='escola.lote'),
        ),
        migrations.AddField(
            model_name='anexoocorrenciamedicaoinicial',
            name='rastro_terceirizada',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_anexoocorrenciamedicaoinicial_rastro_terceirizada', to='terceirizada.terceirizada'),
        ),
        migrations.AddField(
            model_name='anexoocorrenciamedicaoinicial',
            name='status',
            field=django_xworkflows.models.StateField(max_length=39, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='MEDICAO_EM_ABERTO_PARA_PREENCHIMENTO_UE', name='SolicitacaoMedicaoInicialWorkflow', states=['MEDICAO_EM_ABERTO_PARA_PREENCHIMENTO_UE', 'MEDICAO_ENVIADA_PELA_UE', 'MEDICAO_CORRECAO_SOLICITADA', 'MEDICAO_CORRECAO_SOLICITADA_CODAE', 'MEDICAO_CORRIGIDA_PELA_UE', 'MEDICAO_CORRIGIDA_PARA_CODAE', 'MEDICAO_APROVADA_PELA_DRE', 'MEDICAO_APROVADA_PELA_CODAE'])),
        ),
    ]
