# Generated by Django 3.2.18 on 2023-05-31 06:07

from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0013_auto_20230112_1152'),
        ('escola', '0057_merge_20230303_1131'),
        ('medicao_inicial', '0018_auto_20230512_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexoocorrenciamedicaoinicial',
            name='solicitacao_medicao_inicial',
        ),
        migrations.CreateModel(
            name='OcorrenciaMedicaoInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', django_xworkflows.models.StateField(max_length=39, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='MEDICAO_EM_ABERTO_PARA_PREENCHIMENTO_UE', name='SolicitacaoMedicaoInicialWorkflow', states=['MEDICAO_EM_ABERTO_PARA_PREENCHIMENTO_UE', 'MEDICAO_ENVIADA_PELA_UE', 'MEDICAO_CORRECAO_SOLICITADA', 'MEDICAO_CORRECAO_SOLICITADA_CODAE', 'MEDICAO_CORRIGIDA_PELA_UE', 'MEDICAO_CORRIGIDA_PARA_CODAE', 'MEDICAO_APROVADA_PELA_DRE', 'MEDICAO_APROVADA_PELA_CODAE']))),
                ('nome_ultimo_arquivo', models.CharField(max_length=100)),
                ('ultimo_arquivo', models.FileField(upload_to='')),
                ('rastro_lote', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_ocorrenciamedicaoinicial_rastro_lote', to='escola.lote')),
                ('rastro_terceirizada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicao_inicial_ocorrenciamedicaoinicial_rastro_terceirizada', to='terceirizada.terceirizada')),
                ('solicitacao_medicao_inicial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia', to='medicao_inicial.solicitacaomedicaoinicial')),
            ],
            options={
                'abstract': False,
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.Logs, django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.AddField(
            model_name='anexoocorrenciamedicaoinicial',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='medicao_inicial.ocorrenciamedicaoinicial'),
        ),
    ]
