# Generated by Django 3.2.18 on 2023-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0020_auto_20230531_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnexoOcorrenciaMedicaoInicial',
        ),
    ]
