# Generated by Django 3.2.18 on 2023-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0021_delete_anexoocorrenciamedicaoinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomedicaoinicial',
            name='ue_possui_alunos_periodo_parcial',
            field=models.BooleanField(default=False, verbose_name='Possui alunos periodo parcial?'),
        ),
    ]
