# Generated by Django 3.2.18 on 2023-08-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0058_logalunosmatriculadosfaixaetariadia'),
        ('medicao_inicial', '0022_solicitacaomedicaoinicial_ue_possui_alunos_periodo_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valormedicao',
            name='faixa_etaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.faixaetaria'),
        ),
    ]
