# Generated by Django 3.2.18 on 2023-08-17 19:16
import django.db.models.deletion
import numpy
from django.db import migrations, models
from calendar import setfirstweekday, monthcalendar

def get_week_of_month(year, month, day):
    setfirstweekday(0)
    x = numpy.array(monthcalendar(year, month))
    week_of_month = numpy.where(x==day)[0][0] + 1
    return(week_of_month)

def popular_semanas(apps, _):
    ValorMedicao = apps.get_model('medicao_inicial', 'ValorMedicao')
    for valor_medicao in ValorMedicao.objects.all():
        solicitacao = valor_medicao.medicao.solicitacao_medicao_inicial
        valor_medicao.semana = get_week_of_month(int(solicitacao.ano), int(solicitacao.mes), int(valor_medicao.dia))
        valor_medicao.save()

def backwards(apps, _):
    ValorMedicao = apps.get_model('medicao_inicial', 'ValorMedicao')
    ValorMedicao.objects.all().update(semana=None)

class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0023_valormedicao_faixa_etaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomedicaoinicial',
            name='historico',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valormedicao',
            name='semana',
            field=models.CharField(blank=True, max_length=1, verbose_name='Semana'),
        ),
        migrations.RunPython(popular_semanas, backwards),
    ]
