# Generated by Django 3.2.20 on 2023-10-09 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


def inserir_nomes(apps, _):
    AlimentacaoLancamentoEspecial = apps.get_model('medicao_inicial', 'AlimentacaoLancamentoEspecial')
    for alimentacao in [
    {
      'nome': '2ª Refeição 1ª oferta',
      'posicao': 1
    },
    {
      'nome': 'Repetição 2ª Refeição',
      'posicao': 2
    },
    {
      'nome': '2ª Sobremesa 1ª oferta',
      'posicao': 3
    },
    {
      'nome': 'Repetição 2ª Sobremesa',
      'posicao': 4
    },
    {
      'nome': '2º Lanche 4h',
      'posicao': 5
    },
    {
      'nome': '2º Lanche 5h',
      'posicao': 6
    },
    {
      'nome': 'Lanche Extra',
      'posicao': 7
    }]:
        AlimentacaoLancamentoEspecial.objects.create(nome=alimentacao['nome'], posicao=alimentacao['posicao'])


def backwards(apps, _):
    AlimentacaoLancamentoEspecial = apps.get_model('medicao_inicial', 'AlimentacaoLancamentoEspecial')
    AlimentacaoLancamentoEspecial.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0025_solicitacaomedicaoinicial_logs_salvos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentacaoLancamentoEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('posicao', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Alimentação de Lançamento Especial',
                'verbose_name_plural': 'Alimentações de Lançamentos Especiais',
            },
        ),
        migrations.RunPython(inserir_nomes, backwards),
    ]
