# Generated by Django 3.2.20 on 2023-10-10 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sme_terceirizadas.dados_comuns.behaviors
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicao_inicial', '0026_diasparacorrigir'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaParaCorrigir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dia', models.CharField(max_length=2, verbose_name='Dia')),
                ('habilitado_correcao', models.BooleanField(default=True)),
                ('categoria_medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_para_corrigir', to='medicao_inicial.categoriamedicao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_para_corrigir', to='medicao_inicial.medicao')),
            ],
            options={
                'verbose_name': 'Dia da Medição para corrigir',
                'verbose_name_plural': 'Dias da Medição para corrigir',
            },
            bases=(sme_terceirizadas.dados_comuns.behaviors.TemIdentificadorExternoAmigavel, models.Model),
        ),
        migrations.DeleteModel(
            name='DiasParaCorrigir',
        ),
    ]
