# Generated by Django 4.1.12 on 2023-10-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0028_alter_medicao_rastro_lote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaolancamentoespecial',
            options={'ordering': ['-alterado_em'], 'verbose_name': 'Permissão de Lançamento Especial', 'verbose_name_plural': 'Permissões de Lançamentos Especiais'},
        ),
        migrations.AddField(
            model_name='permissaolancamentoespecial',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
