# Generated by Django 4.1.12 on 2023-10-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0029_alter_permissaolancamentoespecial_options_and_more'),
        ('medicao_inicial', '0029_diaparacorrigir'),
    ]

    operations = [
    ]
