# Generated by Django 4.1.12 on 2023-11-05 18:08

from django.db import migrations, models

def migrar_dados_tipos_contagem_alimentacao(apps, _):
    modelo_solicitacao_medicao = apps.get_model('medicao_inicial', 'SolicitacaoMedicaoInicial')
    for solicitacao in modelo_solicitacao_medicao.objects.all():
        if solicitacao.tipo_contagem_alimentacoes:
            solicitacao.tipos_contagem_alimentacao.add(solicitacao.tipo_contagem_alimentacoes)
            solicitacao.save()

def backwards(apps, _):
    modelo_solicitacao_medicao = apps.get_model('medicao_inicial', 'SolicitacaoMedicaoInicial')
    for solicitacao in modelo_solicitacao_medicao.objects.all():
        solicitacao.tipos_contagem_alimentacao.set([])

class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0030_merge_20231016_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomedicaoinicial',
            name='tipos_contagem_alimentacao',
            field=models.ManyToManyField(to='medicao_inicial.tipocontagemalimentacao'),
        ),
        migrations.RunPython(migrar_dados_tipos_contagem_alimentacao, backwards),
    ]
