# Generated by Django 4.1.12 on 2023-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_inicial', '0031_solicitacaomedicaoinicial_tipos_contagem_alimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaomedicaoinicial',
            name='tipo_contagem_alimentacoes',
        ),
        migrations.AlterField(
            model_name='solicitacaomedicaoinicial',
            name='tipos_contagem_alimentacao',
            field=models.ManyToManyField(related_name='solicitacoes_medicao_inicial', to='medicao_inicial.tipocontagemalimentacao'),
        ),
    ]
