# Generated by Django 4.2.7 on 2023-11-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicao_inicial", "0033_criar_grupos_medicao_infantil"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="dre_ciencia_correcao_data",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
