# Generated by Django 4.2.7 on 2024-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "medicao_inicial",
            "0034_solicitacaomedicaoinicial_dre_ciencia_correcao_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="valormedicao",
            name="infantil_ou_fundamental",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("INFANTIL", "INFANTIL"),
                    ("FUNDAMENTAL", "FUNDAMENTAL"),
                ],
                default="N/A",
                max_length=11,
            ),
        ),
    ]
