# Generated by Django 4.2.7 on 2023-11-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicao_inicial", "0034_solicitacaomedicaoinicial_dre_ciencia_correcao_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="dre_ciencia_correcao_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_medicao_ciencia_correcao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
