# Generated by Django 4.2.7 on 2024-02-06 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicao_inicial", "0035_empenho"),
        ("medicao_inicial", "0035_valormedicao_infantil_ou_fundamental"),
    ]

    operations = []
