# Generated by Django 4.2.7 on 2024-03-05 20:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0019_alter_contrato_ata"),
        ("medicao_inicial", "0037_diaparacorrigir_infantil_ou_fundamental"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClausulaDeDesconto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "numero_clausula",
                    models.CharField(max_length=100, verbose_name="Número da Cláusula"),
                ),
                (
                    "item_clausula",
                    models.CharField(max_length=100, verbose_name="Item da Cláusula"),
                ),
                (
                    "porcentagem_desconto",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clausula_desconto",
                        to="terceirizada.edital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cláusula de Desconto",
                "verbose_name_plural": "Cláusulas de Descontos",
                "ordering": ["-alterado_em"],
                "unique_together": {("edital", "numero_clausula", "item_clausula")},
            },
        ),
    ]
