# Generated by Django 4.2.7 on 2024-03-28 12:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0068_add_historico_matricula_aluno"),
        ("cardapio", "0046_dataintervaloalteracaocardapiocemei"),
        ("terceirizada", "0019_alter_contrato_ata"),
        ("medicao_inicial", "0039_remove_empenho_tipo_reajuste"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametrizacaoFinanceira",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("legenda", models.TextField(blank=True, null=True)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametrizacoes_financeiras",
                        to="terceirizada.edital",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametrizacoes_financeiras",
                        to="escola.lote",
                    ),
                ),
                (
                    "tipos_unidades",
                    models.ManyToManyField(
                        related_name="parametrizacoes_financeiras",
                        to="escola.tipounidadeescolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização Financeira",
                "verbose_name_plural": "Parametrizações Financeiras",
                "unique_together": {("edital", "lote")},
            },
        ),
        migrations.CreateModel(
            name="ParametrizacaoFinanceiraTabela",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nome", models.CharField()),
                (
                    "parametrizacao_financeira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabelas",
                        to="medicao_inicial.parametrizacaofinanceira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização Financeira Tabela",
                "verbose_name_plural": "Parametrizações Financeiras Tabelas",
                "unique_together": {("nome", "parametrizacao_financeira")},
            },
        ),
        migrations.CreateModel(
            name="ParametrizacaoFinanceiraTabelaValor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("grupo", models.CharField(blank=True, null=True)),
                ("valor_colunas", models.JSONField()),
                (
                    "tabela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="medicao_inicial.parametrizacaofinanceiratabela",
                    ),
                ),
                (
                    "tipo_alimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametrizacoes_valores",
                        to="cardapio.tipoalimentacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização Financeira Tabela Valor",
                "verbose_name_plural": "Parametrizações Financeiras Tabelas Valores",
                "unique_together": {("tabela", "tipo_alimentacao", "grupo")},
            },
        ),
    ]
