# Generated by Django 4.2.7 on 2024-04-11 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicao_inicial", "0040_add_parametrizacao_financeira"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametrizacaofinanceira",
            options={
                "ordering": ["-alterado_em"],
                "verbose_name": "Parametrização Financeira",
                "verbose_name_plural": "Parametrizações Financeiras",
            },
        ),
    ]
