ENDPOINT_ALERGIAS_INTOLERANCIAS = 'alergias-intolerancias'
ENDPOINT_CLASSIFICACOES_DIETA = 'classificacoes-dieta'
ENDPOINT_MOTIVOS_NEGACAO = 'motivos-negacao'
ENDPOINT_TIPOS_DIETA_ESPECIAL = 'tipos-dieta-especial'
ENDPOINT_ALIMENTOS = 'alimentos'
ENDPOINT_TIPO_CONTAGEM = 'tipo-contagem'
